### ISSUE TITLE
listView可以用VC做容器吗?

### ISSUE THREAD

**Issue by JW-chenjingwei** [pujiaxin33/JXPagingView#10]
_listViewArray 可以用vc1.view, vc2.view ...想各个分页内容由各自的控制器管理,需要怎么设置?

**Comment by pujiaxin33** [comment]
只能直接放view，你可以把VC.view的class给改成遵从了JXPagingViewListViewDelegate代理的自定义view，在loadView里面修改

**Comment by pujiaxin33** [comment]
你好最新1.0.0版本已经支持列表用VC做容器，而且不至于VC，只要遵从`JXPagerViewListViewDelegate`协议的类都可以当做列表容器。
