### ISSUE TITLE
CollectionView设置ContentInset时有问题

### ISSUE THREAD

**Issue by CliffVardant** [pujiaxin33/JXPagingView#100]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
下方ContentViewController的滑动视图是UICollectionView，设置contentInset.top时，会出现奇怪的抖动。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：OC
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

如果想做成像马蜂窝那种类型，请问这个库支持吗
[https://s2.ax1x.com/2019/07/05/ZacFsK.md.png](url)

**Comment by pujiaxin33** [comment]
你能有关键代码么？
还有是这个图片点击点开有问题，看不了。

**Comment by pujiaxin33** [comment]
马蜂窝这个效果没有问题啊，就是list是collectionView而已，你有什么难点吗？

**Comment by CliffVardant** [comment]
当collectionview设置了contentInset.top后，滑动起来就很奇怪。
这是我demo的设置，你可以看看
[下载链接](https://pan.baidu.com/s/1qF8IXXI_bmHA03NzuvLHLg)

**Comment by pujiaxin33** [comment]
你能传我qq邮箱吗： 317437084@qq.com  百度非让我下载网盘，很不爽

**Comment by CliffVardant** [comment]
> 你能传我qq邮箱吗： [317437084@qq.com](mailto:317437084@qq.com) 百度非让我下载网盘，很不爽

好的，发过去了

**Comment by pujiaxin33** [comment]
加上`_collectionView.delegate = self;`才能收到滚动的回调。

**Comment by CliffVardant** [comment]
> 加上`_collectionView.delegate = self;`才能收到滚动的回调。

好的，这是我的失误，漏写了这个。
但写上后，contentInset没有生效啊😂

**Comment by pujiaxin33** [comment]
别急，目前暂不支持列表设置了contentInset，我正在看代码

**Comment by pujiaxin33** [comment]
最新版本1.1.14，已经兼容处理了。

**Comment by CliffVardant** [comment]
我更新了你的库后，设置了contentInset后，vertical方向的滑动没问题了。
但在contentInset.top区域内设置一个horizon的CollectionView后，发现无法滚动了😂
在ContainerViewController中也做了相关的手势设置
```
- (BOOL)mainTableViewGestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    //禁止categoryView左右滑动的时候，上下和左右都可以滚动
    UICollectionView *horizonCollectionView = ((TestViewController *)[self.pagerView.validListDict objectForKey:@(self.categoryView.selectedIndex)]).horizonCollectionView;
    if (otherGestureRecognizer == self.categoryView.collectionView.panGestureRecognizer || otherGestureRecognizer == horizonCollectionView.panGestureRecognizer) {
        return NO;
    }
    return [gestureRecognizer isKindOfClass:[UIPanGestureRecognizer class]] && [otherGestureRecognizer isKindOfClass:[UIPanGestureRecognizer class]];
}
```

**Comment by pujiaxin33** [comment]
把你最新demo发给我呢？

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/60763092-c5c86680-a09f-11e9-88f5-b21fd3bb02e9.png)
红色箭头两处，上面添加，下面删除。

**Comment by pujiaxin33** [comment]
还有就是一点小小的建议，写demo验证的时候，尽量严谨一点点，比如上面漏代码这个还是比较低级的错误，这样子你找别人，看了半天结果就是无关紧要的逻辑漏洞，这个还是很浪费时间的哈。
当然如果你充分思考验证也解决不了的问题，我也是愿意解答的。

**Comment by CliffVardant** [comment]
感谢你解答我的疑问，star已送上😁
