### ISSUE TITLE
你好，能否支持headerVIew高度的动态改变，目前是必须刷新，这样改变高度效果比较生硬

### ISSUE THREAD

**Issue by xuhuaping** [pujiaxin33/JXPagingView#101]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
如何动态改变呢？你能详细举一个应用例子呢?

**Comment by xuhuaping** [comment]
> 如何动态改变呢？你能详细举一个应用例子呢？

比如展开收起

**Comment by pujiaxin33** [comment]
给个截图呢？

**Comment by xuhuaping** [comment]
> 给个截图呢？

![IMG_0528](https://user-images.githubusercontent.com/18001988/60781230-1b6e4300-a174-11e9-9a1f-09a1caa7200f.jpg)
![IMG_0529](https://user-images.githubusercontent.com/18001988/60781231-1b6e4300-a174-11e9-9abd-3743d99b6795.jpg)
这样

**Comment by pujiaxin33** [comment]
因为上面整个视图是`UITableView.tableHeaderView`，然后我去stackoverflow上面找了一圈都没有找到，动画更新`tableHeaderView`的方法。
所以，问题就转为如何用动画的方式更新`UITableView.tableHeaderView`？

**Comment by pujiaxin33** [comment]
貌似这个方法可以，[link](https://stackoverflow.com/questions/15432792/animate-uitableview-headers-when-animating-tableheaderview-in?rq=1)
让我再润色一下代码

**Comment by pujiaxin33** [comment]
你下载最新的代码，swift版本的demo，新增了一个`HeightChangeAnimationViewController`类示例。目前写了一个很粗糙的示例，用于验证可行性，你看一下。顺便看看如何优化示例，能给一个完整的PullRequest就更好了。

**Comment by xuhuaping** [comment]
> 你下载最新的代码，快捷版本的演示，了新增一个`HeightChangeAnimationViewController`类示例。目前写了一个很粗糙的示例，用于验证可行性，你看一下。顺便看看如何优化示例，能给一个完整的PullRequest就更好了。

好的

**Comment by xuhuaping** [comment]
> 你下载最新的代码，swift版本的demo，新增了一个`HeightChangeAnimationViewController`类示例。目前写了一个很粗糙的示例，用于验证可行性，你看一下。顺便看看如何优化示例，能给一个完整的PullRequest就更好了。

这样效果可以，有点小问题，我开始默认高度300，改变为100后滑动到底部之后再上拉一下，然后把高度改为300，就会上下跳动一下

**Comment by pujiaxin33** [comment]
可以反复修改啊，好吧，需求是无穷无尽的，明天再看看吧，还有你有类似效果的app可以让我参考一下吗？就是已经上线了的，有同类效果的app

**Comment by zhouaaa** [comment]
如何上拉刷新下拉加载更多 
![Simulator Screen Shot - iPhone Xs Max - 2019-07-11 at 20 27 24](https://user-images.githubusercontent.com/13092196/61050808-67421600-a41a-11e9-9371-758901771929.png)

**Comment by pujiaxin33** [comment]
@zhouaaa 第一，能麻烦你再仔细有条理的梳理下问题吗？没有看懂。第二，你这是另一个问题了吧，麻烦你重新看一个issure提问吧。

**Comment by xuhuaping** [comment]
> 可以反复修改啊，好吧，需求是无穷无尽的，明天再看看吧，还有你有类似效果的应用程序可以让我参考一下吗？就是已经上线了的，有同类效果的应用

是的  可以反复展开收起  同类效果可以参考微信朋友圈文字的展开收起

**Comment by xuhuaping** [comment]
> @zhouaaa第一，能麻烦你再仔细有条理的梳理下问题吗？没有看懂。第二，你这是另一个问题了吧，麻烦你重新看一个issure提问吧。

这不是我提的呀

**Comment by pujiaxin33** [comment]
> > 你下载最新的代码，swift版本的demo，新增了一个`HeightChangeAnimationViewController`类示例。目前写了一个很粗糙的示例，用于验证可行性，你看一下。顺便看看如何优化示例，能给一个完整的PullRequest就更好了。
> 
> 这样效果可以，有点小问题，我开始默认高度300，改变为100后滑动到底部之后再上拉一下，然后把高度改为300，就会上下跳动一下

我更新了demo示例，并没有出现你说的情况，你重新clone最新demo，尝试在demo上面复现呢？

**Comment by pujiaxin33** [comment]
我对动画更新高度，进行了终极版本优化，你clone最新仓库体验一把，相信我，没有毛病了。准备明天出个新版本。

**Comment by pujiaxin33** [comment]
1.1.15版本发布
