### ISSUE TITLE
mainTableView已经显示了header，listView的contentOffset重置时，listView自身的ContentInset将被重置

### ISSUE THREAD

**Issue by w258958134** [pujiaxin33/JXPagingView#102]
mainTableView已经显示了header，listView的contentOffset重置时，listView自身的ContentInset将被重置

**Comment by pujiaxin33** [comment]
你的意思是listView的contentOffset重置时，希望ContentInset被重置吗？

**Comment by w258958134** [comment]
是希望能保持住ContentInset 
- (void)setListScrollViewToMinContentOffsetY:(UIScrollView *)scrollView {
    scrollView.contentOffset = CGPointMake(-scrollView.contentInset.left, [self minContentOffsetYInListScrollView:scrollView]);
}
我这样设置的就可以了

**Comment by pujiaxin33** [comment]
哦，忽略了还有`scrollView.contentInset.left`的情况

**Comment by pujiaxin33** [comment]
我修改为这样子，这样子就不会影响到列表的contentOffset.x了：
```Swift
func setListScrollViewToMinContentOffsetY(_ scrollView: UIScrollView) {
        scrollView.contentOffset = CGPoint(x: scrollView.contentOffset.x, y: minContentOffsetYInListScrollView(scrollView))
    }
```
