### ISSUE TITLE
tableView的delegate会被置空

### ISSUE THREAD

**Issue by CliffVardant** [pujiaxin33/JXPagingView#103]
**Feature描述**
希望滑动事件的delegate与系统的delegate区分开。
我在项目使用时，遇到了点击cell push至下个页面，返回后发现tableview的delegate被置为nil了。
我也不敢肯定是不是这个库的问题😂，只是希望能把双方的delegate区分开，好做下一步的问题定位

**Comment by pujiaxin33** [comment]
你说的是哪两个`delegate`，你截图说明一下吗？

**Comment by CliffVardant** [comment]
我指的是`JXPagerViewListViewDelegate`里滑动事件的回调和`UITableViewDelegate`

**Comment by pujiaxin33** [comment]
`JXPagerViewListViewDelegate`和`UITableViewDelegate`难道不是区分开的吗？

**Comment by CliffVardant** [comment]
我表述得不够清楚

**Comment by CliffVardant** [comment]
现在有个比较奇怪的bug
当categoryView贴到顶部，然后重复present或push多次ViewController。pager内无法响应点击事件。

**Comment by pujiaxin33** [comment]
内部没有操作ListView的UITableViewDelegate，只是通过一个scrollCallback回调接收列表的滚动回调。
第二你说的bug，能用demo复现吗？我需要排序是否是你项目的问题，还是这个库的问题。
