### ISSUE TITLE
在JXPagerView中子ListVc上拉刷新后一直不结束刷新状态，页面中的tableView也reload刷新不了UI

### ISSUE THREAD

**Issue by zhouaaa** [pujiaxin33/JXPagingView#104]
![Simulator Screen Shot - iPhone Xs Max - 2019-07-12 at 09 29 37](https://user-images.githubusercontent.com/13092196/61095824-993d9180-a487-11e9-80c8-22147638b9b6.png)

**Comment by zhouaaa** [comment]
listV中，我添加的是ViewController
/**
 返回listView。如果是vc包裹的就是vc.view；如果是自定义view包裹的，就是自定义view自己。
 
 @return UIView
 */
- (UIView *)listView
{
    return self.view;
}

**但我改成View做listv是，却能达到结束刷新状态**

**Comment by pujiaxin33** [comment]
建议你仔细梳理一下你的代码，列表的数据刷新，跟PagerView没有多大关系。

**Comment by zhouaaa** [comment]
换成View做子视图了
