### ISSUE TITLE
您好，请问怎么可以只刷新标题文字？

### ISSUE THREAD

**Issue by mokyz** [pujiaxin33/JXPagingView#105]
我现在执行 segmentedView.reloadData() 会刷新整个 segmentedView，有时候会导致标题颜色缩放等会闪一下，想知道怎么可以只刷信 segmentedView 标题的文字？

**Comment by pujiaxin33** [comment]
你这个问题跟JXPagingView有关系么？你是不是应该到JXCategoryView库提该问题？

**Comment by mokyz** [comment]
不好意思，没注意
