### ISSUE TITLE
pinSectionHeaderVerticalOffset 为负数时, 内容无法完全显示

### ISSUE THREAD

**Issue by urm9ril** [pujiaxin33/JXPagingView#106]
pinSectionHeaderVerticalOffset 为负数时, mainTableView 的 contentInset.top 会显示不玩这个. 可以测试一下 Demo 的最后一个, 将  pinSectionHeaderVerticalOffset 设置为 -50

**Comment by pujiaxin33** [comment]
pinSectionHeaderVerticalOffset为什么要设置为负数呢？这个属性初中就是设置为正数，然后让悬浮header向下偏移

**Comment by urm9ril** [comment]
负数是为了向上偏移, 
开始显示成这个样子 

<img width="373" alt="WX20190723-174039@2x" src="https://user-images.githubusercontent.com/20199378/61701604-0cd97b80-ad71-11e9-8828-6e4a41f247d4.png">

目标是显示成这个样子 

<img width="372" alt="WX20190723-174507@2x" src="https://user-images.githubusercontent.com/20199378/61702135-dc461180-ad71-11e9-9f79-729ca3ed8ae1.png">

我设置为负数的目的是为了让他藏在导航条的后面.

**Comment by pujiaxin33** [comment]
那你参考导航栏隐藏示例，源代码里面有说明
