### ISSUE TITLE
OC 版动态修改headerView的高度 貌似不行啊

### ISSUE THREAD

**Issue by Jack-Rain** [pujiaxin33/JXPagingView#107]
@implementation PagingViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    self.h = 200;
    self.view.backgroundColor = [UIColor whiteColor];
    self.navigationController.navigationBar.translucent = false;
    _titles = @[@"能力", @"爱好", @"队友"];

    _userHeaderView = [[PagingViewTableHeaderView alloc] init];
    _userHeaderView.tapAction = ^{
        if (self.h == 100) {
            self.h = 200;
        } else {
            self.h = 100;
        }
        [self.pagerView resizeTableHeaderViewHeightWithAnimatable:YES duration:0.25 curve:UIViewAnimationCurveEaseInOut];
    };

**Comment by Jack-Rain** [comment]
OC版少了 self.tableHeaderContainerView = containerView;

**Comment by pujiaxin33** [comment]
感谢反馈，已经修复，预计在1.1.16版本更新

**Comment by Jack-Rain** [comment]
> 感谢反馈，已经修复，预计在1.1.16版本更新

在headerView 高度很大的情况下 当滑动到sectionHeader的时候 不知道为啥会卡顿一下
