### ISSUE TITLE
iOS8.1出现闪退

### ISSUE THREAD

**Issue by sysworker** [pujiaxin33/JXPagingView#108]
**bug描述**
我在适配老机性，老版本的时候，出现了一个闪退，新版本都运行正常

**版本号**
1.JXPagingView版本号：(1.1.0)
2.OC还是Swift版本：OC
3.手机系统版本号：8.1
4.手机型号：iPhone5s

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryBaseView 
2.具体的操作步骤是：我在首页启动会闪退

**截图、GIF**
![file1](https://user-images.githubusercontent.com/16078882/62190233-7118c280-b3a3-11e9-9aa6-5f5825b18539.png)

![演示](https://user-images.githubusercontent.com/16078882/62190278-8ee62780-b3a3-11e9-9593-4302c79a087e.gif)

**Comment by sysworker** [comment]
> **bug描述**
> 我在适配老机性，老版本的时候，出现了一个闪退，新版本都运行正常
> 
> **版本号**
> 1.JXPagingView版本号：(1.1.0)
> 2.OC还是Swift版本：OC
> 3.手机系统版本号：8.1
> 4.手机型号：iPhone5s
> 
> **复现步骤**
> 
> 1. 遇到问题的相关效果、类是：JXCategoryBaseView
>    2.具体的操作步骤是：我在首页启动会闪退
> 
> **截图、GIF**
> ![file1](https://user-images.githubusercontent.com/16078882/62190233-7118c280-b3a3-11e9-9aa6-5f5825b18539.png)

**Comment by pujiaxin33** [comment]
你看一下崩溃的时候self.titleFont是否为nil，自己再进一步排查原因呢？

**Comment by sysworker** [comment]
是的我这里有设置
在2019年07月31日 15:39，暴走的鑫鑫<notifications@github.com> 写道：

你看一下崩溃的时候self.titleFont是否为nil，自己再进一步排查原因呢？

**Comment by pujiaxin33** [comment]
> 是的我这里有设置

啥意思，能表达清楚点吗

**Comment by sysworker** [comment]
我现在使用iPhone5s   8.1的系统会闪退，具体位置在


当我把判断注释掉就可以了，是不是这个方法没有兼容8.1系统
在2019年07月31日 15:47，暴走的鑫鑫<notifications@github.com> 写道：

是的我这里有设置

啥意思，能表达清楚点吗

**Comment by pujiaxin33** [comment]
咱们先不管它兼不兼容，第一要务是找到崩溃的原因，所以，你可以尝试打印当前函数的所有变量，看看哪里有问题。先找原因。

**Comment by sysworker** [comment]
找到问题了，我把设置字体的位置修改了下就好了



[UIFontfontWithName:@"PingFangSC-Medium"size:16.f]




换成

[UIFont boldSystemFontOfSize:16.f]

在2019年07月31日 15:55，暴走的鑫鑫<notifications@github.com> 写道：

咱们先不管它兼不兼容，第一要务是找到崩溃的原因，所以，你可以尝试打印当前函数的所有变量，看看哪里有问题。先找原因。

**Comment by pujiaxin33** [comment]
👍等于说iOS8.1没有这个字体`[UIFontfontWithName:@"PingFangSC-Medium"size:16.f]`

**Comment by sysworker** [comment]
是的，我这边做下判断吧




在2019年07月31日 16:04，暴走的鑫鑫<notifications@github.com> 写道：

👍等于说iOS8.1没有这个字体[UIFontfontWithName:@"PingFangSC-Medium"size:16.f]
