### ISSUE TITLE
tileview可以跟headerview重合吗？

### ISSUE THREAD

**Issue by YellBinn** [pujiaxin33/JXPagingView#109]
**Feature描述**
tileview可以跟headerview重合吗？

**参考效果**
如果你想要实现一个其他APP已有的效果：
3.目标效果截图：？
淘宝店铺页面

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
你能截图说明一下吗？

**Comment by YellBinn** [comment]
大框是header 小框是标题
![image](https://user-images.githubusercontent.com/13357868/62684293-f713b980-b9f2-11e9-8b23-dd0645ffc7da.png)

**Comment by YellBinn** [comment]
大致效果是这样的 框架能实现吗？

**Comment by pujiaxin33** [comment]
就是大框框，是整个悬浮的哇

**Comment by pujiaxin33** [comment]
你给一个可以体验的app以及具体页面呢？我去体验一下

**Comment by YellBinn** [comment]
淘宝的店铺详情页 哈哈  你看一下

**Comment by pujiaxin33** [comment]
我看了一下，它也只是小框悬浮，上面的内容也是会被推到屏幕外。只是背景是透明的，统一加了红色背景而已。

**Comment by YellBinn** [comment]
嗯 好的
