### ISSUE TITLE
JXPagingViewListViewDelegate func listScrollView() -> UIScrollView 崩溃

### ISSUE THREAD

**Issue by Onetaway** [pujiaxin33/JXPagingView#111]
**版本号**
1.JXPagingView版本号：1.1.16
2.OC还是Swift版本：Swift
3.手机系统版本号：iOS 12.4
4.手机型号：xs Mas
5.JXCategoryView版本号: 1.3.16

JXPagingViewListViewDelegate func listScrollView() -> UIScrollView 崩溃
报错:Fatal error: Unexpectedly found nil while implicitly unwrapping an Optional value   这个错误前面还有一些约束错误

[LayoutConstraints] Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want. 
	Try this: 
		(1) look at each constraint and try to figure out which you don't expect; 
		(2) find the code that added the unwanted constraint or constraints and fix it. 
(
    "<NSLayoutConstraint:0x2802cc550 V:|-(0)-[live.UserProfileHeaderView:0x107107c90]   (active, names: '|':UIView:0x10710d3b0 )>",
    "<NSLayoutConstraint:0x2802cd450 live.UserProfileHeaderView:0x107107c90.bottom == UIView:0x10710d3b0.bottom   (active)>",
    "<SnapKit.LayoutConstraint:0x28058ae80@UserProfileViewController.swift#262 live.UserProfileHeaderView:0x107107c90.height == 392.0>",
    "<NSLayoutConstraint:0x2802ef570 'UIView-Encapsulated-Layout-Height' UIView:0x10710d3b0.height == 400   (active)>"
)

Will attempt to recover by breaking constraint 
<SnapKit.LayoutConstraint:0x28058ae80@UserProfileViewController.swift#262 live.UserProfileHeaderView:0x107107c90.height == 392.0>

**Comment by pujiaxin33** [comment]
` Unexpectedly found nil while implicitly unwrapping an Optional value`明显是你返回了一个nil对象，你自己打上全局断点，就知道哪里有错误强解了。
