### ISSUE TITLE
pod 安装失败

### ISSUE THREAD

**Issue by luo-h** [pujiaxin33/JXPagingView#112]
pod repo update后一样的失败

[!] Error installing JXPagingView
[!] /usr/bin/git clone https://github.com/pujiaxin33/JXPagingView.git /var/folders/5r/_pp8zg490m5714v421m44q0h0000gn/T/d20190813-25392-cxvjs3 --template= --single-branch --depth 1 --branch 1.1.8

Cloning into '/var/folders/5r/_pp8zg490m5714v421m44q0h0000gn/T/d20190813-25392-cxvjs3'...
error: RPC failed; curl 56 LibreSSL SSL_read: SSL_ERROR_SYSCALL, errno 54
fatal: the remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed

**Comment by pujiaxin33** [comment]
网络问题，建议你稍后再试。
或者你可以百度一下如何把终端的http代理指向你的翻墙代理，这样子就可以快速install了。
