### ISSUE TITLE
你好  有关悬浮的视图,为什么往上滚动时悬浮视图直接顶到顶了,而不是慢慢滚动的效果

### ISSUE THREAD

**Issue by MoShenGuo** [pujiaxin33/JXPagingView#114]
![image](https://user-images.githubusercontent.com/21171688/63138662-dc9e9900-c00d-11e9-97a0-d917be265066.png)
你好 我是OC版本 master分支,看到你写的很不错,我把你的集成到的项目里,但是我的项目里 往上滚动时 悬浮视图直接滚动到顶了,而不是慢慢滚动,这是什么原因呢?望解答一下了,谢谢

**Comment by pujiaxin33** [comment]
请认真参考demo写法，你这个情况多半是scrollCallback没有正确回调。你自己再认真比对一下代码哈

**Comment by MoShenGuo** [comment]
> 请认真参考demo写法，你这个情况多半是scrollCallback没有正确回调。你自己再认真比对一下代码哈

对  我后面看到了,谢谢了,楼主写的不错
