### ISSUE TITLE
present出来一个控制器之后，再dismiss掉这个控制器，返回之后,headerView 会消失一下

### ISSUE THREAD

**Issue by Onetaway** [pujiaxin33/JXPagingView#116]
**bug描述**
present出来一个控制器之后，再dismiss掉这个控制器，返回之后,headerView 会消失一下

**版本号**
1.JXPagingView版本号：1.1.17
2.OC还是Swift版本：Swift
3.手机系统版本号：12.4
4.手机型号：xs Max

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：
点击tableview 里面的一个cell，弹出一个控制器，然后再关掉这个控制器，下面两个是控制器。

![gifhome_888x1920_10s](https://user-images.githubusercontent.com/3251826/63500752-07e92280-c4fd-11e9-95be-c8dbca808a30.gif)

**Comment by Onetaway** [comment]
作者看到了麻烦请回复一下，谢谢

**Comment by pujiaxin33** [comment]
请查看文档【常见问题与答案】，不能用列表VC来present，而是传递进来的navigationController，具体请看文档。

**Comment by pujiaxin33** [comment]
不能用列表VC来present，而是要用外面的VC来present

**Comment by Onetaway** [comment]
是 push 这个vc的vc  还是  navigationController?

**Comment by pujiaxin33** [comment]
只要是最外层的VC就行，你都试一下呢？

**Comment by Onetaway** [comment]
嗯 是因为这个原因，感谢解答，我关了
