### ISSUE TITLE
点击状态栏列表无法滚动到前

### ISSUE THREAD

**Issue by CivelXu** [pujiaxin33/JXPagingView#117]
**bug描述**
点击状态栏列表无法滚动到前

**版本号**
1.JXPagingView版本号：1.1.17
2.OC还是Swift版本：Swift
3.手机系统版本号：iOS12.4
4.手机型号：iPhoneX

**复现步骤**
如果tableHeaderView返回的内容包含了滚动视图 例如UICollectionView，
点击状态栏列表滚动到前的效果会无效，
如果tableHeaderView不包含滚动视图，点击状态栏， 能返回到列表前面， 无法返回到mainTableView前面

**Comment by pujiaxin33** [comment]
1.请将tableHeaderView的滚动视图的isScrollToTop设置为false
2.如果tableHeaderView有滚动视图，建议看一下这个库：[JXPageListView](https://github.com/pujiaxin33/JXPageListView)

**Comment by CivelXu** [comment]
@pujiaxin33  感谢回复； 滚动视图的isScrollToTop设置为false点击状态栏有效；
另外再问一下， 如果想实现点击状态栏 回到 mainTableView 顶部要怎么实现呢？

**Comment by pujiaxin33** [comment]
你需要先把当前列表的contentOffset设置为0（不能有动画，要立即生效）。然后你再滚动mainTableView到顶部即可。
