### ISSUE TITLE
主动调用子控制器内collectionView的scrollToItemAtIndexPath:问题

### ISSUE THREAD

**Issue by mikibw** [pujiaxin33/JXPagingView#118]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：1.1.15
2.OC还是Swift版本：OC
3.手机系统版本号：所有
4.手机型号：所有

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagerListRefreshView
2.具体的操作步骤是：带有header，在子控制器内部调用scrollToItemAtIndexPath:方法无法主动滚动到对应的item，只有在header到达顶部的时候调用该方法才有效。

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
请参考示例：
![image](https://user-images.githubusercontent.com/12654640/63821999-87557680-c981-11e9-836a-f2ca66938401.png)

**Comment by mikibw** [comment]
3q
