### ISSUE TITLE
改变JXPagingView高度， 列表内容大小不更新

### ISSUE THREAD

**Issue by CivelXu** [pujiaxin33/JXPagingView#119]
**bug描述**
JXPagingMainTableView中的UITableViewCell大小不正确

**版本号**
1.JXPagingView版本号：1.1.17
2.OC还是Swift版本：Swift
3.手机系统版本号：iOS12.4
4.手机型号：iPhoneX

**复现步骤**
1. 滑动JXPagingView， 顶部导航收缩， 调整JXPagingView布局， 增加高度；
2. JXPagingListContainerView 显示内容大小不正确，

**截图、GIF**
<img width="786" alt="WX20190828-190034@2x" src="https://user-images.githubusercontent.com/19768199/63850471-b93cfc00-c9c6-11e9-86a1-035db62d3107.png">

**Comment by pujiaxin33** [comment]
最下面cell，也就是`JXPagingListContainerView`所在的cell的高度，通过下面的方法计算：
```Swift
public func tableView(_ tableView: UITableView, heightForRowAt indexPath: IndexPath) -> CGFloat {
        return self.bounds.height - pinSectionHeaderHeight() - CGFloat(pinSectionHeaderVerticalOffset)
    }
```

所以你修改`JXPagingView`的布局，并没有触发到cell的重用。我不知道你的具体UI效果，也非常不建议动态修改`JXPagingView`的布局

**Comment by CivelXu** [comment]
尝试修改 mainTableView的contentinset 也会影响悬停的位置


| |
xuxiwen785
邮箱：xuxiwen785@163.com
|

Signature is customized by Netease Mail Master

在2019年08月29日 09:34，暴走的鑫鑫 写道：

最下面cell，也就是JXPagingListContainerView所在的cell的高度，通过下面的方法计算：

publicfunctableView(_tableView: UITableView, heightForRowAtindexPath: IndexPath) -> CGFloat {

        returnself.bounds.height-pinSectionHeaderHeight() -CGFloat(pinSectionHeaderVerticalOffset)

    }

所以你修改JXPagingView的布局，并没有触发到cell的重用。我不知道你的具体UI效果，也非常不建议动态修改JXPagingView的布局

**Comment by pujiaxin33** [comment]
首先最重要的建议，你可以尝试仔细描述你想要的效果，我看看能不能实现。
不然你又没有深入理解到视图结构，然后又强行修改，只会浪费时间。
