### ISSUE TITLE
楼主有木有博客分享一下实现思路？

### ISSUE THREAD

**Issue by chenshipeng** [pujiaxin33/JXPagingView#120]

**Comment by pujiaxin33** [comment]
好建议，可能只会给一个核心思路的说明，因为参数的边界处理都是反复调试出来的

**Comment by pujiaxin33** [comment]
[实现原理](https://github.com/pujiaxin33/JXPagingView/blob/master/Document/JXPagingView%E5%8E%9F%E7%90%86.md)
