### ISSUE TITLE
OC 版本的header如何能自适应高度呢

### ISSUE THREAD

**Issue by w258958134** [pujiaxin33/JXPagingView#121]
header里面有tableView, tableView通过监听contentSize的改变然后改变tableView的高度，从而自适应的改变整个header的高度，然后通过回调[self.pagerView reloadData]想更新pager的header高度,但是出现死循环卡死现象。

**Comment by pujiaxin33** [comment]
header部分有滚动视图的，建议先看一下这个库[JXPageListView](https://github.com/pujiaxin33/JXPageListView)

**Comment by w258958134** [comment]
> header部分有滚动视图的，建议先看一下这个库[JXPageListView](https://github.com/pujiaxin33/JXPageListView)
问一下 为什么这个JXPageListView库的代理不改成和JXPagerView库一样呢。

- (NSArray<UIView<JXPageListViewListDelegate> *> *)listViewsInPageListView:(JXPageListView *)pageListView {
    return self.listViewArray;
}

-(id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index{
    return self.listViewArray[index];
}

**Comment by pujiaxin33** [comment]
JXPageListView只提供了一个大概思路，有些细节没有完全按照JXPagingView来，如果你觉得有必要，欢迎提交一个PullRequest
