### ISSUE TITLE
关于交互的建议

### ISSUE THREAD

**Issue by dong09000** [pujiaxin33/JXPagingView#122]
**Feature描述**
请简单描述你想要的效果：iOS11 的大标题样式开启后，联动效果没有那么好

**参考效果**
嗯，基本就是参考作者的写的样子，在页面上写一下开启大标题就行了

**其他补充**
关于目标效果的其他说明：作者可以把代码里加入效果看一下。实在不行我也可以提交demo代码。
另外我在自己使用时，用DataSource代替Delegate来处理

**Comment by pujiaxin33** [comment]
还有接触过大标题，支持的版本都还比较老，稍后去尝试一下

**Comment by pujiaxin33** [comment]
你重新clone一下仓库，对于开启了大标题优化了显示，至于上下滑动的交互，也就只能那样子了，你先自己体验一下哈
