### ISSUE TITLE
能否有属性设置segment不悬停

### ISSUE THREAD

**Issue by huangyisheng** [pujiaxin33/JXPagingView#125]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
悬停的原理就是把分段视图放到UITableView的sectionHeader上面的，所以无法设置不悬停。
