### ISSUE TITLE
请问滚动到一个页面进行请求为什么卡

### ISSUE THREAD

**Issue by ljw215** [pujiaxin33/JXPagingView#127]
func pagingView(_ pagingView: JXPagingView, initListAtIndex index: Int) -> JXPagingViewListViewDelegate {}

请问我在这个代理方法里去请求每个新页面的数据，为什么会卡顿，应该咋样解决，谢谢

**Comment by pujiaxin33** [comment]
卡顿的问题需要你自己用TimeProfiler确认了，按理数据加载是异步的，这个卡顿问题，应该与本库无关。

**Comment by stgoodluck** [comment]
新页面请求，这个卡顿怎么解决的，求解

**Comment by pujiaxin33** [comment]
> 新页面请求，这个卡顿怎么解决的，求解

请自行用Instruments分析一下呢？页面请求卡顿，应该与该库无关。

**Comment by stgoodluck** [comment]
> func pagingView(_ pagingView: JXPagingView, initListAtIndex index: Int) -> JXPagingViewListViewDelegate {}
> 
> 请问我在这个代理方法里去请求每个新页面的数据，为什么会卡顿，应该咋样解决，谢谢

你解决了吗

**Comment by pujiaxin33** [comment]
@stgoodluck 你能提供一个复现问题的demo吗？

**Comment by stgoodluck** [comment]
> @stgoodluck 你能提供一个复现问题的demo吗？

我解决了，自己的问题
