### ISSUE TITLE
使用列表下拉刷新的时候 会导致MJRefresh的bug

### ISSUE THREAD

**Issue by xiaoChen666** [pujiaxin33/JXPagingView#129]
iOS 12.1 开启开发者慢网络模式
 加载多个视图 并且每个视图添加MJRefreshNormalHeader 将下拉的时间设置较长 10秒左右 来回切换子视图并且下拉会导致菊花框隐藏的情况（1下拉 切换到2 下拉 再回到1 1的加载菊花框不见了）

**Comment by pujiaxin33** [comment]
- (void)listDidAppear {
//    NSLog(@"%@", NSStringFromSelector(_cmd));
    //因为`JXCategoryListCollectionContainerView`内部通过`UICollectionView`的cell加载列表。当切换tab的时候，之前的列表所在的cell就被回收到缓存池，就会从视图层级树里面被剔除掉，即没有显示出来且不在视图层级里面。这个时候MJRefreshHeader所持有的UIActivityIndicatorView就会被设置hidden。所以需要在列表显示的时候，且isRefreshing==YES的时候，再让UIActivityIndicatorView重新开启动画。
    if (self.tableView.mj_header.isRefreshing) {
        UIActivityIndicatorView *activity = [self.tableView.mj_header valueForKey:@"loadingView"];
        [activity startAnimating];
    }
}

**Comment by xiaoChen666** [comment]
谢谢了..


发自我的 iPhone
