### ISSUE TITLE
滑动返回的事件

### ISSUE THREAD

**Issue by yangbo930204** [pujiaxin33/JXPagingView#13]
你好，请问，如何处理滑动返回的事件？比如如何与[FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture) 这个库结合使用？麻烦你了，这个问题好忧伤。。。

**Comment by pujiaxin33** [comment]
建议你查看这个库：[JXCategoryView](https://github.com/pujiaxin33/JXCategoryView)

里面有对手势处理进行介绍，多实践一下，应该没问题

**Comment by yangbo930204** [comment]
> 建议你查看这个库：[JXCategoryView](https://github.com/pujiaxin33/JXCategoryView)
> 
> 里面有对手势处理进行介绍，多实践一下，应该没问题

恩。感谢回复，其实改下[JXPagingView](https://github.com/pujiaxin33/JXPagingView)源码也可以，就是得fork，比较麻烦。

**Comment by yangbo930204** [comment]
附上我的解决方法：
修改 JXPagingListContainerView 里的UICollectionView，继承UICollectionView，重写下面的代理方法(解决方法同 [FDFullscreenPopGesture](https://github.com/forkingdog/FDFullscreenPopGesture#view-controller-with-scrollview) )

`open class CustomCollectionView: UICollectionView, UIGestureRecognizerDelegate {
    
    public func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        
        if contentOffset.x <= 0 {
            if let delegate = otherGestureRecognizer.delegate, delegate.isKind(of: NSClassFromString("_FDFullscreenPopGestureRecognizerDelegate")!) {
                return true
            }
        }
        return false
    }
}`
