### ISSUE TITLE
ios 9.3不见了标题

### ISSUE THREAD

**Issue by xhjss** [pujiaxin33/JXPagingView#131]
![WechatIMG22314](https://user-images.githubusercontent.com/7153138/65244869-12a7cf00-db1e-11e9-92d7-4fefe94781ad.jpeg)
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
像某些系统才出现的bug，建议检查一下约束，看一下视图层级

**Comment by pujiaxin33** [comment]
9.3版本，请使用JXCategoryView1.5.2版本，就不会有问题了。
