### ISSUE TITLE
SectionHeaderInPagerView  

### ISSUE THREAD

**Issue by HobaoKing** [pujiaxin33/JXPagingView#132]
**Feature描述**
请简单描述你想要的效果： 
     - (UIView *)viewForPinSectionHeaderInPagerView:(JXPagerView *)pagerView {
    return self.categoryView;
} 
类似于segmentedControl 四周边框线设置不能显示？

这样设置了无效
//        _categoryView.layer.cornerRadius = 15;
//        _categoryView.layer.masksToBounds = YES;
//        _categoryView.layer.borderColor = UIColorHex(0xcccccc).CGColor;
//        _categoryView.layer.borderWidth = 1/[UIScreen mainScreen].scale; 

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：
![image](https://user-images.githubusercontent.com/10751380/65315009-ec3f6d80-dbc9-11e9-9eb3-9e2616743034.png)

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
请到这个库：[https://github.com/pujiaxin33/JXCategoryView](https://github.com/pujiaxin33/JXCategoryView)
查看SegmentedControl效果，然后参考里面的示例代码:[示例类](https://github.com/pujiaxin33/JXCategoryView/blob/master/JXCategoryView/Example/SegmentedControl/SegmentedControlViewController.m)

**Comment by HobaoKing** [comment]
> 请到这个库：https://github.com/pujiaxin33/JXCategoryView
> 查看SegmentedControl效果，然后参考里面的示例代码:[示例类](https://github.com/pujiaxin33/JXCategoryView/blob/master/JXCategoryView/Example/SegmentedControl/SegmentedControlViewController.m)

好的，谢谢，已解决
