### ISSUE TITLE
main.m(@19)  *****出现崩溃异常，异常原因:Invalid row height (-109) provided by table delegate. Value must be at least 0.0, or UITableViewAutomaticDimension. 请查找解决

### ISSUE THREAD

**Issue by MrStock007** [pujiaxin33/JXPagingView#133]
**bug描述**
请简单描述你的bug现象。
使用JXPagingView，header是sdcircleScrollview，子控制器是UIviewcontroller，加uicollectionview
直接崩溃在xcode11（xcode模拟选的12.1的系统）手机版本是iOS13.（因为iOS13直接崩溃，）
main.m(@19)  *****出现崩溃异常，异常原因:Invalid row height (-109) provided by table delegate. Value must be at least 0.0, or UITableViewAutomaticDimension. 请查找解决
（xcode没升级前，没有问题xcode10 ，iOS12）

**版本号**
1.JXPagingView版本号：？
Using JXCategoryView (1.4.0)
Using JXPagingView (1.1.17)
2.OC还是Swift版本：？OC
3.手机系统版本号：？
ios13
4.手机型号：？iphone6sPlus(所有测试的都不行)

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
1.1.18版本已修复
