### ISSUE TITLE
滚动headerView的时候如果上拉有个惯性上划的话，到headerView被完全遮挡后，剩下的速度就无法被转移到下面的scrollView

### ISSUE THREAD

**Issue by LMYCoder** [pujiaxin33/JXPagingView#134]
例如微博的个人主页，你往上滑headerView，有一个速度，松手时整个scrollView还在滑动，到headerView完全隐藏后，滑动会继续进行，而不是直接停止，这个库貌似目前不支持，无论一开始速度多快，当headerView完全被遮挡后，滚动直接停止

**Comment by pujiaxin33** [comment]
是的，这个库实现不了继续滚动。鱼和熊掌不可兼得

**Comment by LMYCoder** [comment]
这么绝对吗？有没有谁改改？或者作者再改下，加上这功能？

**Comment by pujiaxin33** [comment]
@LMYCoder @junnnerr 皇天不负有心人，在最新仓库添加了一个JXPagerSmoothView类，目前只有OC版本有，用新的原理实现了这个效果。你们可以clone最新的仓库看看。

**Comment by pujiaxin33** [comment]
@LMYCoder @junnnerr 预计会在1.2.0版本发布

**Comment by LMYCoder** [comment]
大佬流弊了，给力
