### ISSUE TITLE
关于JXPagerView设置默认选中index的问题

### ISSUE THREAD

**Issue by inoryshu** [pujiaxin33/JXPagingView#135]
你好！我想请问一下有什么办法可以设置默认选中下标？我看在JXPagerView中只能设置categoryView的默认选中下标，却无法设置JXPagerView的默认选中index！

**Comment by pujiaxin33** [comment]
文档里面就有答案：
指定默认选中index
默认显示index=2的列表，代码如下：

self.pagerView.defaultSelectedIndex = 2;
self.categoryView.defaultSelectedIndex = 2;

**Comment by inoryshu** [comment]
哦！不好意思。我以为有用的是最新版的，记错了。
