### ISSUE TITLE
是否支持CategoryView添加在头图上？是否支持CategoryView背景色为透明色？

### ISSUE THREAD

**Issue by Amelia1202** [pujiaxin33/JXPagingView#136]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
可以的，你自己尝试一下就知道了

**Comment by Amelia1202** [comment]
> 可以的，你自己尝试一下就知道了

我看了视图层级，headerView是在categoryView上面的，是否能类似淘宝店铺首页一样headerView和categoryView重合呢？就是底图能透到categoryView去，然后是一个整体的效果。
<img width="374" alt="pic" src="https://user-images.githubusercontent.com/47619343/71573774-834c8780-2b20-11ea-99a7-3ab9590bc7f5.png">

**Comment by pujiaxin33** [comment]
我在oc版本添加了【顶部背景图】示例，仅提供一个思路，其他细节请自己补充实现。

**Comment by Amelia1202** [comment]
> 我在oc版本添加了【顶部背景图】示例，仅提供一个思路，其他细节请自己补充实现。

好的，谢谢。
