### ISSUE TITLE
当向下拉动时让子滚动视图滚动

### ISSUE THREAD

**Issue by AbnerZS** [pujiaxin33/JXPagingView#137]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

在使用改项目时, 当设置有下沉内容(类似哔哩哔哩视频播放页)时,  当向下滑动时能否设置主滚动视图不动, 而让子滚动视图进行滚动
类似操作: 打开哔哩哔哩, 进入视频播放页, 向下拉动, 此时是视频简介内容滚动而不是主滚动视图

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
这种效果，你就不需要JXPagingView了，自己布局就行

**Comment by AbnerZS** [comment]
当播放暂停的时候会整体滚动，当播放进行的时候左右滚动，上下滚动，用你这个框架还是很方便的

发自我的 iPhone6s

**Comment by pujiaxin33** [comment]
我有一个类似的需求，当需要上下滚动的时候，设置pinSectionHeaderVerticalOffset=0，并且reloadData；
当顶部需要固定的时候，设置pinSectionHeaderVerticalOffset=视频视图的高度，并且reloadData；
思路就是这样的，你自己多尝试一下

**Comment by isdotjim** [comment]
搭个车...
想邀请Repo作者来w3c.group创建项目的对应小组。w3c.group是类似知识星球的社群工具，小组可设置为付费且有赞助功能，同时也是一个区块链主导的创作者社区。这是相关介绍：
http://t.cn/Ai1vLcCU
http://t.cn/Ai1vLcCG
http://t.cn/Ai1vLcCA
