### ISSUE TITLE
滚动列表时，categoryView无法响应点击事件

### ISSUE THREAD

**Issue by whatsbug** [pujiaxin33/JXPagingView#139]
**bug描述**
滚动列表时，categoryView无法响应点击事件

**版本号**
1.JXPagingView版本号：1.1.19
2.OC还是Swift版本：OC
3.手机系统版本号：12.4
4.手机型号：模拟器iPhone XR

**复现步骤**
在列表滚动时，单击categoryView，第一次单击时无法切换页面，第二次才阔以

**截图、GIF**
注意看截图，我是单击了两次才能切换页面，而且这个bug是必现的
![Kapture 2019-11-02 at 18 31 12](https://user-images.githubusercontent.com/7418617/68069921-fac09d80-fda1-11e9-9c13-b1000bd5caa5.gif)

**Comment by pujiaxin33** [comment]
确实有这个问题，但是还没有找到问题点

**Comment by pujiaxin33** [comment]
经过分析，这是系统自带的特性。
你可以打开微信，首页聊天列表，你滚动的时候，第一次点击会先停止滚动，再次点击才会跳转。
或者你一只手滚动列表，一只手去点击，也不会响应点击。只要你点击的元素是列表的子视图，都不能跳转。
这应该是当前的手势被列表滚动占有了，就不会允许他的子视图有其他响应。

**Comment by whatsbug** [comment]
不是系统特性哦，你可以尝试多几个App或者你自己的另一个框架JXCategoryView都没有这样的问题。。

**Comment by pujiaxin33** [comment]
请关注这句话【只要你点击的元素是列表的子视图，都不能跳转。】重点时【指示图】
如果只是JXCategoryview的示例的话JXCategoryview和下面的列表视图是分割开的，所以没有这个问题。

**Comment by whatsbug** [comment]
试试转转首页，应该是你说的【只要你点击的元素是列表的子视图】这种情况，但转转还是能正常转跳的

**Comment by pujiaxin33** [comment]
想不到你这么执着，看来我只有告诉你真相了😀（纯属活跃气氛）
你左手滚动转转首页的列表，但是不要让选择器悬浮到顶部，这个时候你点击一下试试呢？是不是点击不了呢？
那么为什么滚动到顶部的时候，又能点击呢？给你3秒钟，用你聪明的小脑袋想想呢。
没有错，悬浮到顶部的时候，它把视图放置到VC.view上面了，而不是在列表上面。
什么❓你还不信
你自己可以逆向研究一下，看下转转的视图层级就有答案了。

**Comment by whatsbug** [comment]
😂老哥不是我执着，我站在用户角度(非程序员，不知道你的具体实现)体验你的框架，我发现我在滚动列表时无法切换页面，我的第一反应这是bug，然后反馈了给你。然后你告诉我这不是bug，这是系统特性。我就觉得不合理，我心里想哪个系统特性这么坑，要用户第二次交互才给出反馈，以前我用过的拥有类似UI结构的App都不是这样子的啊。于是我把我用过的App介绍给你，然后你告诉我在A情况下转转也不能切换页面，只不过在B情况下它通过某实现 实现了页面切换。可我上面截图给你反馈的都是B情况啊😂，一个用户可能用到他卸载App他都发现不了A情况。
现在站在程序员的角度我理解你说的为什么要第二次点击才能切换页面，可是以后用这个框架的绝大部分都是普通用户啊，他们也会觉得需要二次点击才能切换页面是个“bug”。所以是不是说尽管在程序员的角度这不是bug，是系统特性。但在用户的角度这个框架是不是还缺少跟转转一样的“某实现”呢。。

**Comment by pujiaxin33** [comment]
我知道你说得很有道理，但是事实就是如此。
我也不知道如何修复这个【系统特性】，让用户感受不到这个【bug】。

**Comment by whatsbug** [comment]
哈哈那先不管了

**Comment by pujiaxin33** [comment]
新增加了`JXPagerSmoothView`和`JXPagingSmoothView`，使用新的原理实现了该效果，可以达到列表滚动的时候，点击categoryView可以切换页面。预计1.2.0发布
