### ISSUE TITLE
不知道JXPagingViewListViewDelegate代理怎样设置

### ISSUE THREAD

**Issue by chen7788** [pujiaxin33/JXPagingView#14]
不知道JXPagingViewListViewDelegate代理怎样设置，preferredListViewsArray()返回的数组，数组里的对象怎样遵循JXPagingViewListViewDelegate，不然对象无法遵循这个协议

**Comment by pujiaxin33** [comment]
请参考demo里面的如下代码：
```
extension VCListViewController: JXPagingViewListViewDelegate {
    func listView() -> UIView {
        return self.view
    }

    func listScrollView() -> UIScrollView {
        return contentView.tableView
    }

    func listViewDidScrollCallback(callback: @escaping (UIScrollView) -> ()) {
        contentView.listViewDidScrollCallback = callback
    }
}
```

**Comment by chen7788** [comment]
因为不知道哪里设置代理，我意思这个控制器无法遵守这个协议

**Comment by pujiaxin33** [comment]
只要遵守这个协议即可，无需设置代理。
如果是oc，在SubscriptionController.h遵从JXPagingViewListViewDelegate代理。
如果是swift，就按照我上面发的做。

**Comment by chen7788** [comment]
你好，func preferredPagingView() -> JXPagingView {
        return JXPagingView(delegate: self)
    }
Thread 1: Fatal error: NSArray element failed to match the Swift Array Element type
创建JXPagingView(delegate: self)时报错

**Comment by pujiaxin33** [comment]
建议你按照demo操作，跟库无关的问题，请百度研究

**Comment by chen7788** [comment]
是和demo一样的，直接考过去也抱着错，我是pod导入库不是直接拖进去的，这个是初始化库报错，和库相关呢

**Comment by pujiaxin33** [comment]
建议你将你的代码：
```
func preferredListViewsArray() -> [JXPagingViewListViewDelegate] {
return [SubscriptionController(),SubscriptionController(),SubscriptionController()]
}
```
修改为：
```
func listViews(in pagingView: JXPagingView) -> [ JXPagingViewListViewDelegate] {
        var listViewArray:[JXPagingViewListViewDelegate] = [yourInstance1, yourInstance2]
        return listViewArray
    }
```
参考这篇文章：[fatal error: NSArray element failed to match the Swift Array Element type](https://stackoverflow.com/questions/25484554/fatal-error-nsarray-element-failed-to-match-the-swift-array-element-type/25785471)
