### ISSUE TITLE
保有主頁下拉刷新+懸浮Header位置調整

### ISSUE THREAD

**Issue by FrankWuoO** [pujiaxin33/JXPagingView#141]
**Feature描述**
请简单描述你想要的效果：
同時保有主頁下拉刷新+懸浮Header位置調整

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：
應用場景在於畫面可以再導航列消失時，主頁可以下拉刷新
目前是卡在當有拉更新控件與pagingView.pinSectionHeaderVerticalOffset有值時
下拉更新動畫會突然消失

依照以下步驟可以重現
在範例RefreshViewController類中新增
pagingView.pinSectionHeaderVerticalOffset = 44
則導致下拉更新動畫不完全，一下就消失
想保有pinSectionHeaderVerticalOffset彈性並可以支援下拉刷新
p.s.下拉更新是用原生 UIRefreshControl 控件（非MJRefresh）
let refreshControl = UIRefreshControl()
refreshControl.addTarget(self, action: #selector(headerRefresh), for: .valueChanged)
pagingView.mainTableView.refreshControl = refreshControl

**Comment by pujiaxin33** [comment]
demo示例就是使用的MJRefresh，按照你说得，在RefreshViewController里面添加`pagingView.pinSectionHeaderVerticalOffset = 44`代码，并没有出现你说得问题。建议你使用MJRefresh

**Comment by xierwanasi** [comment]
使用MJRefresh， 再把endRefreshing延迟调到10s， 去上下滑动会有问题
