### ISSUE TITLE
collectionview滑动弹跳问题

### ISSUE THREAD

**Issue by shengguangdaren** [pujiaxin33/JXPagingView#142]
我用JXPagerView做容器做左右切换效果，第一个列表用的tableview没问题，第二个列表用的colelctionview，然后发现上下滑动的时候会有弹跳的情况，我仔细对比了代码，发现和我第一个tableview列表只是控件的区别，相关的协议方法都实现了，请问这种情况可能是什么导致的

**Comment by pujiaxin33** [comment]
不知道呢？建议你看一下swift版本有个collectionView的使用示例，在对比一下呢?
在看看scrollCallBack有没有正确回调呢？

**Comment by shengguangdaren** [comment]
嗯好的

**Comment by githublsy** [comment]
> 嗯好的

兄弟你解决了吗

**Comment by shengguangdaren** [comment]
@githublsy 按照坐着说的方法去做了 ，但是还是会有 不过是偶尔的

**Comment by zyxiaofeng** [comment]
我也遇到了这个问题   是怎么解决的呢

**Comment by clearlovelyQ** [comment]
解决了嘛，我也有这个问题，jxcategoryview的listcontainerView第一个是collectionview，第二个是tableview，collectionView滑动的额时候，headerview会跳动，已经正常设置了scrollblock的滚动代理，还是没解决

**Comment by bestvideo** [comment]
@clearlovelyQ 可以提供一个复现的demo吗

**Comment by clearlovelyQ** [comment]
> 解决了嘛，我也有这个问题，jxcategoryview的listcontainerView第一个是collectionview，第二个是tableview，collectionView滑动的额时候，headerview会跳动，已经正常设置了scrollblock的滚动代理，还是没解决

已解决，因为自己用的iglistkit然后忘记设置collectionview的滚动代理了
