### ISSUE TITLE
默认显示在悬浮HeaderView的位置

### ISSUE THREAD

**Issue by a497500306** [pujiaxin33/JXPagingView#143]
**Feature描述**
请简单描述你想要的效果：默认显示在悬浮HeaderView的位置

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：微博
2.目标页面路径：微博首页点击某条微博的评论按钮跳转到详情页
3.目标效果截图：
![image](https://user-images.githubusercontent.com/12522414/69596834-ee490100-103e-11ea-8356-0df714c216d3.png)
![image](https://user-images.githubusercontent.com/12522414/69596881-1afd1880-103f-11ea-8f8d-16381aa5c4fe.png)

**Comment by pujiaxin33** [comment]
你参考如下代码：
```Swift
class RefreshViewController: BaseViewController {
    var isFirstLayout = true

    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        if isFirstLayout {
            isFirstLayout = false
            view.setNeedsLayout()
            view.layoutIfNeeded()
            pagingView.mainTableView.contentOffset = CGPoint(x: 0, y: 100)
        }
    }
}
```

**Comment by a497500306** [comment]
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        if self.vcJumpComment == true {
            vcJumpComment = false
            view.setNeedsLayout()
            view.layoutIfNeeded()
            self.pagingView.mainTableView.scrollToRow(at: IndexPath(row: NSNotFound, section: 0), at: UITableViewScrollPosition.top, animated: false)
            self.pagingView.mainTableView.contentOffset = CGPoint(x: 0, y: self.tableHeaderViewHeight - 40)
        }
    }
我是这样实现的,因为如果HeaderView位置超过一屏后,下面的cell会不加载,如果直接用contentOffset会出现抖动的情况,需要用scrollToRow,

**Comment by NSLog-YuHaitao** [comment]
请问oc怎么实现的
