### ISSUE TITLE
向下滚动卡顿

### ISSUE THREAD

**Issue by Hurdery** [pujiaxin33/JXPagingView#144]
**bug描述**
   设置self.pagerView.mainTableView.bounces = NO以后，向下滚动卡主不动

OC还是Swift版本：OC

**复现步骤**
设置self.pagerView.mainTableView.bounces = NO，必现

**截图、GIF**
![image](https://user-images.githubusercontent.com/13878993/69691571-6cbea500-110a-11ea-85d4-3be57e4cd813.png)

**Comment by pujiaxin33** [comment]
可以不把self.pagerView.mainTableView.bounces 设置为NO吗？

**Comment by pujiaxin33** [comment]
或者说不支持把self.pagerView.mainTableView.bounces设置为NO

**Comment by Hurdery** [comment]
因为我要做的功能是，隐藏导航栏，并且头视图要吸顶，所以能想到的办法只有设置这个bounces属性，那既然没办法，目前只能先这样了，以后有时间再优化吧，谢谢大佬回复！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"暴走的鑫鑫"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月27日(星期三) 中午1:42
收件人:&nbsp;"pujiaxin33/JXPagingView"<JXPagingView@noreply.github.com&gt;;
抄送:&nbsp;"gesture"<2522905745@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [pujiaxin33/JXPagingView] 向下滚动卡顿 (#144)




可以不把self.pagerView.mainTableView.bounces 设置为NO吗？
