### ISSUE TITLE
偏移量问题

### ISSUE THREAD

**Issue by shengguangdaren** [pujiaxin33/JXPagingView#146]
现在有需求需要外部更改偏移量 我使用此方法设置：    

```
[self.pagingView.mainTableView setContentOffset:CGPointMake(0, offset)];
```

发现无效。调试后看到mainTableView的偏移量永远是
```
-(NSUInteger)tableHeaderViewHeightInPagerView:(JXPagerView *)pagerView
```
此方法返回的高度,
请问我如何才能更改偏移量呢？

**Comment by pujiaxin33** [comment]
参考一下[默认显示在悬浮HeaderView的位置 #143](https://github.com/pujiaxin33/JXPagingView/issues/143)

**Comment by shengguangdaren** [comment]
尝试了下[默认显示在悬浮HeaderView的位置 #143](https://github.com/pujiaxin33/JXPagingView/issues/143)提供的方法，同样无效，并且该方法是在`viewDidLayoutSubviews `中执行且只执行一次，我的需求是需要多次更改偏移量，有暴露的api或者思路吗请问？

**Comment by pujiaxin33** [comment]
请参考OC版本示例【设置mainTableView contentOffset】

**Comment by NSLog-YuHaitao** [comment]
请问最终采用什么方法来多次更改偏移量

**Comment by pujiaxin33** [comment]
@shengguangdaren @NSLog-YuHaitao 
下面这段代码是设置默认的mainTableView contentoffset。也就是进入页面希望调整到的问题：
```Objectivie-c
- (void)viewDidLayoutSubviews {
    [super viewDidLayoutSubviews];

    if (self.isFirstLayout) {
        self.isFirstLayout = NO;
        [self.view setNeedsLayout];
        [self.view layoutIfNeeded];
        //mainTableView的默认偏移量设置方法
        self.pagerView.mainTableView.contentOffset = CGPointMake(0, 150);
    }
}
```

下面这段代码是页面显示之后想要再次调整的代码：
```Objective-c
//必须让self.pagerView.currentScrollingListView滚动到顶部，才能触发main列表的滚动所以这里的animated必须是NO
    [self.pagerView.currentScrollingListView setContentOffset:CGPointZero animated:NO];
    //然后让self.pagerView.mainTableView滚动到顶部，这里的animated可以为YES
    [self.pagerView.mainTableView setContentOffset:CGPointMake(0, 100) animated:NO];
```

所有的代码都是oc示例`MainTableViewOffsetViewController`类里面。

**Comment by YongTaiSin** [comment]
> ```objc
> //然后让self.pagerView.mainTableView滚动到顶部，这里的animated可以为YES
>     [self.pagerView.mainTableView setContentOffset:CGPointMake(0, 100) animated:NO];
> ```

这段代码在JXRefreshPagingView中第一次滚动会不准确，后面就准确了
