### ISSUE TITLE
使用SmoothListViewController 有数据不足，segmentedView不能悬浮时候的问题

### ISSUE THREAD

**Issue by Resoulte** [pujiaxin33/JXPagingView#148]
使用SmoothListViewController可以忽略数据多少的问题，切换的时候让segmentedView一直悬浮吗

[问题视频.zip](https://github.com/pujiaxin33/JXPagingView/files/3931505/default.zip)

**Comment by VillageMud** [comment]
1.监听子vc里面的scrollview的contentsize
2.如果contentsize.height< 你自己想要展示的高度，就好了

**Comment by pujiaxin33** [comment]
@Resoulte 我在最新的demo代码里面兼容了数据不足的情况，你可以下载最新的oc demo代码试一下，验证没有问题之后才会发布新版本

**Comment by Resoulte** [comment]
@pujiaxin33 可以，我试过了，辛苦了老哥

**Comment by pujiaxin33** [comment]
将会在2.0.0版本修复。
