### ISSUE TITLE
取消Tab切换后，滑动列表后，列表的位置不正确

### ISSUE THREAD

**Issue by D-meng** [pujiaxin33/JXPagingView#149]
**bug描述**
点击 Demo 首页 第一项：
第一步：然后向上滑动 能力 Tab 的列表，滑动到最底(不需要完全到底，只是为了现实效果更明显)
第二步：从能力 Tab 往 爱好 Tab 滑动，滑动一点点后，离开屏幕，让屏幕还是显示 能力 Tab
第三步：手指 从上往下 滑动 能力 Tab 列表

观察列表后发现，列表会显示 最上边的内容，继续滑动，顶部的那张图片就开始 显示出来了，不知道这个能不能优化一下？

**版本号**
1.JXPagingView版本号：1.2.2
2.OC还是Swift版本：OC

**Comment by pujiaxin33** [comment]
你用最新的仓库代码试一下呢？（还没有更新release包）进行了列表容器的重构，解决了此问题，但是还没有经过全面的测试，所以，需要你帮忙验证一下。等稳定之后会发新版本。

**Comment by D-meng** [comment]
> 你用最新的仓库代码试一下呢？（还没有更新release包）进行了列表容器的重构，解决了此问题，但是还没有经过全面的测试，所以，需要你帮忙验证一下。等稳定之后会发新版本。

点击Demo 首页 第三项<列表下拉刷新>，还是会有这个问题。只不过 bug 描述里的第三步，需要多移动一点距离，才会出现问题。
测试环境：iPhone 11 pro 模拟器 --- iOS 13.3

**Comment by pujiaxin33** [comment]
刚更新了代码，你再下载试试呢？

**Comment by D-meng** [comment]
> 刚更新了代码，你再下载试试呢？

这次应该是没什么问题了，我没有复现之前的问题

**Comment by pujiaxin33** [comment]
将会在2.0.0版本修复。
- **2.0.0版本**：`JXPagerListContainerView`进行了重构，列表拥有了完整的生命周期方法。列表是`UIViewController`类，`viewWillAppear`等生命周期方法将会正确触发。
- 
    - 删除了collectionView，用`scrollView`属性替换。
    - 和`CategoryView`的联动绑定代码更新为`self.categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pagerView.listContainerView;`。
    - `JXPagerView`新增`- (instancetype)initWithDelegate:(id<JXPagerViewDelegate>)delegate listContainerType:(JXPagerListContainerType)type`初始化方法，可以指定列表容器为`UIScrollView`或者`UICollectionView`；
