### ISSUE TITLE
方法不执行

### ISSUE THREAD

**Issue by TML007** [pujiaxin33/JXPagingView#150]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。
- (void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event 方法不执行
**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
谁的`(void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event `方法不执行，有详细的上下文吗？

**Comment by TML007** [comment]
> 谁的`(void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event `方法不执行，有详细的上下文吗？

我的列表UIViewController，在cell中有引用自定义的view，实现了(void)touchesBegan:(NSSet<UITouch *> *)touches withEvent:(UIEvent *)event，但是发现此方法在这里就不执行了，其他地方引入使用没问题。

**Comment by pujiaxin33** [comment]
建议你用JXPagerSmoothView试一下呢？
