### ISSUE TITLE
左右滑动会影响当前currentIndex

### ISSUE THREAD

**Issue by jasparchan** [pujiaxin33/JXPagingView#151]
因为触发了willDisplayCell，从而触发listDidAppear，导致currentIndex不对

**Comment by pujiaxin33** [comment]
你用最新的仓库代码试一下呢？（还没有更新release包）进行了列表容器的重构，解决了此问题，但是还没有经过全面的测试，所以，需要你帮忙验证一下。等稳定之后会发新版本。

**Comment by pujiaxin33** [comment]
将会在2.0.0版本修复。
- **2.0.0版本**：`JXPagerListContainerView`进行了重构，列表拥有了完整的生命周期方法。列表是`UIViewController`类，`viewWillAppear`等生命周期方法将会正确触发。
- 
    - 删除了collectionView，用`scrollView`属性替换。
    - 和`CategoryView`的联动绑定代码更新为`self.categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pagerView.listContainerView;`。
    - `JXPagerView`新增`- (instancetype)initWithDelegate:(id<JXPagerViewDelegate>)delegate listContainerType:(JXPagerListContainerType)type`初始化方法，可以指定列表容器为`UIScrollView`或者`UICollectionView`；
