### ISSUE TITLE
如何保留UItableView 和 滚动Y轴 不被重置

### ISSUE THREAD

**Issue by TzyTman** [pujiaxin33/JXPagingView#155]
- (void)setListScrollViewToMinContentOffsetY:(UIScrollView *)scrollView {
    scrollView.contentOffset = CGPointMake(scrollView.contentOffset.x, [self minContentOffsetYInListScrollView:scrollView]);
}

**Comment by pujiaxin33** [comment]
只要当任一列表滚动到显示了顶部headerview之后，都会将其他列表同步滚动到最上面。不然这个时候列表左右切换，每个列表的偏移量不同，会有问题。
