### ISSUE TITLE
下载了，打不开

### ISSUE THREAD

**Issue by CalmHeart** [pujiaxin33/JXPagingView#16]
弹出Failed to load project at '/Users/goopai/Downloads/JXPagingView-master/JXPagingView.xcodeproj', incompatible project version.

**Comment by pujiaxin33** [comment]
应该是你的xcode版本比较低，建议参考这篇文章试试呢
[https://www.jianshu.com/p/9949c9c3edc1](https://www.jianshu.com/p/9949c9c3edc1)
