### ISSUE TITLE
【JXPagerSmoothView】tab页的数据比较少是，pinHeader无法置顶

### ISSUE THREAD

**Issue by suqiang** [pujiaxin33/JXPagingView#161]
<img width="338" alt="WX20200109-103143@2x" src="https://user-images.githubusercontent.com/12711428/72032797-6efc4d80-32cb-11ea-8934-a345dafda2c4.png">

这个列表，tab页的数据比较少是，pinHeader无法置顶，请问有什么解决方案吗

**Comment by pujiaxin33** [comment]
你用最新的版本试试，之前就已经修复过了。

**Comment by 17554265585** [comment]
好像没有修复，我是今天刚下载测试的

**Comment by pujiaxin33** [comment]
你的手机系统是多少？

**Comment by 17554265585** [comment]
> 你的手机系统是多少？

抱歉，看了下版本是1.2.3，但是安装2.0.0会报找不到包

**Comment by pujiaxin33** [comment]
你用最新的demo吗？最新的发布版本是2.0.1

**Comment by pujiaxin33** [comment]
找不到最新包要pod repo update 一下
