### ISSUE TITLE
scrollviewdidscroll重复调用

### ISSUE THREAD

**Issue by greatmm** [pujiaxin33/JXPagingView#162]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
tabbar有三个item，第一个item使用JXPagerView添加了三个collectionview
当切换其它item时如果collecionview正在滚动，再返回第一个item时会一直调用setContentInset，直到崩溃

**版本号**
1.JXPagingView版本号：最新版？
2.OC还是Swift版本：oc？
3.手机系统版本号：10.3，13.3？
4.手机型号：iphone5，iphonex，iphonexr？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
JXPagingView什么版本

**Comment by greatmm** [comment]
- JXCategoryView (1.5.2)
  - JXPagingView/Pager (1.2.2)

**Comment by pujiaxin33** [comment]
我在oc版本demo写了【tabbar示例】并没有复现，你可以将你的版本升级到2.0.1版本看看还会不会复现。
如果还复现你可以把我的demo示例修改到能复现，然后发给我，我好查找原因。
