### ISSUE TITLE
JXPagingView/Pager (1.2.3)  刷新header高度问题

### ISSUE THREAD

**Issue by iostang** [pujiaxin33/JXPagingView#163]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。
OC版本调用JXPagerView的resizeTableHeaderViewHeightWithAnimatable方法会crash

**版本号**
1.JXPagingView版本号：1.2.3
2.OC还是Swift版本：OC
3.手机系统版本号：与系统版本无关
4.手机型号：与手机型号无关

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagerView
2.具体的操作步骤是：调用resizeTableHeaderViewHeightWithAnimatable方法会crash 原因是方法声明和实现不一致

**JXPagerView.h**
```
- (void)resizeTableHeaderViewHeightWithAnimatable:(BOOL)animatable duration:(NSTimeInterval)duration curve:(UIViewAnimationCurve)curve
```
**JXPagerView.m**
```
- (void)resizeTableHeaderViewHeightWithAnimatable:(BOOL)animatable duration:(NSTimeInterval)duration options:(UIViewAnimationOptions)options 
```

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
升级到2.0.0即可，再注意一下2.0.0迁移指南

**Comment by iostang** [comment]
你好 想问下 我怎么手动切换页面  我没有使用JXCategoryView
用的是segmentControl 点击item时需要切换页面 
1.2.3版本时 设置scrollView的contentOffset就可以 2.0.0就不行了

**Comment by pujiaxin33** [comment]
`JXPagerListContainerView`新增了`- (void)didClickSelectedItemAtIndex:(NSInteger)index;`，就是点击选中某个item。

**Comment by 17554265585** [comment]
为什么我下载的始终都是1.2.3，并且指定2.0.0说找不到

**Comment by pujiaxin33** [comment]
@17554265585 `pod repo update`把本地索引库更新之后，就有最新版本了。
