### ISSUE TITLE
系统版本号：12.4 JXSmoonthView 首次置顶，再滑动到其他tab,位置错误

### ISSUE THREAD

**Issue by suqiang** [pujiaxin33/JXPagingView#164]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
滚动延续（PageHeader列表）当系统是13.3时表现正常，系统为12.4时，表现异常。
首次进入，拖动第一个列表，让pinHeader置顶，测试点击或者滑动到第个列表，跳动后，位置错误

**版本号**
1.JXPagingView版本号：最新
2.OC还是Swift版本：OC
3.手机系统版本号：12.4
4.手机型号：模拟器

**复现步骤**
1. 遇到问题的相关效果、类是：SmoothCustomPagerHeaderViewController
2.具体的操作步骤是：
首次进入，拖动第一个列表，让pinHeader置顶，测试点击或者滑动到第个列表，跳动后，位置错误

**截图、GIF**
提供bug出现时的截图或者GIF。

![bugg](https://user-images.githubusercontent.com/12711428/72201688-b8969500-3491-11ea-91a3-46dabdecc46c.gif)

**Comment by pujiaxin33** [comment]
JXPagerView哪个版本?

**Comment by pujiaxin33** [comment]
最新demo已经修复，麻烦你再验证一下。
