### ISSUE TITLE
JXSmoothView无tab数据时，header仍需要显示和滚动

### ISSUE THREAD

**Issue by suqiang** [pujiaxin33/JXPagingView#166]
**Feature描述**
当前如果JXSmoothView中，tab无数据时，底部支撑上下滑动的scrollview就不存在，顶部headerview就无法显示和滚动

JXSmoothView无tab数据时，header仍需要显示和滚动

**其他补充**
实际业务场景时，tab相关的内容是根据数据来展示，可能存在需要不显示的情况，当前实现无法满足，希望恐惧能支持

**Comment by kashjack** [comment]
确实如此，之前1.0.0版本可以用，升级之后，出问题了

**Comment by pujiaxin33** [comment]
JXSmoothView的header是会寄生在滚动列表里面的，你没有tab就没有列表，所以就无法正常显示。建议你无tab时，使用一个空白字符给titles，假装有一个列表，然后返回一个特殊的列表vc，里面只有一个空白的UITableView，好让内部相关机制生效。

**Comment by suqiang** [comment]
个人建议，可以这么改造：
JXSmoothView 的headerview，一般在使用的时候也是UITableview
当JXSmoothView 通过代理，检测到没有tab数据时，直接把headerview贴到JXSmoothView上

**Comment by pujiaxin33** [comment]
JXSmoothView本身没有上下滚动的scrollView，只有左右滚动的列表容器视图。不想因为没有tab加入过多的逻辑。而且没有tab的情况，本来就不太适合JXSmoothView

**Comment by suqiang** [comment]
不是没有tab，是整个列表数据驱动的。
如果接口没返回tab的数据，下面也没返回的左右滚动页的数据，但只返回来头部数据。
无数据时，tab相关的都需要展示。
测试，使用者要自己兼容，建议能从框架层面支持

**Comment by pujiaxin33** [comment]
说是这么说，逻辑就是这么一步步复杂起来了。
要不你提个PR？

**Comment by suqiang** [comment]
我也还没有修复这个问题，滑动置顶那边也还有点问题，我晚点再和你聊，年底越忙了

**Comment by pujiaxin33** [comment]
最新demo仓库已经兼容了只有header没有tab的情况，有空可以测试一下，没有问题，我再发新包。

**Comment by HT204370534** [comment]
这个问题解决了吗
