### ISSUE TITLE
单独使用JXPagingView出现问题

### ISSUE THREAD

**Issue by kashjack** [pujiaxin33/JXPagingView#168]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：2.0.0
2.OC还是Swift版本：Swift
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：只使用JXPagingView的话，滑动不能触发listAppear等方法，故不可以加载出来页面，查看源码发现滑动触发segmentview的KVO才可以。这样不能满足单独使用JXPagingView啊
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
调用`JXPagingListContainerView`的`didClickSelectedItem(at index: Int)`方法即可

**Comment by kashjack** [comment]
调用该方法依然没反应。而且，滑动的时候除第一页外都是空白页，我尝试修改你的demo，只使用JXPagingView，不使用segmentview，也会出现这个问题。

**Comment by pujiaxin33** [comment]
需要在添加一个api，如下：
```Objective-C
[self.pagerView.listContainerView.scrollView setContentOffset:CGPointMake(0, 0) animated:YES];
[self.pagerView.listContainerView didClickSelectedItemAtIndex:0];
```

我在oc版本的demo添加了【自定义categoryView】示例，具体你看一下代码。

**Comment by Joecao123** [comment]
@pujiaxin33 请问使用自定义categoryView后，左右滑动能否自动触发Page的加载，还是说必须通过手动调用didClickSelectedItemAtIndex才能触发Page的加载？

**Comment by pujiaxin33** [comment]
@Joecao123 请参考demo示例。
