### ISSUE TITLE
请问怎样点击状态栏滚动到顶部

### ISSUE THREAD

**Issue by lxszl** [pujiaxin33/JXPagingView#17]
设置了currentScrollingListView的scrollsToTop，但是只有HeaderView可见时才能滚到到顶部，滑动范围超过HeaderView的高度接不能滚到顶部了。
谢谢。

**Comment by pujiaxin33** [comment]
基于JXPagingView的实现原理，UITableView，嵌入UICollectionView，嵌入UITableView，不推荐使用scrollsToTop这个特性。

**Comment by lxszl** [comment]
> 基于JXPagingView的实现原理，UITableView，嵌入UICollectionView，嵌入UITableView，不推荐使用scrollsToTop这个特性。

好的😂
