### ISSUE TITLE
pinSectionHeaderVerticalOffset < heightForPinSectionHeaderInPagerView时 调用[self.pagerView reloadData] crash

### ISSUE THREAD

**Issue by keleyundou** [pujiaxin33/JXPagingView#170]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
当pinSectionHeaderVerticalOffset < heightForPinSectionHeaderInPagerView时 调用[self.pagerView reloadData] crash

**版本号**
1.JXPagingView版本号：2.0.1
2.OC还是Swift版本：oc
3.手机系统版本号：12.4.1
4.手机型号：7s

**复现步骤**
1. 遇到问题的相关效果、类是：`ReloadWithoutInitListViewController`
2.具体的操作步骤是：

前提条件：
`pinSectionHeaderVerticalOffset < heightForPinSectionHeaderInPagerView`

eg:

```
...
self.pagerView.pinSectionHeaderVerticalOffset = 64;
...

- (NSUInteger)heightForPinSectionHeaderInPagerView:(JXPagerView *)pagerView {
    return 80;
}

```

进入界面点击reload按钮后，将列表滑动到底部，再次点击此按钮

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by xingze0308** [comment]
我设置了 pinSectionHeaderVerticalOffset  偶crash

**Comment by xingze0308** [comment]
又仔细阅读了demo中的例子 发现加上如下代码不crash    
    [self.pagerView.listContainerView.scrollView.panGestureRecognizer requireGestureRecognizerToFail:self.navigationController.interactivePopGestureRecognizer];
    [self.pagerView.mainTableView.panGestureRecognizer requireGestureRecognizerToFail:self.navigationController.interactivePopGestureRecognizer];

如果没加的话会在viewwilldisapper中crash 我在viewwillapper中隐藏导航栏 viewwilldisapper中设置了显示导航栏
加上以上代码没有crash

**Comment by pujiaxin33** [comment]
@xingze0308 能否把crash日志截图发送一下呢?
