### ISSUE TITLE
ios8-运行demo出现数据显示不完

### ISSUE THREAD

**Issue by leeaken** [pujiaxin33/JXPagingView#171]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

![21579230322_ pic](https://user-images.githubusercontent.com/8663400/72581141-49012980-3919-11ea-9396-0f488d716b3c.jpg)

![31579231901_ pic](https://user-images.githubusercontent.com/8663400/72582210-ffb2d900-391c-11ea-9b9a-b3313ebe2bd8.jpg)

**Comment by pujiaxin33** [comment]
没有ios8的手机和系统，你可以选择用JXPagerView替代JXPagerSmoothView吗?
