### ISSUE TITLE
pinSectionHeaderVerticalOffset > 0，mainTableView使用MJ下拉刷新时，再刷新过程中上滑，mainTableView的contentInset设置成了.zero

### ISSUE THREAD

**Issue by werner0423** [pujiaxin33/JXPagingView#172]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
pinSectionHeaderVerticalOffset > 0，mainTableView使用MJ下拉刷新时，再刷新过程中上滑，mainTableView的contentInset设置成了.zero，这个时候再下拉tableView会出现无法下拉

通过阅读源码发现JXPagingView的scrollViewDidScroll方法中，在scrollView.contentOffset.y < 0时直接调用了adjustMainScrollViewToTargetContentInsetIfNeeded(inset: UIEdgeInsets.zero)

**版本号**
1.JXPagingView版本号：2.0.1
2.OC还是Swift版本：swift

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
刚刚修复了，你下载最新demo再试试呢？

**Comment by werner0423** [comment]
> 刚刚修复了，你下载最新demo再试试呢？

上滑没有问题了，但是现在会在2~3后自动endRefresh

**Comment by pujiaxin33** [comment]
因MJRefresh在下拉刷新成功之后，会更新contentInset

**Comment by werner0423** [comment]
> 因MJRefresh在下拉刷新成功之后，会更新contentInset

但是我没有调用endRefreshing。 现在的情况是 当第一次我开始刷新的时候，不结束刷新，mj_header会一直显示，这是正确的。但是当我上滑之后，再回到顶部，这个时候mj_header依然显示，这样是正确的。但是停留2~3s之后mj_header就消失了，tableView的contentOffset变成.zero了。

        pagingView.mainTableView.mj_header = MJRefreshNormalHeader(refreshingBlock: {
        })
你可以这样试一下，给mainTableView的mj_header赋值，但不进行任何操作，然后上滑，然后再回到顶部，你就能复现出来

**Comment by werner0423** [comment]
> 因MJRefresh在下拉刷新成功之后，会更新contentInset

    public func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        if isListHorizontalScrollEnabled {
            listContainerView.scrollView.isScrollEnabled = true
        }
        if mainTableView.contentInset.top != 0 && pinSectionHeaderVerticalOffset != 0 {
            adjustMainScrollViewToTargetContentInsetIfNeeded(inset: UIEdgeInsets.zero)
        }
    }

我看了代码   是这块儿重新设置了inset导致的

**Comment by pujiaxin33** [comment]
你用最新demo在看看呢？

**Comment by werner0423** [comment]
> 你用最新demo在看看呢？

没好

**Comment by pujiaxin33** [comment]
因MJRefresh在下拉刷新成功之后，会更新contentInset。 然后下拉刷新结束之后，本身就会重置一下页面。请问现在还有什么问题呢？
