### ISSUE TITLE
请问怎样隐藏滚动条呢

### ISSUE THREAD

**Issue by 17554265585** [pujiaxin33/JXPagingView#174]
![image](https://user-images.githubusercontent.com/57781441/73738363-5292ea00-477f-11ea-9d0b-9de7cf7bcde3.png)
如图，在切换tab的时候滚动条显示不正确

**Comment by PZXforXcode** [comment]
我发现加了这句代码就无法隐藏滚动条了，!self.scrollCallback ?: self.scrollCallback(scrollView);

**Comment by PZXforXcode** [comment]
automaticallyDisplayListVerticalScrollIndicator设置为NO 就可以啦

**Comment by Liyongcong** [comment]
> automaticallyDisplayListVerticalScrollIndicator设置为NO 就可以啦

设置这个属性无效
