### ISSUE TITLE
在列表下拉刷新中设置了pinSectionHeaderVerticalOffset 偏移量的问题

### ISSUE THREAD

**Issue by gitchenyuke** [pujiaxin33/JXPagingView#177]
OC版本
在列表下拉刷新中设置了pinSectionHeaderVerticalOffset 偏移量后 mainTableView 仍然会有弹簧效果，不设置pinSectionHeaderVerticalOffset就不会出现，可以解决一下吗？

**Comment by pujiaxin33** [comment]
我在最新demo优化了。你clone下来，试试，看看解决了问题没？

**Comment by obj-dayao** [comment]
swift版本一样会有这个问题 这个帮忙改一下吧。。。

**Comment by pujiaxin33** [comment]
@obj-dayao 你用2.0.5版本试试呢

**Comment by obj-dayao** [comment]
2.0.5swfit 版本一样有这个问题啊 我加你QQ了 给你发下你看看

**Comment by pujiaxin33** [comment]
@obj-dayao 你用oc版本试试呢

**Comment by obj-dayao** [comment]
oc 版本确实没问题，但是swfit版本不行

**Comment by pujiaxin33** [comment]
swift代码没有完全同步，demo已经修复了。

**Comment by obj-dayao** [comment]
好，我下载试试
