### ISSUE TITLE
缓存

### ISSUE THREAD

**Issue by FaDeve** [pujiaxin33/JXPagingView#18]
有五个item,直接点击第五个,会看到中间的界面,如果有很多个item,会不会很占用内存

**Comment by pujiaxin33** [comment]
1、如果你不想要点击之后，会看到中间的页面。可以直接切换过去，没有中间动画，参考下面：
你可以实现下面的代理方法进行自定义：
```
- (void)categoryView:(JXCategoryBaseView *)categoryView contentScrollViewTransitionToIndex:(NSInteger)index
```
具体可以看里面的API注解
2、关于内存问题
参考这个[关于视图全部加载问题 ](https://github.com/pujiaxin33/JXCategoryView/issues/25)

**Comment by FaDeve** [comment]
动画省略之后,实际上如果加载完了10个item,应该还是常驻内存的吧?


原始邮件
发件人:暴走的鑫鑫notifications@github.com
收件人:pujiaxin33/JXPagingViewJXPagingView@noreply.github.com
抄送:FaDeve2404445663@qq.com; Authorauthor@noreply.github.com
发送时间:2018年11月9日(周五) 10:10
主题:Re: [pujiaxin33/JXPagingView] 缓存 (#18)


1、如果你不想要点击之后，会看到中间的页面。可以直接切换过去，没有中间动画，参考下面：
 你可以实现下面的代理方法进行自定义：
- (void)categoryView:(JXCategoryBaseView *)categoryView contentScrollViewTransitionToIndex:(NSInteger)index
具体可以看里面的API注解
 2、关于内存问题
 参考这个关于视图全部加载问题

**Comment by pujiaxin33** [comment]
是的，中间的item，虽然初始化了，但是没有加载数据，内存消耗不大

**Comment by FaDeve** [comment]
普通应用还好,如果视频类的,几十个item,且每个页面都比较复杂的,这个时候就要考虑一下内存的优化


原始邮件
发件人:暴走的鑫鑫notifications@github.com
收件人:pujiaxin33/JXPagingViewJXPagingView@noreply.github.com
抄送:FaDeve2404445663@qq.com; Authorauthor@noreply.github.com
发送时间:2018年11月9日(周五) 15:09
主题:Re: [pujiaxin33/JXPagingView] 缓存 (#18)


是的，中间的item，虽然初始化了，但是没有加载数据，内存消耗不大

**Comment by pujiaxin33** [comment]
感谢你的反馈，1.0.0版本实现了列表懒加载。等到列表显示的时候，才会真正初始化。欢迎使用最新版本体验！！！
