### ISSUE TITLE
iOS10的崩溃问题

### ISSUE THREAD

**Issue by linzhesheng** [pujiaxin33/JXPagingView#181]
iOS10 如果 - (NSUInteger)tableHeaderViewHeightInPagerView:(JXPagerView *)pagerView 和 pinSectionHeaderVerticalOffset 一样，JXPagerView 内部会反复调用 - (void)scrollViewDidScroll:(UIScrollView *)scrollView 而崩溃

**Comment by pujiaxin33** [comment]
崩溃堆栈截图发一下呢？

**Comment by pujiaxin33** [comment]
我身边没有iOS10的手机和模拟器，高系统没有复现。

**Comment by pujiaxin33** [comment]
我用ios10.3.1的模拟器依然没有复现。
