### ISSUE TITLE
JXPagerSmoothView与JXCategoryTitleView配合使用,点击JXCategoryTitleView时底部的列表切换时没有动画

### ISSUE THREAD

**Issue by xiaogehenjimo** [pujiaxin33/JXPagingView#183]
**Feature描述**
能否实现类似 JXCategoryListContainerView  中 didClickSelectedItemAtIndex 这种类似的接口供外界调用实现底部的滚动效果?

**Comment by pujiaxin33** [comment]
因为JXPagerSmoothView的特殊性无法实现左右滚动切换效果。
