### ISSUE TITLE
iOS12正常；iOS13异常，如果睡眠2秒即sleep(2)后，再去执行刷新操作，页面数据则正常显示。

### ISSUE THREAD

**Issue by HaoHaoChina** [pujiaxin33/JXPagingView#184]
控制器中代码逻辑是：
1，先添加视图 
2，再去请求数据 
3，在数据请求完成回调中给页面控件赋值，或者刷新操作（代码如下）

//            sleep(2)
                self.dataSource.titles = self.titles
                self.dataSource.reloadData(selectedIndex: 0)
                self.segmentedView.defaultSelectedIndex = 0
                self.segmentedView.reloadData()
                self.pagingView.reloadData()

问题描述：iOS12页面显示正常；iOS13页面显示异常如下图，如果睡眠2秒即增加sleep(2)这行代码，页面显示正常。
![Simulator Screen Shot - iPhone 8 Plus - 2020-02-20 at 14 53 01](https://user-images.githubusercontent.com/26422887/75315062-9370b100-589c-11ea-99d3-34c4a0811db1.png)

**Comment by pujiaxin33** [comment]
1、不要用sleep，你其实要模拟网络请求回来之后刷新数据。自己异步延迟到主线程刷新。你sleep之后，后面的流程都不会走了。
2、你说的界面异常，麻烦标注说明一下，我光看图片，不明白。

**Comment by HaoHaoChina** [comment]
<img width="965" alt="iOS12" src="https://user-images.githubusercontent.com/26422887/76917545-b53ee000-68fe-11ea-9c88-24a050e08db8.png">



<img width="981" alt="iOS13" src="https://user-images.githubusercontent.com/26422887/76917591-df909d80-68fe-11ea-9a0e-cf5538aedd2c.png">

**Comment by HaoHaoChina** [comment]
在iOS12上页面正常显示；但是在iOS13上页面就会一直显示刷新加载控件，感觉像页面卡住了一样，在iOS13上如果加上sleep(2)这句代码就会正常。

**Comment by pujiaxin33** [comment]
能提供一下复现问题的demo吗？你可以把已有的仓库demo改造一下。

**Comment by HaoHaoChina** [comment]
已发送您QQ邮箱,请查收！主题是：demo + 问题复现截图

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/79089878-5f811a80-7d7a-11ea-8a66-d15be6635052.png)
你的headerView在ios13，有循环调用的问题，你自己解决哈。

**Comment by HaoHaoChina** [comment]
已解决，谢谢大神指点！🙂
