### ISSUE TITLE
设置pinSectionHeaderVerticalOffset问题

### ISSUE THREAD

**Issue by huangxianyu** [pujiaxin33/JXPagingView#187]
设置pinSectionHeaderVerticalOffset后, 只滑动tableHeaderView区域不流畅, 上下滑动没有惯性, 感觉比较卡顿

**Comment by huangxianyu** [comment]
现在需求是listContainerView就1个列表, 怎么才能listContainerView列表有多少内容就显示多高, 比如说下面列有两个cell, 就显示两个cell, 不显示cell下面多余的空白, sectionHeaderView不直接顶到最上面.  能不能实现?

**Comment by pujiaxin33** [comment]
> 设置pinSectionHeaderVerticalOffset后, 只滑动tableHeaderView区域不流畅, 上下滑动没有惯性, 感觉比较卡顿

这个问题我在最新demo优化了一下，你clone最新版本试试。我只在ios13测试没有问题。你自己多测试一下，看看符合要求不。

**Comment by pujiaxin33** [comment]
> 现在需求是listContainerView就1个列表, 怎么才能listContainerView列表有多少内容就显示多高, 比如说下面列有两个cell, 就显示两个cell, 不显示cell下面多余的空白, sectionHeaderView不直接顶到最上面. 能不能实现?

这个无法实现，底部列表区域大小必须要提前计算好的，固定高度，不能根据列表的内容高度来。

**Comment by huangxianyu** [comment]
多谢老铁

**Comment by huangxianyu** [comment]
优化后pinSectionHeaderVerticalOffset, 下拉到底, 在往上滑动, 整个界面会有跳动的问题

> > 设置pinSectionHeaderVerticalOffset后, 只滑动tableHeaderView区域不流畅, 上下滑动没有惯性, 感觉比较卡顿
> 
> 这个问题我在最新demo优化了一下，你clone最新版本试试。我只在ios13测试没有问题。你自己多测试一下，看看符合要求不。

优化后设置pinSectionHeaderVerticalOffset, 先下拉到底, 再往上滑, 整个界面会有跳动问题.

**Comment by huangxianyu** [comment]
JXPagerListRefreshView 设置pinSectionHeaderVerticalOffset后, 底部显示不全, 头大了..

**Comment by pujiaxin33** [comment]
> JXPagerListRefreshView 设置pinSectionHeaderVerticalOffset后, 底部显示不全, 头大了..

你发一个截图呢，我测试没有这个问题

**Comment by xytyes** [comment]
我也出现类似问题， 设置pinSectionHeaderVerticalOffset后，底部显示不全了， @huangxianyu  这个问题你解决了没？

**Comment by huangxianyu** [comment]
> > JXPagerListRefreshView 设置pinSectionHeaderVerticalOffset后, 底部显示不全, 头大了..
> 
> 你发一个截图呢，我测试没有这个问题

如果延后设置就会出现显示不全的问题
    dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        self.pagerView.pinSectionHeaderVerticalOffset = JXTableHeaderViewHeight;
    });

**Comment by huangxianyu** [comment]
> 我也出现类似问题， 设置pinSectionHeaderVerticalOffset后，底部显示不全了， @huangxianyu 这个问题你解决了没？

在创建时设置self.pagerView.pinSectionHeaderVerticalOffset = JXTableHeaderViewHeight;

**Comment by huangxianyu** [comment]
> > JXPagerListRefreshView 设置pinSectionHeaderVerticalOffset后, 底部显示不全, 头大了..
> 
> 你发一个截图呢，我测试没有这个问题

如果延后设置机会出现显示不全的问题, 创建后就设置不会出现, 但我要根据网络请求结果设置pinSectionHeaderVerticalOffset大小.

dispatch_after(dispatch_time(DISPATCH_TIME_NOW, (int64_t)(3 * NSEC_PER_SEC)), dispatch_get_main_queue(), ^{
        self.pagerView.pinSectionHeaderVerticalOffset = JXTableHeaderViewHeight;
    });

**Comment by pujiaxin33** [comment]
你有调用reloadData方法吗？

**Comment by huangxianyu** [comment]
> 你有调用reloadData方法吗？

需要调用reloadData方法啊, 我没调用, 不好意思了兄弟.
我试了试, 每次reloadData, 都会重新创建ListViewController.

**Comment by pujiaxin33** [comment]
你参考oc还是swift里面的一个示例，缓存列表视图，你自己在demo里面找一下

**Comment by zhangxiangguang** [comment]
> > 现在需求是listContainerView就1个列表，如何才能listContainerView列表有多少内容就显示多高，比如说下面列有两个cell，就显示两个cell，不显示cell下面多余的空白，sectionHeaderView不直接顶到最上面。能不能实现？
> 
> 这个无法实现，底部列表区域大小必须要提前计算好的，固定高度，不能根据列表的内容高度来。

---

### 通过runtime去hook方法

* `JXPagerView`的实例方法：`@selector(tableView:heightForRowAtIndexPath:)` ，返回自己需要的高度；

* `JXPagerListContainerView`的实例方法：`collectionView:cellForItemAtIndexPath:`，设置listView的显示layout。

**Comment by huangxianyu** [comment]
> 你参考oc还是swift里面的一个示例，缓存列表视图，你自己在demo里面找一下

找到了, 多谢老铁及时回复.

**Comment by huangxianyu** [comment]
> > > 现在需求是listContainerView就1个列表，如何才能listContainerView列表有多少内容就显示多高，比如说下面列有两个cell，就显示两个cell，不显示cell下面多余的空白，sectionHeaderView不直接顶到最上面。能不能实现？
> > 
> > 
> > 这个无法实现，底部列表区域大小必须要提前计算好的，固定高度，不能根据列表的内容高度来。
> 
> ### 通过runtime去hook方法
> * `JXPagerView`的实例方法：`@selector(tableView:heightForRowAtIndexPath:)` ，返回自己需要的高度；
> * `JXPagerListContainerView`的实例方法：`collectionView:cellForItemAtIndexPath:`，设置listView的显示layout。

多谢, 提供思路方法.
