### ISSUE TITLE
User pager 模式只显示第一个view, 后面的不显示

### ISSUE THREAD

**Issue by AndyFightting** [pujiaxin33/JXPagingView#189]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
User pager 模式只显示第一个view, 后面的不显示

1.下载使用demo里的 JXPagingView-Swift 模块可以正常显示，关键代码如下
segmentedView.contentScrollView = pagingView.listContainerView.collectionView

2.使用pod 安装 pod 'JXPagingView/Paging'
segmentedView.contentScrollView = pagingView.listContainerView.scrollView , 和Demo不一样

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？ Swift 
3.手机系统版本号：？ 13.2
4.手机型号：？iphoneX

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
只会显示目录那第一个View, 后面的简介和评论添加的view都显示不出来，弄了半天没弄出来，使用demo里的 JXPagingView-Swift 模块而不通过pod安装才好了..

![Simulator Screen Shot - iPhone 11 - 2020-03-09 at 16 16 59](https://user-images.githubusercontent.com/12689782/76194732-c19dab80-6221-11ea-9d3a-e2cb2c5d79a2.png)

**Comment by pujiaxin33** [comment]
这是最新版本的关联方法
```swift
segmentedView.listContainer = pagingView.listContainerView
```

**Comment by AndyFightting** [comment]
<img width="684" alt="截屏2020-03-12下午5 17 57" src="https://user-images.githubusercontent.com/12689782/76505983-59e79a80-6485-11ea-9b0e-697da7872944.png">

**Comment by tanjieaa** [comment]
> 这是最新版本的关联方法
> 
> ```swift
> segmentedView.listContainer = pagingView.listContainerView
> ```

也遇到这个问题，第一个view显示，选择后面的不显示，离开再次点击才会显示，是使用最新的关联方法

**Comment by butcheryl** [comment]
```
public func scrolling(from leftIndex: Int, to rightIndex: Int, percent: CGFloat, selectedIndex: Int)
```

上面的方法是 能否显示后续界面的关键，查看源码发现这个方法一次都没有被调用过。只有在使用`JXSegmentedView`这个库的时候，才被调用

**Comment by LeeJoey77** [comment]
ReadMe 中有回答这个问题，需要添加一句代码
` extension JXPagingListContainerView: JXSegmentedViewListContainer{}
`

**Comment by pujiaxin33** [comment]
@LeeJoey77 感谢你的补充，若还有问题，请参考升级指南。
