### ISSUE TITLE
一个请教问题

### ISSUE THREAD

**Issue by simpleLiYu** [pujiaxin33/JXPagingView#190]
### **首先感谢作者提供如此强大的库，十分感谢**
![image](https://user-images.githubusercontent.com/20043672/76318400-9b0e6c00-6318-11ea-8d51-2cb39a534006.png)
这种情况下我想实现的是下拉刷新是让下方对应的控制器进行刷新数据的操作，可是我如何才能获取到下方的三个控制器呢？

**Comment by pujiaxin33** [comment]
你可以自己记录已经生成的列表，然后调用列表刷新方法：
```Objective-c
- (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index {
    ListViewController *listView = [[ListViewController alloc] init];
//伪代码，然后就可以用self.listView进行后续操作了。
self.listView = listView;
    return listView;
}
```

**Comment by simpleLiYu** [comment]
好的，懂了，给他们全部记录起来对吧，感谢
