### ISSUE TITLE
JXCategoryTitleView能否向上滑动

### ISSUE THREAD

**Issue by huangping35** [pujiaxin33/JXPagingView#191]
大佬，现在项目的首页，类似京东首页，点击JXCategoryTitleView的首页，需要自定义的JXCategoryTitleView也一起向上滑动，这个需要调用什么委托实现，还是怎么实现？
我现在的做法是 CGRect frame=self.pagerView.mainTableView.frame; frame.origin.y=-(50) self.pagerView.mainTableView.frame=frame; self.pagerView是JXPagerView。

**Comment by pujiaxin33** [comment]
这些就只有你自己调整控件frame了，JXCategoryTitleView和JXPagerView，对于该效果是无法内部支持的。

**Comment by tanbinzone** [comment]
> 这些就只有你自己调整控件frame了，JXCategoryTitleView和JXPagerView，对于该效果是无法内部支持的。
这种效果很多app还要需要的，不需要悬停的title

**Comment by onceMu** [comment]
悬停的header 内部可以滚动？类似 网易云音乐电台个人页。

**Comment by pujiaxin33** [comment]
demo新增了一个scrollUp示例，可以参考一下这块代码。
