### ISSUE TITLE
1、Demo中NestViewController.swift中不设置indicators,titleSelectedColor无效。2、indicators设置为JXSegmentedIndicatorLineView，第一个title不显示。详情可看图

### ISSUE THREAD

**Issue by amycliny** [pujiaxin33/JXPagingView#194]
1、Demo中不设置indicator，titleSelectedColor无效
![no indicator](https://user-images.githubusercontent.com/15085638/76682063-aec91380-6633-11ea-8bf3-c620f3396ac7.png)
![1](https://user-images.githubusercontent.com/15085638/76682074-cf916900-6633-11ea-827a-344f41a41db6.png)
2、还是这个NestViewController.swift，如果设置indicators为JXSegmentedIndicatorLineView，第一个title不显示
![line indicator](https://user-images.githubusercontent.com/15085638/76682133-652cf880-6634-11ea-83b1-c2d9412a8950.png)
![2](https://user-images.githubusercontent.com/15085638/76682144-7d9d1300-6634-11ea-981a-7b07ecc3da1f.png)
3、还有就是想请教下swif版本可以实现像爱奇艺会员页这种效果吗？下拉刷新的时候，两个tab是贴着的，demo设置header高度为0后是有空隙的
<img width="357" alt="1" src="https://user-images.githubusercontent.com/15085638/76979431-e2c57100-6972-11ea-9637-66462ae18f72.png">
<img width="363" alt="2" src="https://user-images.githubusercontent.com/15085638/76979652-31730b00-6973-11ea-8bc0-70215795b756.png">

**Comment by pujiaxin33** [comment]
1、Demo中NestViewController.swift中不设置indicators,titleSelectedColor无效。
这个问题，你需要把`naviDataSource.isTitleMaskEnabled = true`这句代码注释掉，因为开启了isTitleMaskEnabled，就需要依赖indicator。

**Comment by pujiaxin33** [comment]
2、indicators设置为JXSegmentedIndicatorLineView，第一个title不显示。
这个问题同理，把`naviDataSource.isTitleMaskEnabled = true`这句代码注释掉即可。

**Comment by pujiaxin33** [comment]
3、还有就是想请教下swif版本可以实现像爱奇艺会员页这种效果吗？下拉刷新的时候，两个tab是贴着的，demo设置header高度为0后是有空隙的

你看的示例是*categoryView嵌套pagingView*，你想要的效果是*categoryView嵌套categoryView*。这个示例在JXCategoryView库里面有，你自己找一找
