### ISSUE TITLE
上滑tableview列表后，有时点击cell不响应点击事件

### ISSUE THREAD

**Issue by wyk190576528** [pujiaxin33/JXPagingView#195]
滑动列表后，看着页面已经不再滑动了，此时点击cell不响应事件，需要再次点击一下才会响应事件

**Comment by pujiaxin33** [comment]
关于下方列表视图的代理方法- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath有时候需要点击两次才回调
出现步骤：当手指放在下方列表视图往下拉，直到TableHeaderView完全显示。

原因：经过上面的步骤之后，手指已经离开屏幕且列表视图已经完全静止，UIScrollView的isDragging属性却依然是true。就导致了后续的第一次点击，让系统认为当前UIScrollView依然在滚动，该点击就让UIScrollView停止下来，没有继续转发给UITableView，就没有转化成didSelectRow事件。

解决方案：经过N种尝试之后，还是没有回避掉系统的isDragging异常为true的bug。大家可以在自定义cell最下方放置一个与cell同大小的button，把button的touchUpInside事件当做didSelectRow的回调。因为UIButton在响应链中的优先级要高于UIGestureRecognizer。

代码：请参考TestTableViewCell类的配置。

**Comment by pujiaxin33** [comment]
或者你使用JXPagerSmoothView，可以规避这个问题
