### ISSUE TITLE
升级到2.0.0版本，右滑返回出问题

### ISSUE THREAD

**Issue by wyk190576528** [pujiaxin33/JXPagingView#198]
升级前，只支持侧边右滑返回，升级后，可以全屏右滑返回了，怎么控制这个？

**Comment by wyk190576528** [comment]
设置self.navigationController.interactivePopGestureRecognizer.enabled，无效

**Comment by pujiaxin33** [comment]
我不晓得什么问题。

**Comment by pujiaxin33** [comment]
可以全屏右滑返回，是不是你项目引入了什么库
