### ISSUE TITLE
如何在各子列表界面底部添加按钮，并固定在屏幕底部，有方法吗

### ISSUE THREAD

**Issue by gouqituzi0117** [pujiaxin33/JXPagingView#199]
**Feature描述**
如何在各子列表界面底部添加按钮，并固定在屏幕底部，有方法吗

**Comment by pujiaxin33** [comment]
你只能在最外层里面添加按钮，固定到底部。列表是会随着上下滚动而移动的，所以无法在列表上面添加按钮，并固定到屏幕底部。
