### ISSUE TITLE
下载下来不能运行

### ISSUE THREAD

**Issue by dongzejun** [pujiaxin33/JXPagingView#2]

**Comment by pujiaxin33** [comment]
你选择模拟器运行呢，亲测没有问题，不然你把问题的描述发一下呢

**Comment by dongzejun** [comment]
![20961534903137_ pic_hd](https://user-images.githubusercontent.com/15865668/44438565-3f737500-a5f2-11e8-8abd-1b1b0962e0b9.jpg)
还没到选择模拟器那一步,下载下来后就没能打开
我XCode 版本 Version 9.2

**Comment by pujiaxin33** [comment]
尝试下这个解决方案呢？ https://stackoverflow.com/questions/49622341/failed-to-load-project-incompatible-project-version-pop-up-appears-when-i-op
