### ISSUE TITLE
有参数可以设置某一个listView能下拉刷新吗?

### ISSUE THREAD

**Issue by Ycong** [pujiaxin33/JXPagingView#20]

**Comment by zhangqi02060227m** [comment]
只给要刷新的vc中的scrollView 添加 mj_header 就行了。意思就是需要刷新头的加，不需要刷新的vc不加，就可以实现了。。。

**Comment by pujiaxin33** [comment]
@zhangqi02060227m very good！列表里面的scrollView本身就是你自己控制的，控制一个listView的下拉刷新不是分分钟的事情吗？

**Comment by Ycong** [comment]
**1.使用JXPagingView时下拉头部会跟着滚动.**
![ezgif-2-9d495652136d](https://user-images.githubusercontent.com/10216202/48252104-c2aca600-e43e-11e8-80ed-254b076ae253.gif)

**2.使用JXPagingListRefreshView但listView没有添加mj_header,头部不会跟着滚动.**
![ezgif-2-a22528bd0952](https://user-images.githubusercontent.com/10216202/48252222-1f0fc580-e43f-11e8-9859-39ebce77c79f.gif)


**我的意思是当使用JXPagingListRefreshView但listView没有添加mj_header时,头部能不能也跟着滚动?**

**Comment by pujiaxin33** [comment]
JXPagingListRefreshView本来就不支持头部跟着滚动哈

**Comment by Ycong** [comment]
试着改了一下,应该可以用.
![ezgif-2-3dbff1379a1c](https://user-images.githubusercontent.com/10216202/48254059-d9a1c700-e443-11e8-8556-3fd344e13ae6.gif)
