### ISSUE TITLE
pinSectionHeaderVerticalOffset问题

### ISSUE THREAD

**Issue by tanbinzone** [pujiaxin33/JXPagingView#200]
demo中HeaderPositionViewController设置self.pagerView.pinSectionHeaderVerticalOffset = -50;

上拉到tableview最底部，header先隐藏，后面会闪现显示出来 

版本：2.0.1

**Comment by pujiaxin33** [comment]
pinSectionHeaderVerticalOffset不要设置为负数，pinSectionHeaderVerticalOffset的初衷是为了下沉而添加了，不是上浮隐藏。

**Comment by simpleLiYu** [comment]
> pinSectionHeaderVerticalOffset不要设置为负数，pinSectionHeaderVerticalOffset的初衷是为了下沉而添加了，不是上浮隐藏。

作者你好，麻烦问下JXPagingSmoothView可以监听页面的滑动吗

**Comment by pujiaxin33** [comment]
@simpleLiYu JXPagingSmoothView的上下滑动就是你列表的本身的滑动，其次就是左右滑动，你说的哪一个？

**Comment by simpleLiYu** [comment]
> @simpleLiYu JXPagingSmoothView的上下滑动就是你列表的本身的滑动，其次就是左右滑动，你说的哪一个？

恩，我想监听一下竖直的滑动
<img width="627" alt="QQ20200409-155846@2x" src="https://user-images.githubusercontent.com/20043672/78871943-0f087500-7a7b-11ea-8841-4a3006c6f9c2.png">

**Comment by FlyingNoob** [comment]
pinSectionHeaderVerticalOffset 设置之后添加了下拉刷新 多次下拉 会抖动。滚动到顶部

**Comment by FlyingNoob** [comment]
@pujiaxin33

**Comment by pujiaxin33** [comment]
@simpleLiYu SmoothListViewController就是你自己列表类，自己列表类的scrollView滚动，你通过代码监听就行了。

**Comment by simpleLiYu** [comment]
> pinSectionHeaderVerticalOffset 设置之后添加了下拉刷新 多次下拉 会抖动。滚动到顶部

你的意思是不是下面的列表随便拖一下就直接滑到顶部这样

**Comment by pujiaxin33** [comment]
> > pinSectionHeaderVerticalOffset 设置之后添加了下拉刷新 多次下拉 会抖动。滚动到顶部
> 
> 你的意思是不是下面的列表随便拖一下就直接滑到顶部这样

这个问题已经修复了： https://github.com/pujiaxin33/JXPagingView/issues/203

**Comment by Katherine923** [comment]
pinSectionHeaderVerticalOffset 为0 设置了下拉刷新 上推不是平滑的悬浮 有解决的办法吗 
把minContentOffsetYInListScrollView的返回值设置为header的高度就正常，有其他的办法吗
