### ISSUE TITLE
adjustMainScrollViewToTargetContentInsetIfNeeded  EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by simpleLiYu** [pujiaxin33/JXPagingView#201]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号 2.0.1
2.OC还是Swift版本：Swift
3.手机系统版本号： 模拟器 Xs Max 12.2

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagingView.swift 
2.具体的操作步骤是：点击跳转到新控制器

**截图、GIF**
![image](https://user-images.githubusercontent.com/20043672/78764030-8a552280-79b8-11ea-89e2-1559d2be76a5.png)

**Comment by pujiaxin33** [comment]
我用ios12.4的iPhone7模拟器测试，没有复现你说的问题。你能否用ios13的系统复现呢

**Comment by simpleLiYu** [comment]
> 我用ios12.4的iPhone7模拟器测试，没有复现你说的问题。你能否用ios13的系统复现呢
换了模拟器测试又好了，目前只在Xs Max 12.2出现这个问题，先关闭等回头有时间的话再来解决

**Comment by RobotAmiee** [comment]
最近线上 App 也遇到类似的问题，目前定位到原因了，我这边的情况是：在 Feed 流列表界面，在用户在开启热点或打电话时在 App 查看大图后，最开始触发了 `JXPagerView.m` 的 `layoutSubviews` 方法，然后触发了 `scrollViewDidScroll`方法，然后进入 `setMainTableViewToMaxContentOffsetY` 方法调用 `self.mainTableView.contentOffset` 后又会触发 `scrollViewDidScroll` 方法，最后这样互相调用进入死循环，最终崩溃，触发原因目前不明。我目前这样改了下：

```
- (void)adjustMainScrollViewToTargetContentInsetIfNeeded:(UIEdgeInsets)insets {
    if (UIEdgeInsetsEqualToEdgeInsets(insets, self.mainTableView.contentInset) == NO) {
        self.mainTableView.delegate = nil;
        self.mainTableView.contentInset = insets;
        self.mainTableView.delegate = self;
    }
}
```

用来解决死循环。看能不能给作者提供下思路，这块是否有死循环的风险，该怎样规避解决。

**Comment by pujiaxin33** [comment]
@RobotAmiee 感谢你的反馈，确实按照你说的路径可以复现。已经采用你的方案，修改了代码。

**Comment by bk97531** [comment]
这样简单粗暴的处理后续可能埋坑,建议在scrollViewDidScroll中加判断处理
