### ISSUE TITLE
iOS 13系统在 滚动延续列表，上滑能力，爱好，队友那一栏之后 点击状态栏无法回到顶部，iOS11可以

### ISSUE THREAD

**Issue by hanjianfei** [pujiaxin33/JXPagingView#202]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
我用ios13.1的模拟器测试，木有问题呢？
能再详细描述一下复现步骤吗？

**Comment by hanjianfei** [comment]
是滚动延续（pagerHeader列表）这一个

**Comment by pujiaxin33** [comment]
加在这句就行：
`self.pagerHeader.scrollsToTop = NO;`

**Comment by hanjianfei** [comment]
> 加在这句就行：
> `self.pagerHeader.scrollsToTop = NO;`

好了
