### ISSUE TITLE
导航隐藏 设置pinSectionHeaderVerticalOffset  添加下拉刷新 滑动 产生抖动 不能再次下拉

### ISSUE THREAD

**Issue by FlyingNoob** [pujiaxin33/JXPagingView#203]
**bug描述**
类似demo中 导航隐藏应用场景。 设置pinSectionHeaderVerticalOffset  添加顶部下拉刷新，多次下拉抖动

**版本号**
1.JXPagingView版本号：最新版
复现：
最新 demo 中导航隐藏 里面 添加头部下拉刷新。多次下拉就会复现

**Comment by pujiaxin33** [comment]
因为MJRefresh通过设置contentInset来显示下拉刷新视图，然后呢，JXPaingView通过设置contentInset来实现pinSectionHeaderVerticalOffset的效果。出现抖动的就是JXPaingView把contentInset.top设置0，MJRefresh在freshing状态，又会把contentInset.top设置为54。所以，两个来回设置，就出现了抖动。

至于解决方案的话，容我想想。

**Comment by pujiaxin33** [comment]
最新仓库代码已经修复了，你试一试。但是必须保证pinSectionHeaderVerticalOffset和MJRefresh的mj_insetT不一样就行。

**Comment by FlyingNoob** [comment]
@pujiaxin33 可以了，谢谢

**Comment by weizhangCoder** [comment]
> @pujiaxin33 可以了，谢谢

我怎么尝试demo 里面的TabBar 示例，在下拉刷新的时候，再次刷新依然还会抖动，要设置什么吗？
