### ISSUE TITLE
bug：mj_header.beginRefreshing()无下拉动画

### ISSUE THREAD

**Issue by JayLin0920** [pujiaxin33/JXPagingView#205]
**bug描述**
通过点击segment上的标签，触发mj_header.beginRefreshing()
- 有问题处：当segment处于第一个标签时，无下拉动画
- 无问题处：segment处于非第一个标签，有下拉动画

（该问题仅在，segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑，这种情况下，才无下拉动画） 

**版本号**
1.JXPagingView版本号：pod 'JXPagingView/Paging','2.0.1'，楼主最新代码Download下来也可以复现这个问题
2.OC还是Swift版本：Swift
3.手机系统版本号：iOS 13.4.1（Xcode11.4.1模拟器也有这个问题）
4.手机型号：iphone11

**复现步骤**
1、楼主的demo中加入如下代码
```
1、BaseViewController中，添加通知
func segmentedView(_ segmentedView: JXSegmentedView, didClickSelectedItemAt index: Int) {
        print("jl==   didClickSelectedItemAt")
        NotificationCenter.default.post(name: NSNotification.Name(rawValue: "NotificationCenter_didClickSelectedItemAt"), object: nil)
    }

2、ListViewController中，监听通知
NotificationCenter.default.addObserver(self, selector: #selector(ntf), name: NSNotification.Name(rawValue: "NotificationCenter_didClickSelectedItemAt"), object: nil)
@objc func ntf() {
        if isNeedHeader {
            print("jl== beginRefreshing")
            self.tableView.mj_header.beginRefreshing()
        }
    }
```
2、demo点击步骤
（1）启动app，点击进入‘列表下拉刷新’页面
（2）进入页面后，让页面稍微往上面滑动一点（让segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑）
（3）点击segment上的’能力‘，会触发 ’mj_header.beginRefreshing()‘，此时没有mj的自动下拉的动画效果（如果点击的是第二个标签’爱好‘，是有自动下拉的动画效果）

**截图、GIF**
楼主现有的demo，下载下来，修改下就可以复现

**Comment by pujiaxin33** [comment]
就我测试的情况来看，你把能力、爱好标签的数据，多添一些，超过一个屏幕。那么同样，点击也不会有下拉刷新控件的出现。

就从我设计的初衷，在（让segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑）这种情况是不允许有下拉刷新控件出现。

至于为什么数据量少的时候，点击触发下拉刷新可以出现，我也很迷。暂时找不到问题点，总感觉和MJRefresh关系很大。

**Comment by pujiaxin33** [comment]
内容少的时候，调用路径是这样的：
![image](https://user-images.githubusercontent.com/12654640/79546939-d47b8980-80c5-11ea-8e2d-0888cf854b49.png)

**Comment by pujiaxin33** [comment]
内容超过一个屏幕的时候，调用路径是这样的：
![image](https://user-images.githubusercontent.com/12654640/79547116-0ab90900-80c6-11ea-9b77-c7b41e34e20a.png)

**Comment by pujiaxin33** [comment]
我不负责任的猜想一下，内容过少，以至于无法滚动，那么方法`[self.scrollView setContentOffset:offset animated:NO];`的内部实现，与有足够多的内容可以引起滚动，两种情况，系统内部实现机制不一样。可能是这个导致的。

**Comment by pujiaxin33** [comment]
最后总结一下：
就从我设计的初衷，在（让segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑）这种情况是不允许有下拉刷新控件出现。
所以，不建议你去实现这样的效果。

第二，至于为什么数据少的时候，可以实现上面的效果，我也无法解释。你可以自行探究一下。

**Comment by JayLin0920** [comment]
> 我不负责任的猜想一下，内容过少，以至于无法滚动，那么方法`[self.scrollView setContentOffset:offset animated:NO];`的内部实现，与有足够多的内容可以引起滚动，两种情况，系统内部实现机制不一样。可能是这个导致的。

内容过少，只要把segment顶到最顶上，可以可以触发引起刷新动画的

**Comment by JayLin0920** [comment]
> 最后总结一下：
> 就从我设计的初衷，在（让segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑）这种情况是不允许有下拉刷新控件出现。
> 所以，不建议你去实现这样的效果。
> 
> 第二，至于为什么数据少的时候，可以实现上面的效果，我也无法解释。你可以自行探究一下。

像这种pagingview结合segment，重复点击上面segment会触发下拉刷新操作，这种效果还蛮常见的，如果没有这种下拉刷新动画，那就看不出来是刷新了😢

**Comment by JayLin0920** [comment]
还是很感谢楼主的查看🌹
我也在查查，看有没有解决办法。
楼主也可以关注下，感觉’双击segment可以触发刷新‘，这个情况还是蛮常见的😋

**Comment by 0x1306a94** [comment]
@pujiaxin33 我也遇到这个问题. 就是往上滑动到标签悬停后,手动调用下面代码也无法让其滚动到顶部
```Objective-C
[self.pagerView.mainTableView setContentOffset:CGPointZero animated:YES];
```

**Comment by pujiaxin33** [comment]
@0x1306a94 你看一下oc或swift的示例，有手动滚动的示例。

**Comment by 0x1306a94** [comment]
> @0x1306a94 你看一下oc或swift的示例，有手动滚动的示例。

看到了

**Comment by ZhengHei** [comment]
> **bug描述**
> 通过点击segment上的标签，触发mj_header.beginRefreshing()
> 
> * 有问题处：当segment处于第一个标签时，无下拉动画
> * 无问题处：segment处于非第一个标签，有下拉动画
> 
> （该问题仅在，segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑，这种情况下，才无下拉动画）
> 
> **版本号**
> 1.JXPagingView版本号：pod 'JXPagingView/Paging','2.0.1'，楼主最新代码Download下来也可以复现这个问题
> 2.OC还是Swift版本：Swift
> 3.手机系统版本号：iOS 13.4.1（Xcode11.4.1模拟器也有这个问题）
> 4.手机型号：iphone11
> 
> **复现步骤**
> 1、楼主的demo中加入如下代码
> 
> ```
> 1、BaseViewController中，添加通知
> func segmentedView(_ segmentedView: JXSegmentedView, didClickSelectedItemAt index: Int) {
>         print("jl==   didClickSelectedItemAt")
>         NotificationCenter.default.post(name: NSNotification.Name(rawValue: "NotificationCenter_didClickSelectedItemAt"), object: nil)
>     }
> 
> 2、ListViewController中，监听通知
> NotificationCenter.default.addObserver(self, selector: #selector(ntf), name: NSNotification.Name(rawValue: "NotificationCenter_didClickSelectedItemAt"), object: nil)
> @objc func ntf() {
>         if isNeedHeader {
>             print("jl== beginRefreshing")
>             self.tableView.mj_header.beginRefreshing()
>         }
>     }
> ```
> 
> 2、demo点击步骤
> （1）启动app，点击进入‘列表下拉刷新’页面
> （2）进入页面后，让页面稍微往上面滑动一点（让segment并不处置顶也不是处于最下，也就是让此时的segment既可以向上滑也可以向下滑）
> （3）点击segment上的’能力‘，会触发 ’mj_header.beginRefreshing()‘，此时没有mj的自动下拉的动画效果（如果点击的是第二个标签’爱好‘，是有自动下拉的动画效果）
> 
> **截图、GIF**
> 楼主现有的demo，下载下来，修改下就可以复现

你解决了嘛，我也是有同样的需求，遇到同样的问题
