### ISSUE TITLE
JXPaginView 升级到最新版，segmentedControl.listContainer = pagingView.listContainerView 赋值报错

### ISSUE THREAD

**Issue by XIAODINGPA** [pujiaxin33/JXPagingView#206]
![image](https://user-images.githubusercontent.com/28077025/79841150-92b25200-83e9-11ea-9c0d-ffbe21660469.png)

**Comment by pujiaxin33** [comment]
extension JXPagingListContainerView: JXSegmentedViewListContainer {}

**Comment by XIAODINGPA** [comment]
可以了，谢谢呀
