### ISSUE TITLE
无法取消pagerView.mainTableView的showsVerticalScrollIndicator显示效果

### ISSUE THREAD

**Issue by RomitLee** [pujiaxin33/JXPagingView#207]
**bug描述**
自定义一个tableview，设置table的showsVerticalScrollIndicator为NO，可是还是显示

**版本号**
1.JXPagingView版本号：最新版本
2.OC还是Swift版本：OC
3.手机系统版本号：ios12
4.手机型号：iphone11

**Comment by pujiaxin33** [comment]
`automaticallyDisplayListVerticalScrollIndicator`设置为NO
