### ISSUE TITLE
2.0.4版本有时候会白屏

### ISSUE THREAD

**Issue by BDiego** [pujiaxin33/JXPagingView#209]
**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：2.0.4
2.OC还是Swift版本：OC
3.手机系统版本号：iOS 13.3.1
4.手机型号：iPhone X

**复现步骤**
1. 遇到问题的相关效果、类是：是
2.具体的操作步骤是：
自定义的tableHeaderView异步加载数据，加载完以后[self.pagerView reloadData];
如果- (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index  返回的控制器里异步加载数据没有完成，就会白屏  （我的控制器里面是UICollectionView,返现里面的代理不走）

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
麻烦提供一个可复现问题的demo，你可以用现在的demo工程制造能制造出问题复现就行。

**Comment by BDiego** [comment]
点击 click  按钮，首次进来的时候  vc1  会空白













在 2020-04-30 17:16:06，"暴走的鑫鑫" <notifications@github.com> 写道：

麻烦提供一个可复现问题的demo，你可以用现在的demo工程制造能制造出问题复现就行。

**Comment by BDiego** [comment]
demo已发

**Comment by BDiego** [comment]
> 麻烦提供一个可复现问题的demo，你可以用现在的demo工程制造能制造出问题复现就行。

demo已发

**Comment by 200895045** [comment]
@pujiaxin33 这个问题解决了吗？我这也是同样的问题

**Comment by 200895045** [comment]
@pujiaxin33 我切换到2.0.1版本就没事

**Comment by BDiego** [comment]
> @pujiaxin33 我切换到2.0.1版本就没事

我也退回到2.0.1的版本了，新版的demo我发给开源大佬了

**Comment by pujiaxin33** [comment]
@BDiego 发到哪里的？

**Comment by pujiaxin33** [comment]
谢谢反馈，已找到问题，今天会更新一个2.0.5的包

**Comment by BDiego** [comment]
> 谢谢反馈，已找到问题，今天会更新一个2.0.5的包

好的，大佬
