### ISSUE TITLE
嵌套JXCategoryView出现切换头部无法向下滚动展示出来等问题

### ISSUE THREAD

**Issue by gobeyond** [pujiaxin33/JXPagingView#210]
**bug描述**
当嵌套JXCategoryView时，会出现JXCategoryView第1页滚动到底部时，切换到时JXCategoryView页时，头部无法往下滚动的情况，要切换到第1页，头部才能向下滚动展示出来

**版本号**
1.JXPagingView版本号：2.0.4？

最后在JXPagerView.m中
- (void)listViewDidScroll:(UIScrollView *)scrollView方法加上
self.currentScrollingListView = scrollView;
就能解决这问题

**Comment by pujiaxin33** [comment]
感谢反馈，你去下载最新的JXPagerView库，已经修复了该问题。
