### ISSUE TITLE
网络请求数据后首次刷新pager，不执行 pagerView: initListAtIndex: 这个代理方法！！

### ISSUE THREAD

**Issue by 200895045** [pujiaxin33/JXPagingView#211]
创建完categoryView、pagerView后，请求接口数据，然后执行刷新操作，没有走这个代理，必须滑动一下才走！！
[self.categoryView reloadData];
[self.pagerView reloadData];

**Comment by pujiaxin33** [comment]
谢谢反馈，已找到问题，今天会更新一个2.0.5的包

**Comment by wangchaodong** [comment]
这个问题在当前版本2.0.13 又出现了。 (swift5.0)
