### ISSUE TITLE
改变tableHeaderViewHeight的值后，底部显示不全

### ISSUE THREAD

**Issue by starkite** [pujiaxin33/JXPagingView#212]
**版本号**
1. JXPagingView版本号：最新版本 2.0.5， Pod 2.0.4
2. OC还是Swift版本：Swift

**bug描述**
1. 改变tableHeaderViewHeight的值后，底部显示不全，demo中设置200调整为70后实现偏移
2. 在列表下拉刷新中设置了pinSectionHeaderVerticalOffset 偏移量后，mainTableView仍然会有弹簧效果，不设置pinSectionHeaderVerticalOffset就不会出现

**截图、GIF**

![image](https://user-images.githubusercontent.com/2093033/81375934-192e9980-9135-11ea-8f39-854720a8394c.png)

![12](https://user-images.githubusercontent.com/2093033/81375986-33687780-9135-11ea-820d-1e1d0b79fd8b.PNG)

![IMG_4658](https://user-images.githubusercontent.com/2093033/81376014-40856680-9135-11ea-8a9e-358bd810346c.PNG)

![IMG_4659](https://user-images.githubusercontent.com/2093033/81376027-467b4780-9135-11ea-8442-d40303929ec7.PNG)

![IMG_4660](https://user-images.githubusercontent.com/2093033/81376030-47ac7480-9135-11ea-917f-03e23e66c2af.PNG)

![IMG_4662](https://user-images.githubusercontent.com/2093033/81376033-48dda180-9135-11ea-89dc-220b2242f9a7.PNG)

**Comment by pujiaxin33** [comment]
请参考demo示例，调用方法`resizeTableHeaderViewHeight`
