### ISSUE TITLE
如果全屏幕的视图，在初始化的时候，能否实现预加载当前视图的下一个视图，这样左滑就不会白屏loading页面，

### ISSUE THREAD

**Issue by hanjianfei** [pujiaxin33/JXPagingView#214]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
- (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index 每次滑动会进入这个方法，在这个方法初始化视图，在视图的viewdidload方法里执行网络请求，就会出现滑动白页显示的问题，想问下，预加载的话 改怎么操作

**Comment by hanjianfei** [comment]
可以使用初始化可以设置type JXPagerListContainerType_ScrollView  以scrollview代替collectionView 展示

**Comment by pujiaxin33** [comment]
需要你自己提前初始化列表，然后通过属性持有。然后在initListAtIndex方法里面返回你自己提前创建好的列表即可。
