### ISSUE TITLE
项目中使用了之后，在滑动的时候会突然跳一下

### ISSUE THREAD

**Issue by 624990742** [pujiaxin33/JXPagingView#216]
我是顶部刷新，头部视图是一个轮播图，当我手势触摸向上滑动的时候会忽然跳动一下就滑动上去了。这个是什么原因呢？

**Comment by pujiaxin33** [comment]
你试一下oc版本示例【顶部轮播视图手势处理】，看看是否有同样问题呢？如果没有，参考示例代码修改一下。

**Comment by 624990742** [comment]
我出现问题的版本就是oc版本的 624990742 邮箱：624990742@qq.com 签名由 网易邮箱大师 定制 在2020年05月19日 10:05，暴走的鑫鑫 写道： 你试一下oc版本示例【顶部轮播视图手势处理】，看看是否有同样问题呢？如果没有，参考示例代码修改一下。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by pujiaxin33** [comment]
你参考一下oc版本示例【顶部轮播视图手势处理】

**Comment by 624990742** [comment]
头部视图我是用的这个”TYCyclePagerView“三方实现的轮播图，我按照demo中进行了设置，可是还是不行。

**Comment by pujiaxin33** [comment]
demo示例有问题吗

**Comment by 624990742** [comment]
我还没试，我先去试一下看看

**Comment by dawnnnnn** [comment]
swift中也有这个问题，并且头部只是一个view

**Comment by pujiaxin33** [comment]
@dawnnnnn demo也有这个问题吗？只要能通过demo复现，然后把复现路径，操作环境告诉就行。

**Comment by 624990742** [comment]
非常感谢问题已经解决，是因为在板块的控制器中少实现了一个方法，现在好了。这行代码的意思是什么意思呢？
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    !self.scrollCallback ?: self.scrollCallback(scrollView);
}

**Comment by pujiaxin33** [comment]
就是把列表的滚动传递给JXPaingView进行处理。

**Comment by 624990742** [comment]
嗯，这下知道啦。非常感谢。

**Comment by queli1990** [comment]
@624990742 我也遇到同样的问题了，怎么解决的呢，可以贴一些细节吗？

**Comment by eric1202** [comment]
> @624990742 我也遇到同样的问题了，怎么解决的呢，可以贴一些细节吗？

func scrollViewDidScroll(_ scrollView: UIScrollView) {
        self.listViewDidScrollCallback?(scrollView)
    }


 func listViewDidScrollCallback(callback: @escaping (UIScrollView) -> Void) {
        self.listViewDidScrollCallback = callback

    }

这两个方法要实现！！ 搞了我2天了。。。。。。

**Comment by 19aneng** [comment]
2021年还是遇到了，建议作者把这个写在readme那里
仅仅实现以下方法是没办法解决问题的。
- (void)listViewDidScrollCallback:(void (^)(UIScrollView *))callback {
    self.scrollCallback = callback;
}

PagingViewController代码并没有实现
(void)scrollViewDidScroll:(UIScrollView *)scrollView {
!self.scrollCallback ?: self.scrollCallback(scrollView);
}

导致我一直出现跳动问题

**Comment by Liyongcong** [comment]
> 头部视图我是用的这个”TYCyclePagerView“三方实现的轮播图，我按照demo中进行了设置，可是还是不行。
你好，我先也想实现顶部轮播，然后header自定义悬浮，请问你怎么实现的

**Comment by queli1990** [comment]
您好，您的邮件已收到，我会尽快查阅，谢谢！

**Comment by joshiaProgram** [comment]
scrollViewDidScroll 无论怎么滑动都不回调

**Comment by queli1990** [comment]
您好，您的邮件已收到，我会尽快查阅，谢谢！
