### ISSUE TITLE
发生了崩溃，导致菜单栏和scrollview上下联动不了怎么处理

### ISSUE THREAD

**Issue by zfx5130** [pujiaxin33/JXPagingView#217]
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[JXPagerListContainerView contentScrollView]: unrecognized selector sent to instance 0x10e8095c0'

self.categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pagerView.listContainerView; 这句话发生崩溃，把Test代码放入项目也是崩溃，但是在你的TestDemo就不会，这个怎么解决

**Comment by pujiaxin33** [comment]
你确定一下是不是最新版本呢？self.categoryView.listContainer = (id)self.pagerView.listContainerView;是后面版本引入进来。

**Comment by zfx5130** [comment]
@pujiaxin33  通过pod下载的， 如果不是的话， 不应该直接报错么， 没有此类方法

**Comment by zfx5130** [comment]
@pujiaxin33  我对比了下代码，我通过pod更新的和你demo里面的代码确实不是同一版本，问题解决了， 感谢
