### ISSUE TITLE
使用 JXPagingListRefreshView 和全屏返回 push到下一个vc 导致所有pop 行为失效

### ISSUE THREAD

**Issue by wangjinshan** [pujiaxin33/JXPagingView#219]
lazy var pagingView: JXPagingListRefreshView = {
        let view = JXPagingListRefreshView(delegate: self, listContainerType: .scrollView)
        return view
    }()
// 框架引用代码
extension HomeworkListController {

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        navigationController?.fd_fullscreenPopGestureRecognizer?.isEnabled = (segmentedView.selectedIndex == 0)
    }

    override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        view.endEditing(true)
        navigationController?.fd_fullscreenPopGestureRecognizer?.isEnabled = true
    }

    func setupJxUI() {
        segmentedView.backgroundColor = ThemeColor.shared.homeCardBgColor
        segmentedView.delegate = self
        segmentedView.isContentScrollViewClickTransitionAnimationEnabled = false
        segmentConfig.selectedAttributedTitles = segmentTitleSelectedConfig
        if let segmentTitleNormalConfig = segmentTitleNormalConfig {
            segmentConfig.attributedTitles = segmentTitleNormalConfig
        }
        segmentedView.dataSource = segmentConfig
        if isSender {
            segmentedView.contentEdgeInsetRight = JXSegmentedViewAutomaticDimension
            segmentedView.indicators = [configIndicator]
        } else {
            segmentedView.contentEdgeInsetLeft = topMargin
        }

        let lineWidth = 1.0 / UIScreen.main.scale
        let bottomLineView = UIView()
        bottomLineView.backgroundColor = ThemeColor.shared.comSeparatorColor
        bottomLineView.frame = CGRect(x: 0, y: segmentedView.bounds.height - lineWidth, width: segmentedView.bounds.width, height: lineWidth)
        bottomLineView.autoresizingMask = .flexibleWidth
        segmentedView.addSubview(bottomLineView)

        pagingView.mainTableView.gestureDelegate = self
        pagingView.backgroundColor = ThemeColor.shared.homeCardBgColor
        view.addSubview(pagingView)
        segmentedView.listContainer = pagingView.listContainerView

        if let ges = navigationController?.fd_fullscreenPopGestureRecognizer {
            pagingView.listContainerView.scrollView.panGestureRecognizer.require(toFail: ges)
            pagingView.mainTableView.panGestureRecognizer.require(toFail: ges)
        }
    }

}

// MARK: - 三方代理
extension HomeworkListController: JXPagingViewDelegate {

    func tableHeaderViewHeight(in pagingView: JXPagingView) -> Int {
        let height = Int(userDetailHeadView.viewHeight)
        return height
    }

    func tableHeaderView(in pagingView: JXPagingView) -> UIView {
      return userHeaderBgView
    }

    func heightForPinSectionHeader(in pagingView: JXPagingView) -> Int {
        return Int(sectionHeight)
    }

    func viewForPinSectionHeader(in pagingView: JXPagingView) -> UIView {
        return segmentedView
    }

    func numberOfLists(in pagingView: JXPagingView) -> Int {
        return subControllersArr.count
    }

    func pagingView(_ pagingView: JXPagingView, initListAtIndex index: Int) -> JXPagingViewListViewDelegate {
        return subControllersArr[index]
    }

    func mainTableViewDidScroll(_ scrollView: UIScrollView) {
        configCloseViewIsHidden(offset: scrollView.contentOffset)
    }

    func scrollViewClassInListContainerView(in pagingView: JXPagingView) -> AnyClass {
        return FullScreenGestureScrollView.self
    }

}

extension HomeworkListController: JXSegmentedViewDelegate {
    func segmentedView(_ segmentedView: JXSegmentedView, didSelectedItemAt index: Int) {
        navigationController?.fd_fullscreenPopGestureRecognizer?.isEnabled = (index == 0)
        if isSender {
            loadResultsCount()
            reloadListData() // 滑动刷新数据
        }
    }
}

extension HomeworkListController: JXPagingMainTableViewGestureDelegate {
    func mainTableViewGestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if otherGestureRecognizer == segmentedView.collectionView.panGestureRecognizer {
            return false
        }
        return gestureRecognizer.isKind(of: UIPanGestureRecognizer.self) && otherGestureRecognizer.isKind(of: UIPanGestureRecognizer.self)
    }
}

class FullScreenGestureScrollView: UIScrollView, UIGestureRecognizerDelegate {

    func gestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        if contentOffset.x <= 0 {
            let tempClass: AnyClass? = NSClassFromString("_FDFullscreenPopGestureRecognizerDelegate")
            if let temp = tempClass, let delegate = otherGestureRecognizer.delegate, delegate.isKind(of: temp) {
                return true
            }
        }
        return false
    }
}

问题: 这个scrollViewClassInListContainerView  代理方法一直没有执行
导致push 之后的界面 pop 行为全部失效

**Comment by pujiaxin33** [comment]
你确保用最新版本试试呢？scrollViewClassInListContainerView这个代理方法失效已经修复过了。

**Comment by wangjinshan** [comment]
swift 版本最新版本是 2.0.6  
  - JXPagingView/Paging (2.0.6)
  - JXSegmentedView (1.0.6)

scrollViewClassInListContainerView  这个代理方法 swift 没有内部实现 
oc 版本是好的 
swift Demo 也没有实现这个方法

**Comment by pujiaxin33** [comment]
你用最新的swift demo试试呢？已经修复了
