### ISSUE TITLE
这种效果怎么实现。。

### ISSUE THREAD

**Issue by zhangqi02060227m** [pujiaxin33/JXPagingView#22]
![Uploading IMG_1282.GIF…]
请问一下这个怎么实现，oc版demo中能加一个吗？？？或者说一下思路也行。。谢了。。。

**Comment by pujiaxin33** [comment]
图片没有上传成功

**Comment by zhangqi02060227m** [comment]
嗯，我知道怎么实现了。。。。自己研究出来了。谢谢
