### ISSUE TITLE
header里面 masonry布局，高度一直0

### ISSUE THREAD

**Issue by whpanda** [pujiaxin33/JXPagingView#220]
header里面比较复杂，有原生也有webview组合的，所有高度不固定，需要webview加载完成计算才能得出整个的高度，使用masonry自动算的，如果不使用这个库，使用uiview可以自动撑开没问题，使用这个库，把撑开的view做headerview，高度就一直是0，请问这种怎么处理？使用resizeTableHeaderViewHeightWithAnimatable这个也是0，如果可以的话，求解答

**Comment by pujiaxin33** [comment]
你可以自己提前计算出高度吗？然后在相关的代理方法里面返回

**Comment by whpanda** [comment]
> 里面

提前计算不了，主要是要等webview加载完成，而且好几个...使用kvo监测webview content高度变化的，然后设置webview frame，然后才能知道headerview高度

**Comment by pujiaxin33** [comment]
你试一下，等webview加载完成回调之后计算出高度，再让pagingView reload一下

**Comment by whpanda** [comment]
我写了个demo，能否给个邮箱，麻烦看一下？

**Comment by pujiaxin33** [comment]
317437084@qq.com

**Comment by whpanda** [comment]
已发送

**Comment by whpanda** [comment]
添加了pagerview好像masonry就失效了

**Comment by pujiaxin33** [comment]
我在oc版本示例，添加了一个DynamicHeader示例，你可以参考一下。还有就是你发给我的demo，我已经修改好了，回复给你了，你查收一下。

**Comment by whpanda** [comment]
好的，非常感谢大佬

**Comment by whpanda** [comment]
单个webview很好处理，多个不太行
