### ISSUE TITLE
获取列表tableview可见cell不准确

### ISSUE THREAD

**Issue by huangxianyu** [pujiaxin33/JXPagingView#222]
当前没上滑状态下, 获取可见cell
NSArray <NSIndexPath *> *indexArray = [self.tableView indexPathsForVisibleRows];
![image](https://user-images.githubusercontent.com/20720740/82912398-a67c4580-9f9f-11ea-99ed-77feecab387e.png)

获取到的是下面状态, 全上滑后所有的cell
![image](https://user-images.githubusercontent.com/20720740/82912789-112d8100-9fa0-11ea-8f4d-90c6e25ece2c.png)

有没有办法解决?

**Comment by pujiaxin33** [comment]
没有，因为tableView的frame就是第二张图那么大。
