### ISSUE TITLE
SmoothListViewController 下拉刷新有问题

### ISSUE THREAD

**Issue by daoxingwudao** [pujiaxin33/JXPagingView#223]
当修改 SmoothListViewController  self.count = 10;时  或者 说这个页面 没有数据时页面下拉刷新会出现问题  一下拉页面立刻弹回去

**Comment by homeYsy** [comment]
我也发现这个问题了，SmoothListViewController的下拉刷新立刻回弹，没有中间刷新的那个过渡

**Comment by pujiaxin33** [comment]
感谢反馈，我已经在最新demo修复了。
