### ISSUE TITLE
JXPagingView嵌套JXPagingView使用

### ISSUE THREAD

**Issue by LvBisheng** [pujiaxin33/JXPagingView#226]
JXPagingView嵌套JXPagingView使用时，滑动会有问题，我看demo和issue并没有相关场景

**Comment by pujiaxin33** [comment]
什么问题，麻烦详细描述一下

**Comment by daoxingwudao** [comment]
页面 会很卡顿 在demo RefreshViewController 中给 listView.dataSource中赋大量的值滚动 可以看到页面的卡顿

**Comment by LvBisheng** [comment]
控制器A使用了JXPagingView，对应列表控制器（准守JXPagingViewListViewDelegate协议）是B, i, j...;&nbsp; &nbsp; 然后B本身也使用了JXPagingView，B对应列表控制器（准守JXPagingViewListViewDelegate协议））为e, f...。这种情况下，在滑动e, f的时候就会有问题，不像滑动i, j...那么正常。不知道讲得清不清楚。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "暴走的鑫鑫"<notifications@github.com&gt;; 
发送时间: 2020年6月8日(星期一) 上午9:17
收件人: "pujiaxin33/JXPagingView"<JXPagingView@noreply.github.com&gt;; 
抄送: "天的那一边"<victory.lv@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [pujiaxin33/JXPagingView] JXPagingView嵌套JXPagingView使用 (#226)





 
什么问题，麻烦详细描述一下

**Comment by pujiaxin33** [comment]
暂不支持JXPagingView嵌套JXPagingView使用

**Comment by pujiaxin33** [comment]
你能发一下ui截图吗？很好奇【JXPagingView嵌套JXPagingView使用】的效果

**Comment by QingyuHu** [comment]
同样嵌套使用，没有遇到问题，我使用的是两个JXPagerListRefreshView
![Simulator Screen Shot - iPhone 11 Pro - 2020-07-14 at 13 00 28](https://user-images.githubusercontent.com/6188580/87387441-4be18c00-c5d5-11ea-99d8-500bc82df550.png)
