### ISSUE TITLE
v2.0.2 swift 5.0 reloadData() 泄露

### ISSUE THREAD

**Issue by EdgarHz** [pujiaxin33/JXPagingView#227]
使用官方demo: 主页下拉刷新&列表上拉加载更多
下拉刷新多次后ListViewController未释放。
泄露原因为containerVC.addChild(vc) 而在reloadData时未做清理

`open func reloadData() {
        currentList = nil
        currentScrollingListView = nil
        validListDict.values.forEach { $0.listView().removeFromSuperview() }
        validListDict.removeAll()
        refreshTableHeaderView()
        mainTableView.reloadData()
        listContainerView.reloadData()
    }

func listWillAppear(at index: Int) {
....
           existedList = dataSource.listContainerView(self, initListAt: index)
            guard let list = existedList else {
                return
            }
            if let vc = list as? UIViewController {
                containerVC.addChild(vc)
            }
....
}
`

**Comment by pujiaxin33** [comment]
感谢反馈，已找到问题。

**Comment by shannonchou** [comment]
> 感谢反馈，已找到问题。

请问有修复版本可用了吗？

**Comment by pujiaxin33** [comment]
恩，2.0.10
