### ISSUE TITLE
有 headerView 的情况下，self.segmentedView.selectedIndex != 0，headerView 没有返回手势

### ISSUE THREAD

**Issue by fuhailong** [pujiaxin33/JXPagingView#228]
我看你的 demo 里，未了防止 self.segmentedView.selectedIndex 不为0的情况下触发侧滑返回，你在这里
`func segmentedView(_ segmentedView: JXSegmentedView, didSelectedItemAt index: Int) {
        self.navigationController?.interactivePopGestureRecognizer?.isEnabled = (index == 0)
    }`
做了判断，非0的情况下禁用掉侧滑手势
但是这就有一个新问题，这个手势是全局的 ，如果此时我有一个 headerView，而且这个 headerView 比较大，想在这个区域能响应侧滑这个手势的情况下，这个非0就设定，会使 headerView 上也无法响应

**Comment by fuhailong** [comment]
解决办法 
在对应的 headerView 里添加
`
override func hitTest(_ point: CGPoint, with event: UIEvent?) -> UIView? {
        let navi = AppDelegate.shared.tab?.selectedViewController as? UINavigationController
        navi?.fd_fullscreenPopGestureRecognizer.isEnabled = true
        return self
    }
`

**Comment by pujiaxin33** [comment]
好像也只能按照你的方案解决，非常赞的思路👍
