### ISSUE TITLE
Swift 中出现问题 

### ISSUE THREAD

**Issue by LuYinhao** [pujiaxin33/JXPagingView#229]
完整复制过来的demo， segmentedView.listContainer = pagingView.listContainerView 
提示Cannot assign value of type 'JXPagingListContainerView' to type 'JXSegmentedViewListContainerView‘
错误

**Comment by fengzeyan** [comment]
老哥怎么解决的

**Comment by LuYinhao** [comment]
实现一个必须实现的协议。在你使用的swift文件顶部或者别的地方写这句：
extension JXPagingListContainerView: JXSegmentedViewListContainer {}





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "冯泽雁"<notifications@github.com&gt;; 
发送时间: 2021年2月24日(星期三) 下午5:47
收件人: "pujiaxin33/JXPagingView"<JXPagingView@noreply.github.com&gt;; 
抄送: "杨树🅥"<29539153@qq.com&gt;; "State change"<state_change@noreply.github.com&gt;; 
主题: Re: [pujiaxin33/JXPagingView] Swift 中出现问题  (#229)





 
老哥怎么解决的
