### ISSUE TITLE
内存泄漏问题

### ISSUE THREAD

**Issue by gongxinle** [pujiaxin33/JXPagingView#230]
**bug描述**
demo中的RefreshViewController页面刷新之后ListViewController并没有被释放，导致内存泄漏

**版本号**
1.JXPagingView版本号：最新版
2.OC还是Swift版本：OC
3.手机系统版本号：13.5
4.手机型号：模拟器

**复现步骤**
1. 遇到问题的相关效果、类是：
demo中的RefreshViewController页面刷新之后ListViewController并没有被释放，导致内存泄漏
2.具体的操作步骤是：下拉刷新

ps:由于项目内容较多，内存泄漏比较严重。

**Comment by gongxinle** [comment]
> 可以使用 - (id)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index {
> if(index==0){
> return self.xxx;
> }
> }
> 
> 试试

应该不是这里引起的问题

**Comment by daoxingwudao** [comment]
可以使用 JXPagerSmoothView  代替  测试 JXPagerSmoothView没有内存泄漏   demo中的RefreshViewController 不走dealloc

**Comment by pujiaxin33** [comment]
感谢反馈，已修复

**Comment by pujiaxin33** [comment]
感谢反馈，已修复

**Comment by qishi1716** [comment]
咋解决的?

**Comment by wangchaodong** [comment]
swift 最新版本 依然存在这个问题
