### ISSUE TITLE
使用RxSwift监听mainTableView的didEndDecelerating，会导致subscribe失效

### ISSUE THREAD

**Issue by vjieshao** [pujiaxin33/JXPagingView#231]
复现步骤：
1、设置JXPagingView的pinSectionHeaderVerticalOffset不为0，如pagingView.pinSectionHeaderVerticalOffset = 64
2、使用RxSwift进行监听
`self.pagingView.mainTableView.rx.didEndDecelerating.subscribe { event in
            print("打印了")
}`
3、最终没有打印（如果pinSectionHeaderVerticalOffset设置为0或者不设置，则没问题）

问题定位：
通过查看源码，发现跟JXPagingView.swift 197行中adjustMainScrollViewToTargetContentInsetIfNeeded里面的mainTableView.delegate = nil有关。

希望能修复下这个问题，谢谢！关乎到项目中的一个需求。

**Comment by pujiaxin33** [comment]
mainTableView.delegate = nil
这句代码是为了修复循环调用。你可以通过其他方式处理didEndDecelerating事件吗？

**Comment by vjieshao** [comment]
好的，谢谢，我看看有没有其他的解决方案。

**Comment by pujiaxin33** [comment]
添加了代理方法`@objc optional func pagingView(_ pagingView: JXPagingView, mainTableViewDidEndDragging scrollView: UIScrollView, willDecelerate decelerate: Bool)`
