### ISSUE TITLE
tableView的reloadData的方法会执行 好多次 次 scrollViewDidScroll 

### ISSUE THREAD

**Issue by hapiii** [pujiaxin33/JXPagingView#233]
**bug提交前阅读**
iOS 12.2情况下执行tableView的reloadData的方法会执行 N 次 scrollViewDidScroll 方法
造成内存过大奔溃
N 于已加载cell的个数成正相关次数 

**bug描述**
目前发现iOS12.2,iOS12.4 调用tableView的reloadData的方法 会多次 执行scrollViewDidScroll 回调,如果cell个数非常多的话会造成app崩溃

**版本号**
1.JXPagingView版本号：'1.1.19'
2.OC还是Swift版本：OC
3.手机系统版本号：iOS 12.2 
4.手机型号：XSMax

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagerView
2.具体的操作步骤是：
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    !self.scrollCallback ?: self.scrollCallback(scrollView);
}

- (UIView *)listView {
    return self;
}

- (UIScrollView *)listScrollView {
    return self.tableView;
}

执行[tableView reloadData]

**截图、GIF**
感觉这个更像是系统bug,以前是没问题的,就最近从前天开始出现这个情况,之前reloadData是否会多次调用scrollViewDidScroll我也没有留意

**Comment by pujiaxin33** [comment]
从你的描述，应该是循环调用导致的问题。建议你升级到最新2.0.6版本再试试。
