### ISSUE TITLE
结合MJRefresh上拉下拉加载bug

### ISSUE THREAD

**Issue by baiyidjp** [pujiaxin33/JXPagingView#234]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
在数据没有铺满一屏的时候，会出现bug，一直响应上拉刷新的回调。稍微滑动tableView就会复现。

**版本号**
1.JXPagingView版本号：
  - JXCategoryView (1.5.5)
  - JXPagingView/Pager (2.0.6)
2.OC还是Swift版本：OC
3.手机系统版本号：模拟器
4.手机型号：iPhone11

**复现步骤**
打开OC的demo，选择-主页下拉刷新&列表上拉加载更多-。选择爱好tab,收治稍微滑动（上下都一样）就会触发上拉加载的回调

**截图、GIF**

![Kapture 2020-06-17 at 12 17 19](https://user-images.githubusercontent.com/12672573/84855082-d518a800-b095-11ea-9f59-eddd558e0178.gif)

**Comment by LuYinhao** [comment]
我也是哦

**Comment by pujiaxin33** [comment]
为了解答你们的问题，去看了mj的源码，然后又试了一下mj的example。答案出来了。他自己的示例也是不足一屏幕的数据，你下拉一点也会触发加载更多。

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/87277566-20976800-c515-11ea-99d5-f320e2f5225c.png)
这是调用栈，它是监听手势的state，来决定刷新的。对应JXPaingView来说，当手指在列表上下滑动的时候，其实列表的手势是在响应的，只是当header没有完全隐藏时，内部会再次把列表的contentOffset.y更新0，达到列表没有移动移动的效果。

**Comment by pujiaxin33** [comment]
要理解这个，要看一下JXPaingView的视图层级了。

**Comment by baiyidjp** [comment]
对的，这个发现了。所以只能根据状态设置为没有更多数据就ok了。
