### ISSUE TITLE
手势冲突问题

### ISSUE THREAD

**Issue by onewangxun** [pujiaxin33/JXPagingView#236]
1.headerView 是一个 collectionView1 并且 该 collectionView1中的 collectionViewCell中嵌套横向滚动的 collectionView2 ，并且有在你提供的代理方法中做如下处理
- (BOOL)mainTableViewGestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer {
    //禁止categoryView左右滑动的时候，上下和左右都可以滚动
    if (otherGestureRecognizer == self.categoryView.collectionView.panGestureRecognizer ||  (otherGestureRecognizer == self.headerView.collectionView1.panGestureRecognizer)  ) {
        return NO;
    }
    return [gestureRecognizer isKindOfClass:[UIPanGestureRecognizer class]] && [otherGestureRecognizer isKindOfClass:[UIPanGestureRecognizer class]];
}

但是依然发现有时候滚动cell中的这个横向滚动的的 collectionView2 的时候回触发上下滚动

**Comment by pujiaxin33** [comment]
> 并且 该 collectionView1中的 collectionView��Cell中嵌套横向滚动的 collectionView2 

从你的描述中得出，在该代理方法还需要把当前可见的cell里面的collectionView.panGestureRecognizer加入判断。

**Comment by zhangzongqi** [comment]
赞赞赞，解决了！
