### ISSUE TITLE
列表下拉刷新中 设置pinSectionHeaderVerticalOffset的值的有几率出现的bug

### ISSUE THREAD

**Issue by zhangxiongwen** [pujiaxin33/JXPagingView#237]
**bug描述**
在测试列表下拉刷新的时候，如果设置了pinSectionHeaderVerticalOffset属性，当列表的数据量很多的时候，categoryView已经悬浮，listView也往上滑动了很多的情况下，如果快速往上滑动listView，有几率会使得headView马上显示出来

**版本号**
1.JXPagingView版本号：最新的版本
2.OC还是Swift版本：OC
3.手机系统版本号：ios13.4
4.手机型号：iPhone 7

**复现步骤**
1.出现的类：PagingViewController
”列表下拉刷新“页面

2.具体的操作步骤是：？
在demo中 把listView的数据源增加一些
设置self.pagerView.pinSectionHeaderVerticalOffset = 100;
进入”列表下拉刷新“页面
滑动listView，当categoryView已经悬浮，listView也往上滑动了很多的情况下
如果快速往上滑动listView，有几率会使得headView马上显示出来，
如果当headView的高度大一些的时候就不会出现这个bug

gif图：
[Untitled.gif.zip](https://github.com/pujiaxin33/JXPagingView/files/4807725/Untitled.gif.zip)

**Comment by pujiaxin33** [comment]
感谢反馈，已修复，静候新版本发布。
