### ISSUE TITLE
iOS 12 的情况下，只要目前的大于pinSectionHeaderVerticalOffset的值，每次进入都会往上便宜pinSectionHeaderVerticalOffset值的距离

### ISSUE THREAD

**Issue by weizhangCoder** [pujiaxin33/JXPagingView#239]
**bug描述**
iOS 13 没有问题，在iOS 12下设置 pinSectionHeaderVerticalOffset 等于64 的话，当前页面的额偏移量大于pinSectionHeaderVerticalOffset的时候。 进入子页面后，再返回当前页面，每次都要刷新数据  ，用下面的方法
 [self.categoryView reloadDataWithoutListContainer];
 [self.pagerView reloadData];
然后界面就会向上偏移pinSectionHeaderVerticalOffset的值的距离。目前找了一下问题，发现大概是出在这句代码上。还请大佬看看
<img width="1074" alt="image" src="https://user-images.githubusercontent.com/11644326/86322591-d806c180-bc6d-11ea-86d0-122252d937fc.png">

**版本号**
1.JXPagingView版本号：2.0.6
2.OC还是Swift版本：OC
3.手机系统版本号：目前发现是iOS 12有问题
4.手机型号：6s

**复现步骤**
1. 当前界面的偏移量一定要大于 pinSectionHeaderVerticalOffset 值
2.具体的操作步骤是：点击进入下一页后然后再返回，刷新当前页面，在iOS 12 上就会出现界面偏移pinSectionHeaderVerticalOffset的距离

**截图、GIF**
提供bug出现时的截图或者GIF。

[展示视频.mp4.zip](https://github.com/pujiaxin33/JXPagingView/files/4862346/mp4.zip)

**Comment by weizhangCoder** [comment]
自己试了一下。感觉这块代码，应该是要有头部视图高度的判断。
if (scrollView.contentOffset.y >= [self.delegate heightForPinSectionHeaderInPagerView:self] - self.pinSectionHeaderVerticalOffset) {
//        if (scrollView.contentOffset.y >= self.pinSectionHeaderVerticalOffset) {
            //固定的位置就是contentInset.top
            [self adjustMainScrollViewToTargetContentInsetIfNeeded:UIEdgeInsetsMake(self.pinSectionHeaderVerticalOffset, 0, 0, 0)];
        }

**Comment by pujiaxin33** [comment]
我在reloadData方法添加了以下方法：
```Objective-C
    if (self.pinSectionHeaderVerticalOffset != 0) {
        self.mainTableView.contentOffset = CGPointZero;
    }
```
这样调用reloadData就会有正常的表现，不会记住当前的contentOffset，会让页面重新置顶。

**Comment by weizhangCoder** [comment]
当self.pinSectionHeaderVerticalOffset 是64的时候。当前界面的偏移量大于64，就会走箭头所指的方法，
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/11644326/87267078-4c0c5980-c4f9-11ea-9cd8-89dbff660aca.png">  然后每次到这个界面重新reloadData。就会在原来偏移的基础上在偏移self.pinSectionHeaderVerticalOffset的距离，你可以看下视频展示

**Comment by pujiaxin33** [comment]
你试一下最新2.0.7版本，reloadData之后会置顶
