### ISSUE TITLE
JXPagingView遵守的UITableViewDelegate能否改成open

### ISSUE THREAD

**Issue by iamjjh** [pujiaxin33/JXPagingView#240]
**Feature描述**
请简单描述你想要的效果：JXPagingView遵守的UITableViewDelegate能否改成open，子类有需要重写scrollViewWillBeginDragging(_ scrollView: UIScrollView)函数。

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：无
2.目标页面路径：无
3.目标效果截图：无

**其他补充**
关于目标效果的其他说明：无

**Comment by pujiaxin33** [comment]
谢谢反馈，已改为open
