### ISSUE TITLE
请简单描述你想要的效果：JXPagerListContainerView 的 listCellBackgroundColor 属性没有设置的地方

### ISSUE THREAD

**Issue by anyanf** [pujiaxin33/JXPagingView#241]
**Feature描述**
请简单描述你想要的效果：JXPagerView 中，JXPagerListContainerView 的 listCellBackgroundColor 属性没有设置的接口，希望 JXPagerView 提供可以设置 JXPagerListContainerView 的 listCellBackgroundColor 的方案。

因为 app 是黑色主题，所以 listCellBackgroundColor 是白色，再JXPagerView的第0个list，跳到第2个以及以后的list的动画过程中，会把第一个list的白色背景颜色显示出来，会显得非常突兀，希望作者能提供一个设置的接口。

**Comment by pujiaxin33** [comment]
```Objective-C
self.pagerView.listContainerView.listCellBackgroundColor = [UIColor blackColor];
```
