### ISSUE TITLE
怎么控制segmentedView及listView的frame

### ISSUE THREAD

**Issue by MusicOnMyMind** [pujiaxin33/JXPagingView#242]
segmentedView及listView与pagingView边距设置，现在默认是全屏宽度，手动修改了还是会回滚到全屏宽度

**Comment by pujiaxin33** [comment]
你能截图说明一下吗？

**Comment by MusicOnMyMind** [comment]
> 你能截图说明一下吗？

好的，图上圈的就是我的结症所在

![4EDC20D4-39CD-425D-BA23-D2572931EF8C](https://user-images.githubusercontent.com/16969590/87406853-ecdf3f80-c5f3-11ea-88dc-be41fdb997ec.png)

**Comment by MusicOnMyMind** [comment]
> 你能截图说明一下吗？

好的，请帮忙看看哈

需求是红色banner是要LR铺满，然后绿色segmentedView悬停

我现在的做法是pagingView左右添加指定间距约束，这样子是除了banner，其他都是满足需求的

如果pagingView左右0间距，banner正常，底下的listView就不正常了(无法正常指定frame来设置间距)

如果现在我pagingView宽度铺满的话 banner就正常 但是listView就不能保持正常左右间距()
![4EDC20D4-39CD-425D-BA23-D2572931EF8C](https://user-images.githubusercontent.com/16969590/87513241-f8417200-c6aa-11ea-9ca4-272c4e68621d.png)

**Comment by MusicOnMyMind** [comment]
> 你能截图说明一下吗？

好的，麻烦帮忙看看，3Q

![IMG_2461](https://user-images.githubusercontent.com/16969590/87515224-16f53800-c6ae-11ea-87d7-d8219288c843.PNG)

![IMG_2462](https://user-images.githubusercontent.com/16969590/87515247-22486380-c6ae-11ea-8dea-35b283f61782.PNG)

**Comment by pujiaxin33** [comment]
暂不支持，你这种布局，自己fork修改源码适配吧

**Comment by MusicOnMyMind** [comment]
> 暂不支持，你这种布局，自己fork修改源码适配吧

好的 已经处理好了 谢谢
