### ISSUE TITLE
关于自定义悬浮视图

### ISSUE THREAD

**Issue by fanlilinSaber** [pujiaxin33/JXPagingView#243]
我没搞懂为啥要是是用这个才能正常使用
self.categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pagerView.listContainerView;

在自定义自定义悬浮视图 我没有用 JXCategoryTitleView  这个作为悬浮窗了 代理也是
- (UIView *)viewForPinSectionHeaderInPagerView:(JXPagerView *)pagerView {
    return self.customCategoryView;
}

为什么单独定义自定义悬浮视图  不能正常使用

**Comment by pujiaxin33** [comment]
你看一下CustomCategoryViewController示例类，就知道自定义悬浮视图怎么用了。
```Objective-c
self.categoryView.listContainer = (id)self.pagerView.listContainerView;
```
这段代码就是通过协议，把交互的逻辑封装起来了。

**Comment by 542604974** [comment]
你好，为啥我用这段代码就崩溃呢
