### ISSUE TITLE
PagingViewTableHeaderView 添加button，点击事件无法响应

### ISSUE THREAD

**Issue by HanFei0813** [pujiaxin33/JXPagingView#244]
oc, pod 引入最新 2.0.6 版本，
尝试在 PagingViewTableHeaderView 总添加button，button点击事件无法响应

**Comment by pujiaxin33** [comment]
我在最新的示例，在PagingViewTableHeaderView 上面添加了【关注】按钮，并且能够响应点击。你看一下呢

**Comment by CoderFZHan** [comment]
暂时看不到最新的代码，找不到关注按钮。

**Comment by pujiaxin33** [comment]
swift和oc版本都看一下示例

**Comment by HuTuXuZai** [comment]
我的也是，不过是反过来的， 我的是 JXPagingView 的上的tableview ， 由于PagingViewTableHeaderView高度很高（我试过把高度变小，JXPagingView 的上的tableview的cell上的按钮就可以点击）， 不能点击

**Comment by huxiaoxin** [comment]
我这也是，头一次能点击，切换视图后再 回来无法点击
