### ISSUE TITLE
当self.pinSectionHeaderVerticalOffset 是64的时候。当前界面的偏移量大于64，就会走箭头所指的方法，

### ISSUE THREAD

**Issue by weizhangCoder** [pujiaxin33/JXPagingView#246]
当self.pinSectionHeaderVerticalOffset 是64的时候。当前界面的偏移量大于64，就会走箭头所指的方法，
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/11644326/87267078-4c0c5980-c4f9-11ea-9cd8-89dbff660aca.png">  然后每次到这个界面重新reloadData。就会在原来偏移的基础上在偏移self.pinSectionHeaderVerticalOffset的距离，你可以看下视频展示

_Originally posted by @weizhangCoder in https://github.com/pujiaxin33/JXPagingView/issues/239#issuecomment-657335394_

**Comment by weizhangCoder** [comment]
[JXPagingView.zip](https://github.com/pujiaxin33/JXPagingView/files/4916898/JXPagingView.zip)

这个是我稍微修改了一下你的源码，在NaviBarHiddenViewController这个控制器里面68行添加2个刷新方法
<img width="576" alt="image" src="https://user-images.githubusercontent.com/11644326/87390853-40de2a00-c5dc-11ea-8ced-143d116faaf2.png"> 然后头部的偏移量大于64 导航栏的时候，点击cell，进入下一个界面，然后在返回到当前界面，iOS 13 以上的系统偏移量不会发生变化。iOS 13一下的系统都会发生偏移。

**Comment by weizhangCoder** [comment]
我看到2.0.7版本，如果设置self.pagerView.pinSectionHeaderVerticalOffset =64了，reloadData 的时候，就会偏移到最顶端
<img width="918" alt="image" src="https://user-images.githubusercontent.com/11644326/87502283-ca046800-c693-11ea-936c-120d0a9ccc1f.png">。有这样一个场景我这个界面的数据是不确定的，所以我每次进入都会在每次进入的时候刷新数据的
<img width="699" alt="image" src="https://user-images.githubusercontent.com/11644326/87502564-6c245000-c694-11ea-89d5-b57e0fbcba83.png">
，我reloadData后是不需要返回到最顶部的，只要停留在当前滑动位置就好。
<img width="412" alt="image" src="https://user-images.githubusercontent.com/11644326/87502724-e9e85b80-c694-11ea-97c8-ea7d8d34c80b.png">
比如这个能力的item 下有100条数据，我分页的时候看到了第90条数据。点击进去之后，我又返回当前界面，但是因为我每次都要刷新数据的原因。然后就会 self.mainTableView.contentOffset = CGPointZero; 偏移到最顶端，而不是想要的停留在当前滑动位置。 如果单独写一个属性方法或者属性，去控制刷新的时候要不要偏移到最顶端，会不会好点。

**Comment by pujiaxin33** [comment]
第一个：pagerView的reloadData方法就是会导致置顶，相当于重新构建页面。
第二个：如果你只是列表数据不确定，刷新你的列表即可。

**Comment by weizhangCoder** [comment]
> 第一个：pagerView的reloadData方法就是会导致置顶，相当于重新构建页面。
> 第二个：如果你只是列表数据不确定，刷新你的列表即可。

我这个有各种角色切换。刷新可能categoryView 上的个数要发生变化，然后JXPagerView里面的高度和内容也可能会发生变化，所以我就干脆每次进入以后 都刷新了一下。
 [self.categoryView reloadDataWithoutListContainer];
 [self.pagerView reloadData];
不过iOS 13 是没有问题的。只有iOS12 会有这样的问题
然后我就尝试改了下,虽然可以改好，但怕对别的有影响，没有完全了解你的代码。然后不敢用
（这块，就是加了一个判断，判断偏移量，超过自己头视图的高度了，才让它走入这个方法，楼主看看会不会有问题）
<img width="1117" alt="image" src="https://user-images.githubusercontent.com/11644326/87653956-dc140280-c788-11ea-9a6b-ae972c34eea3.png">

现在我还没有敢更新2.0.7 版本。

**Comment by pujiaxin33** [comment]
你参考【reloadData无需重新创建列表】示例，只是代码：
```
    [self.categoryView reloadDataWithoutListContainer];
    [self.pagerView reloadData];
```
修改为：
```
[self.categoryView reloadData];
```
试一试呢

你发的截图里面的修改，应该是有潜在问题的。

**Comment by pujiaxin33** [comment]
实在解决不了，发一个简单的demo给我，我看具体情况分析了。

**Comment by weizhangCoder** [comment]
> 实在解决不了，发一个简单的demo给我，我看具体情况分析了。

感谢，感谢。这个问题目前也就iOS13 以下有  。 demo我还是拿你的代码稍微修改了一下。就在这个回复的上面第二条。就是我截图的位置。版本是2.0.6 的。
<img width="899" alt="image" src="https://user-images.githubusercontent.com/11644326/87745219-edf4b480-c81f-11ea-8bfc-d5e2d1641e42.png">

复现步骤，在导航栏隐藏列表，点击进去，滑动偏移量大于64 后，然后点击cell，进入下个控制器，然后返回后，就会向上偏移self.pinSectionHeaderVerticalOffset的距离。

然后我看到一个issue,觉得和我这个比较像。https://github.com/pujiaxin33/JXCategoryView/issues/281

**Comment by pujiaxin33** [comment]
已修复，`[self.pagerView reloadData]`调用之后，就会重置整个页面。
