### ISSUE TITLE
列表下拉刷新TableView替换成CollectionView,HeaderView向上便宜问题

### ISSUE THREAD

**Issue by gsd6660** [pujiaxin33/JXPagingView#247]
**bug提交前阅读**
 

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：2.0.7
2.OC还是Swift版本：OC
3.手机系统版本号：13.5
4.手机型号：

问题如图：
![bug](https://user-images.githubusercontent.com/12539471/87498641-dcc66f00-c68a-11ea-8e06-804255c19c0e.gif)

**Comment by pujiaxin33** [comment]
自测没有问题，你需要添加下面的代码，请认真参考文档：
```Objective-C
- (void)listViewDidScrollCallback:(void (^)(UIScrollView *scrollView))callback {
    self.scrollCallback = callback;
}
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    !self.scrollCallback ?: self.scrollCallback(scrollView);
}
```
