### ISSUE TITLE
segmentedView、pagingView默认选中第二个时，点击segmentedView中的第一个时页面无法响应

### ISSUE THREAD

**Issue by jiejianyou** [pujiaxin33/JXPagingView#249]
**bug描述**
当segmentedView、pagingView设置了默认选中第二个时，点击segmentedView中的第一个时页面无法响应，滚动到时第一个页时，是有成功响应的，设置默认选中第三个时，是没有问题的

**版本号**
1.JXPagingView版本号：2.0.8
2.OC还是Swift版本：Swfit
3.手机系统版本号：13.6
4.手机型号：模拟器

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：使用的是最新下载的demo 在BaseViewController中修改默认选中操作
segmentedView.defaultSelectedIndex = 1
pagingView.defaultSelectedIndex = 1

**截图、GIF**
提供bug出现时的截图或者GIF。
![QQ20200717-185204-HD](https://user-images.githubusercontent.com/19336708/87779212-0637f400-c85f-11ea-9b0b-31698729a680.gif)

**Comment by jiejianyou** [comment]
![image](https://user-images.githubusercontent.com/19336708/87779350-3d0e0a00-c85f-11ea-9c8c-2a9de3fe736a.png)

**Comment by jiejianyou** [comment]
![image](https://user-images.githubusercontent.com/19336708/87779419-53b46100-c85f-11ea-9ad2-251f55dac26f.png)

**Comment by jiejianyou** [comment]
@pujiaxin33

**Comment by pujiaxin33** [comment]
感谢反馈，已经修复，预计今天会出一个2.0.9
