### ISSUE TITLE
JXCategoryTitleView 宽度设置没有任何作用。

### ISSUE THREAD

**Issue by zhangqi02060227m** [pujiaxin33/JXPagingView#25]
_categoryView = [[JXCategoryTitleView alloc] initWithFrame:CGRectMake(0, 0, 100, JXheightForHeaderInSection)];
我把_categoryView 的宽度设为100，结果还是屏幕的宽。。

**Comment by zhangqi02060227m** [comment]
但是我想要自定义设置，我肯定想要每一部分都能单独控制。。。。
就像这种效果。。。
![1](https://user-images.githubusercontent.com/16876013/48330375-612b4800-e687-11e8-940d-e1bfd1ab1166.PNG)

**Comment by pujiaxin33** [comment]
你可以直接通过配置categoryView
1、averageCellSpacingEnabled设置为NO
2、自己再调整下cellSpacing就可以了

**Comment by zhangqi02060227m** [comment]
好的，我刚刚没找到这个属性。。。。谢啦。。。
