### ISSUE TITLE
resizeTableHeaderViewHeightWithAnimatable 带动画时，当TableHeader的高度大于pagerView的高度，下面pagerView的cell会触发重用，在动画过程中，cell上的view会消失

### ISSUE THREAD

**Issue by anyanf** [pujiaxin33/JXPagingView#250]
**bug描述**
resizeTableHeaderViewHeightWithAnimatable 带动画时，当TableHeader的高度大于pagerView的高度，下面pagerView的cell会触发重用，在动画过程中，cell上的view会消失
**版本号**
1.JXPagingView版本号：1.5.5
2.OC还是Swift版本：OC
3.手机系统版本号：iOS13.5.1
4.手机型号：XS max

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagerView
2.具体的操作步骤是：header先是高度小于pagerView的高度，点击某按钮后，执行动画，改变header的高度。
当TableHeader的高度大于pagerView的高度，下面pagerView的cell会触发重用，在动画过程中，cell上的view会消失。

**截图、GIF**
[视频链接](http://qdnokqr7y.bkt.clouddn.com/RPReplay_Final1595060049.MP4)

**Comment by pujiaxin33** [comment]
经过多次试验，无法解决。系统判定UITableView的cell无需显示，就直接移除了，没有动画过渡过程。

**Comment by anyanf** [comment]
> 经过多次试验，无法解决。系统判定UITableView的cell无需显示，就直接移除了，没有动画过渡过程。

嗯嗯。。我现在的解决方案是不让下面那个cell触发重用。。也就是加大pagerview的高度。。总感觉很low。。

**Comment by pujiaxin33** [comment]
那就只有按照你的现有方案解决了。
