### ISSUE TITLE
类似于WMPageController的效果

### ISSUE THREAD

**Issue by lilin87788** [pujiaxin33/JXPagingView#251]
**Feature描述**
请简单描述你想要的效果：类似于WMPageController,我不想要tableHeaderViewInPagerView 这个里面的tableHeaderView,怎么支持的，我目前就是tableHeaderViewHeightInPagerView返回高度为0，tableHeaderViewInPagerView这个代理返回[UIView new],但是哪个segmentView并不是固定在顶部的 

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：参考：WMPageController 这个开源代码，我以前用的这个，目前已经停更，想切换到你的这个框架下面来
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
你看下readme的说明：
JXCategoryView、JXSegmentedView
悬浮的HeaderView，用的是我写的：OC版本-JXCategoryView 、Swift版本-JXSegmentedView。几乎实现了所有主流效果，而且非常容易自定义扩展，强烈推荐阅读。
