### ISSUE TITLE
pinSectionHeaderVerticalOffset和JXTableHeaderViewHeight相等的时候，页面无法联动

### ISSUE THREAD

**Issue by PZXforXcode** [pujiaxin33/JXPagingView#252]
**bug描述**
使用最新版的demo，进入PagingViewController，设置:self.pagerView.pinSectionHeaderVerticalOffset = JXTableHeaderViewHeight;
刷新的tableview和次级页面tableview联动消失下拉刷新要拉多次

**版本号**
1.JXPagingView版本号：2.0.8
2.OC还是Swift版本：OC
3.手机系统版本号：13.1
4.手机型号：iPhoneX

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by PZXforXcode** [comment]
@pujiaxin33 大神可以看看吗

**Comment by PZXforXcode** [comment]
效果
![滑动效果](https://user-images.githubusercontent.com/17844055/88002937-471d5a80-cb36-11ea-9235-f4dfb1f7b277.gif)

**Comment by pujiaxin33** [comment]
你一步一步描述一下你的复现步骤

**Comment by PZXforXcode** [comment]
> 你一步一步描述一下你的复现步骤

1.进入demo  
2.选择悬浮sectionHeader位置动态调整那个模块
3.点击右上角切换按钮
4.向下滑动，然后向上滑动，惯性不会带到maintableview

**Comment by pujiaxin33** [comment]
pinSectionHeaderVerticalOffset和JXTableHeaderViewHeight本身就会让header固定，你再理解一下pinSectionHeaderVerticalOffset的作用。
