### ISSUE TITLE
2.0.9 与自定义navi三方右滑冲突

### ISSUE THREAD

**Issue by wyk190576528** [pujiaxin33/JXPagingView#253]
示例demo如下：
[page_demo.zip](https://github.com/pujiaxin33/JXPagingView/files/4951991/page_demo.zip)

**Comment by wyk190576528** [comment]
1.x的版本不冲突

**Comment by pujiaxin33** [comment]
你能仔细描述一下冲突的现象吗？

**Comment by wyk190576528** [comment]
现已解决，通过修改的navi三方库
