### ISSUE TITLE
JXPagerSmoothView  reloadData  刷新问题

### ISSUE THREAD

**Issue by homeYsy** [pujiaxin33/JXPagingView#254]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by homeYsy** [comment]
我想问下    pagerHeader.frame = CGRectMake(0, 0, self.bounds.size.width, self.heightForPagerHeader);
这个frame 的y为0的时候    有这样一个场景，我项目里有两个tabbar，在第一个tabbar刷新正常，跳转到第二个tabbar的页面，在第二个tabbar去通知执行JXPagerSmoothView reloadData，然后返回到第一个tabbar对应的页面，发现页面向上偏移了大概高度10的距离，如果我把这里的y改成10，返回回去看着是正常的。

1.JXPagingView版本号：2.0.8
2.OC还是Swift版本：OC
3.手机系统版本号：目前只在ios13以下发现这种情况
4.手机型号：6p

**Comment by pujiaxin33** [comment]
能麻烦你把demo修改一下，保证能复现问题，然后把zip压缩包发出来。这样我方便查找问题。
