### ISSUE TITLE
导航栏隐藏主页下拉刷新&列表上拉加载更多

### ISSUE THREAD

**Issue by 274737258** [pujiaxin33/JXPagingView#256]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
导航栏隐藏，主页下拉刷新&列表上拉加载更多的方式，随意滚动视图后多次下拉刷新，有时会出现刷新完毕contentOffset.y不为0随机为大于0的数，一般小于20。已经对比过demo没有发现有任何不一样，找不到问题原因。

**版本号**
1.JXPagingView版本号：？JXPagingView/Pager (2.0.1)
2.OC还是Swift版本：？oc
3.手机系统版本号：？13.3
4.手机型号：？iphone7

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？多次下拉刷新

**截图、GIF**
提供bug出现时的截图或者GIF。刷新完毕打印scrollView.contentOffset.y的值不为0

**Comment by pujiaxin33** [comment]
麻烦你用最新版本尝试一下，如果还有问题，麻烦提供复现问题的demo给我，把项目压缩成zip，贴出即可。

**Comment by 274737258** [comment]
更新最新版本后好了
