### ISSUE TITLE
SmoothListViewController tableview 为多个分组时 sectionview 错乱 

### ISSUE THREAD

**Issue by mayunhao910324** [pujiaxin33/JXPagingView#257]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
SmoothListViewController tableview 为多个分组时 sectionview 错乱 

**版本号**
1.JXPagingView版本号：最新demo
2.OC还是Swift版本：OC
3.手机系统版本号：？
4.手机型号：？

**复现步骤**

-(NSInteger)numberOfSectionsInTableView:(UITableView *)tableView{
    return 10;
}
-(CGFloat)tableView:(UITableView *)tableView heightForHeaderInSection:(NSInteger)section{
    return 30.0f;
}
SmoothListViewController.m中
![Simulator Screen Shot - iPhone 11 - 2020-07-24 at 14 51 26](https://user-images.githubusercontent.com/8474693/88367236-db4d2300-cdbd-11ea-9047-101575e3866a.png)

添加上述代码即可复现
**截图、GIF**

**Comment by pujiaxin33** [comment]
基于JXPagerSmoothView目前的原理，内部调整了UITableView的contentInset，用来添加headerView。调整了contentInset.top会影响到UITableViewStylePlain类型下sectionHeader的悬浮位置。所以，基于此，列表的UITableView无法使用UITableViewStylePlain类型。请使用UITableViewStyleGrouped类型。

**Comment by imzzcoder** [comment]
> 基于JXPagerSmoothView目前的原理，内部调整了UITableView的contentInset，用来添加headerView。调整了contentInset.top会影响到UITableViewStylePlain类型下sectionHeader的悬浮位置。所以，基于此，列表的UITableView无法使用UITableViewStylePlain类型。请使用UITableViewStyleGrouped类型。

如果需要分组组头漂浮，要怎么处理呢

**Comment by imzzcoder** [comment]
@pujiaxin33

**Comment by imzzcoder** [comment]
@pujiaxin33  如果需要分组组头漂浮，要怎么处理呢

**Comment by pujiaxin33** [comment]
@imzzcoder 请使用JXPagerView，而不要使用JXSmoothView

**Comment by imzzcoder** [comment]
@pujiaxin33 好的，我自己做了两个view，在组头消失时把另一个view加到父view上，交替显示
