### ISSUE TITLE
pinSectionHeaderVerticalOffset 大于0，滑回顶部时列表contentOffset错误

### ISSUE THREAD

**Issue by alexsun** [pujiaxin33/JXPagingView#258]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
JXPagingView 的 pinSectionHeaderVerticalOffset 大于 0 的时候，
先往上滑动到头部视图不可见后，在往下滑动到顶部，列表contentOffset错误，然后列表会跳动一下恢复到正确的位置

**版本号**
1.JXPagingView版本号：2.0.9
2.OC还是Swift版本：swift
3.手机系统版本号：iOS 13.5
4.手机型号：iPhone 7

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagingView
2.具体的操作步骤是：如上bug描述

**截图、GIF**
![NZSN2302](https://user-images.githubusercontent.com/3223713/88377672-2c671200-cdd2-11ea-9a90-7e63ef54244d.gif)

**Comment by pujiaxin33** [comment]
感谢反馈，已修复，预计2.0.10发布。
