### ISSUE TITLE
JXPagingView 中 listDidAppear listDidDisappear 回调错误

### ISSUE THREAD

**Issue by shannonchou** [pujiaxin33/JXPagingView#259]
**bug描述**
横向划动到最后一个listView 后，listDidAppear listDidDisappear 回调不符合预期，通过顶部点击 JXSegmentedView 切换过去没有问题。
比如从index 6 划动到 index 7 的 listview 后，6 收到了 listDidAppear 回调，7 收到了 listDidDisappear 回调。预期是7 收到 listDidAppear 回调，6 收到 listDidDisappear 回调

**版本号**
1.JXPagingView版本号：2.0.10
2.OC还是Swift版本：swift
3.手机系统版本号：11.4.1
4.手机型号：se

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagingListContainerView  JXPagingViewListViewDelegate
2.具体的操作步骤是：划动到最后一个 listview

**Comment by pujiaxin33** [comment]
最新版本并没有该问题。
