### ISSUE TITLE
自定义悬浮HeaderView的问题

### ISSUE THREAD

**Issue by mxpasser** [pujiaxin33/JXPagingView#26]
@pujiaxin33 你好，先感谢你的这个库，写的挺好。。然后请教你个问题哈，就是我自定义了一个悬浮headerview，上面有2个按钮，我在切换俩按钮的时候怎么触发下面listview的切换，或者切换下面的listview怎么选中headerview上的某个按钮？谢谢！

**Comment by pujiaxin33** [comment]
你的headerView，没有使用JXCategoryView，而是自己定义的两个button？
如果是这样子的话：
1、点击button，就根据点击的哪一个button，控制pagerView.listContainerView.collectionView.contentOffset.x
2、KVO pagerView.listContainerView.collectionView.contentOffset，根据x的值，判断当前是那一页，再刷新button的显示

**Comment by mxpasser** [comment]
嗯，非常感谢你的回复哈。。本来打算用JXCategoryView这个的，但是给的需求很蛋疼，header上不仅有分类切换还有筛选，然后categoryView这个好像不能完全自定义高度和indicator的位置，就自定义了一个headerview。。。😅
![image](https://user-images.githubusercontent.com/3272620/48389186-4d3f1f00-e737-11e8-8ff3-b236d0a94f82.png)

**Comment by mxpasser** [comment]
感谢回复哈~~
嗯，是的。。上午刚问完你，然后突然想到haderview上add JXCategoryView和其他的view就可以了。。😅
