### ISSUE TITLE
刷新时categoryView的title个数由一个改为多个，刷新后新页面不会显示

### ISSUE THREAD

**Issue by 274737258** [pujiaxin33/JXPagingView#260]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？2.0.11
2.OC还是Swift版本：？oc
3.手机系统版本号：？ios13
4.手机型号：？iPhone7

**复现步骤**
1. 遇到问题的相关效果、类是：？刷新时categoryView的title个数由一个改为多个，刷新后新页面不会显示
2.具体的操作步骤是：？把你的demo代码PagingViewController中_titles 改为一个，即_titles = @[@"能力"]; 然后在RefreshViewController控制器下拉刷新，刷新block设置self.categoryView.titles = @[@"高级能力", @"高级爱好", @"高级队友"]，self.categoryView.defaultSelectedIndex = 1;这个时候_titles变为三个，但是下面的内容为空白。

**截图、GIF**
提供bug出现时的截图或者GIF。
![WechatIMG49](https://user-images.githubusercontent.com/4277464/88527978-92e96b80-d030-11ea-8bcc-ca1773eaadaf.jpeg)

**Comment by 274737258** [comment]
[JXPagingView-master 2.zip](https://github.com/pujiaxin33/JXPagingView/files/4981255/JXPagingView-master.2.zip)

**Comment by pujiaxin33** [comment]
感谢反馈，已修复，你用最新的demo测试一下呢？

**Comment by 274737258** [comment]
> 感谢反馈，已修复，你用最新的demo测试一下呢？

可以了

**Comment by pujiaxin33** [comment]
最新2.0.12已发布
