### ISSUE TITLE
刚刚更新了最新的版本之后,点击某个titleview,相应的页面空白,滑动则不会

### ISSUE THREAD

**Issue by crazypoo** [pujiaxin33/JXPagingView#261]
版本号
1.JXPagingView版本号：2.0.12
2.OC还是Swift版本：swift
3.手机系统版本号：?
4.手机型号：?

bug
刚刚更新了最新的版本之后,点击某个titleview,相应的页面空白,滑动则不会

**Comment by pujiaxin33** [comment]
请参考demo的配置代码。
