### ISSUE TITLE
swift版本与oc版本差异，导致bug

### ISSUE THREAD

**Issue by gongqiuwei** [pujiaxin33/JXPagingView#262]
jxpaginview中的函数 preferredProcessListViewDidScroll , 参数传入的scrollView和 属性currentScrollingListView，并不是同一个scrollView，在oc版本这个函数直接使用传入的scrollview，而swift版本中，使用currentScrollingListView。会导致当前list中的scrollView上下滑动的时候出现contentOffset突变
![20200730170707](https://user-images.githubusercontent.com/3827831/88904737-09cc7180-d288-11ea-9506-2ade7752257b.jpg)
![20200730170917](https://user-images.githubusercontent.com/3827831/88904751-105ae900-d288-11ea-9347-2368922af656.jpg)

**Comment by gongqiuwei** [comment]
在swift中，仿照oc的demo做PagingNestCategoryViewController 发现的问题

**Comment by gongqiuwei** [comment]
使用swift版本，仿照oc的demo中的PagingNestCategoryViewController需求发现的问题

**Comment by gongqiuwei** [comment]
目前更改了swift源码， 在func preferredProcessListViewDidScroll(scrollView: UIScrollView) 中第一行 增加 currentScrollingListView = scrollView， 然后仿照oc的demo的PagingNestCategoryViewController，可以做到和oc效果一致

**Comment by pujiaxin33** [comment]
感谢反馈，swift版本已统一为oc版本代码
