### ISSUE TITLE
左右列表切换如果改变pagerView的高度，上下滚动后在切换左右列表出现列表跳动

### ISSUE THREAD

**Issue by JohnJin007** [pujiaxin33/JXPagingView#266]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
请参考调整tableHeaderView高度示例。如果是使用最新版本还有问题，请提供可以复现问题的demo，以便分析具体问题。

**Comment by JohnJin007** [comment]
可以在切换子列表时改变pagerView的高度吗？比如我的第一个子列表叫A，第二个叫B，最开始pagerView和self.view是相等的，当我从A切换到B，我想改变pagerView的大小，比如切换到B时，pagerView的大小距离self.view的底部50px，复现步骤：当我设置好之后，进入页面，首先展示的是子列表A，然后向上滑动整个列表，headerView在顶部悬停，左滑切换到子列表B时，整个列表跳动，headerView也不在顶部悬停，向下偏移。
