### ISSUE TITLE
列表数量如果特别多，内存增长过大照成闪退

### ISSUE THREAD

**Issue by Limghi** [pujiaxin33/JXPagingView#268]
OC   列表数量如果特别多，内存增长过大照成闪退，

**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by Limghi** [comment]
OC 列表数量如果特别多，内存增长过大照成闪退，希望能设置最多允许几个控制器存活，超过了，杀死之前控制器

**Comment by pujiaxin33** [comment]
请选用collection类型的列表容器，你可以自己查看内存监控

**Comment by Limghi** [comment]
collection类型的列表容器，如果列表特别多，内存消耗过大，会杀死之前的控制器吗

**Comment by pujiaxin33** [comment]
collection类型的列表容器的优势相对于UIScrollView，视图不会一直被添加到视图上面。所以占用的内存会更少。你先自测一下嘛

**Comment by Limghi** [comment]
我这边自测了呢，如果界面复杂，控制器又特别多，还是会造成内存增长较多的，可不可以加个属性控制最多允许加载做少个控制器，超过数量，把最先进入的控制器释放掉，，，，，我看今日头条首页好像有这个操作

**Comment by 17554265585** [comment]
滚动延续的实现方式头部区域的内容无法回收，如果头部比较长，内存也成问题
