### ISSUE TITLE
JXPagerSmoothView的Demo中，设置contentScrollViewClickTransitionAnimationEnabled=YES，头部会闪

### ISSUE THREAD

**Issue by LivyNN** [pujiaxin33/JXPagingView#271]
![Aug-11-2020 11-18-19](https://user-images.githubusercontent.com/37862043/89853648-79b1f480-dbc4-11ea-92b9-a0269b845846.gif)

应该是滚动的时候不断添加headerView有关，但这些addSubview应该都是必要

**Comment by pujiaxin33** [comment]
感谢反馈，最新版本demo已修复，麻烦下载验证一下。
