### ISSUE TITLE
关于JXPagerSmoothView 

### ISSUE THREAD

**Issue by json29266** [pujiaxin33/JXPagingView#272]
**Feature描述**
请简单描述你想要的效果：？
JXPagerSmoothView
作者您好，您的库写的非常好，我看最近也更新了JXPagerSmoothView这个类，我有一个小建议，如果JXPagerSmoothView这个类也能支持
/**
 顶部固定sectionHeader的垂直偏移量。数值越大越往下沉。
 */
@property (nonatomic, assign) NSInteger pinSectionHeaderVerticalOffset;
这个属性那就完美了，因为有些情况下我们的navbar是透明的哈

**Comment by 17554265585** [comment]
目前的实现方式在内存方面不友好，头部内容无法回收，如果是采用两个UICollectionView嵌套的方式会好很多

**Comment by pujiaxin33** [comment]
@json29266 暂不支持

**Comment by douxindong** [comment]
@17554265585 同意

**Comment by sizhugongzi** [comment]
> **Feature描述**
> 请简单描述你想要的效果：？
> JXPagerSmoothView
> 作者您好，您的库写的非常好，我看最近也更新了JXPagerSmoothView这个类，我有一个小建议，如果JXPagerSmoothView这个类也能支持
> /**
> 顶部固定sectionHeader的垂直偏移量。数值越大越往下沉。
> */
> @Property (nonatomic, assign) NSInteger pinSectionHeaderVerticalOffset;
> 这个属性那就完美了，因为有些情况下我们的navbar是透明的哈

你好,有实现吗?

**Comment by douxindong** [comment]
Thank you. Your email is received and will be handled as soon as possible.
