### ISSUE TITLE
JXPagingView版本号：2.0.6和2.0.12,使用 JXPagingSmoothView遇到的问题

### ISSUE THREAD

**Issue by HXShuai** [pujiaxin33/JXPagingView#274]
bug描述

使用JXPagingSmoothView实现类似Demo里面的“滚动延续”功能，区别在于SmoothListViewController里是一个瀑布流CollectionView，在ViewDidLoad里实例化collectionview和加载网络数据。在上拉滑动一定距离前，左右滑动或者点击切换没有问题，当上拉一段距离后，向右滑动去显示一个没有显示过得界面。就会闪退报错could not execute support code to read Objective-C class data in the process. This may reduce the quality of type information available.

版本号
1.JXPagingView版本号：2.0.6

2.OC还是Swift版本:swift

3.手机系统版本号：13.5.1

4.手机型号：XR

复现步骤

遇到问题的相关效果、类是：JXPagingSmoothView

具体的操作步骤是：SmoothListViewController里面是一个瀑布流collectionView，在ViewDidLoad里面加载数据然后reload CollectionView
![bug截图](https://user-images.githubusercontent.com/16444115/90388412-51d9f980-e0ba-11ea-8754-6333e12ae13f.jpg)

**Comment by HXShuai** [comment]
bug描述

更新JXPagingView的版本后，上面的情况没有出现了，但是出现了header闪现情况。

版本号
1.JXPagingView版本号：2.0.12

2.OC还是Swift版本:swift

3.手机系统版本号：13.5.1

4.手机型号：XR

复现步骤

遇到问题的相关效果、类是：JXPagingSmoothView
录屏做了一个gif。



![gif2](https://user-images.githubusercontent.com/16444115/90576105-c06ca380-e1ef-11ea-85e2-8abaa6e40548.gif)

**Comment by pujiaxin33** [comment]
@HXShuai 更新JXPagingView的版本后，上面的情况没有出现了，但是出现了header闪现情况。这个可以用demo复现吗

**Comment by hongfenglt** [comment]
同样遇到这个问题。
OC版本20.0.13
