### ISSUE TITLE
JXPagingView  怎么支持RTL镜像布局

### ISSUE THREAD

**Issue by XX-chu** [pujiaxin33/JXPagingView#275]
**Feature描述**
请简单描述你想要的效果：怎么才能跟JXCategoryView配合实现RTL镜像布局，目前JXCategoryView可以实现镜像布局，但是
JXPagingView在镜像情况下，页面回加载不出来
**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
JXPagingView暂不支持RTL，你可以参考JXCategoryView里的RTL代码，给JXPagingView提交一个PR

**Comment by Lifei0229** [comment]
解决JXPagingView 在RTL下会出现空白页面。 JXCategoryView 和JXPagingView搭配使用 RTL的适配 
if (@available(iOS 10.0, *)) {
            self.collectionView.prefetchingEnabled = NO;
        }
        if (@available(iOS 11.0, *)) {
            self.collectionView.contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever;
        }

JXPagerListContainerView.m 190行下面加上 下面的代码
        
        if (isRTL()){
            if (@available(iOS 9.0, *)) {
                self.collectionView.semanticContentAttribute = UISemanticContentAttributeForceLeftToRight;
            } else {
                // Fallback on earlier versions
            }
        }

#define isRTL() [[[[NSBundle mainBundle] preferredLocalizations] firstObject] hasPrefix:@"ar"]

**Comment by pujiaxin33** [comment]
已被 https://github.com/pujiaxin33/JXPagingView/pull/515 支持了RTL
