### ISSUE TITLE
设置pinSectionHeaderVerticalOffset为负数所带来的问题

### ISSUE THREAD

**Issue by 979881765** [pujiaxin33/JXPagingView#279]
设置为负数之后，子列表UICollectionVIew中有固定头部（headerView），会发现滑动到顶部headerView固定之后，segmentView偶尔有闪出情况

**Comment by pujiaxin33** [comment]
设计之初并没有考虑负数的情况，为什么会设置负数呢？

**Comment by 979881765** [comment]
我的目的是为了让子列表的sectionView固定到顶部，不让segmentView固定，所以设置了负数

**Comment by CocoaKier** [comment]
> 设计之初并没有考虑负数的情况，为什么会设置负数呢？
为了让sectionHeader不悬浮，而是跟着tableView滚动，类似tableView .group 的效果。

我也遇到了这个问题，我把偏移设置成sectionHeader等高的负值，达到隐藏sectionHeader的目的。虽然可以达到不悬浮的目的，但是滚动下拉的过程中会闪出
`pagingView.pinSectionHeaderVerticalOffset = -JXheightForHeaderInSection`

**Comment by CocoaKier** [comment]
为了让sectionHeader不悬浮，而是跟着tableView滚动，类似tableView .group 的效果。

我也遇到了这个问题，我把偏移设置成sectionHeader等高的负值，达到隐藏sectionHeader的目的。虽然可以达到不悬浮的目的，但是滚动下拉的过程中会闪出
pagingView.pinSectionHeaderVerticalOffset = -JXheightForHeaderInSection

**Comment by nick5683** [comment]
这个问题怎么解决呢，我也遇到了相同的问题，请教一下

**Comment by nick5683** [comment]
scrollViewDidScroll  方法中， 修改原判断条件为               
  let offset = fabs(Double(pinSectionHeaderVerticalOffset))
                if scrollView.contentOffset.y >= CGFloat(offset) { }
           可解决这个问题，可以试试
