### ISSUE TITLE
下拉刷新设置头部偏移显示错误

### ISSUE THREAD

**Issue by luo-h** [pujiaxin33/JXPagingView#280]
**bug描述**
用一个禁止滑动的collectionView做pagerView的header，并添加顶部下拉刷新，设置self.pagerView.mainTableView.mj_insetT = 50;pagerView的maintableView不会默认显示出mj的头部，可通过手动下拉50显露出mj的头部，并且配合pinSectionHeaderVerticalOffset使用时categoryView偏移错误、抖动。
在demo中当header是一张图片是没有此问题，只有header是一个列表的时候才有

**版本号**
1.JXPagingView版本号：2.0.12
2.OC还是Swift版本：OC
3.手机系统版本号：11+
4.手机型号：所有iPhone

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagerView

**Comment by pujiaxin33** [comment]
可以提供一个能复现问题的demo吗

**Comment by luo-h** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
