### ISSUE TITLE
设置了 pinSectionHeaderVerticalOffset 后 刷新结束 立即回弹 不会有动画

### ISSUE THREAD

**Issue by jiejianyou** [pujiaxin33/JXPagingView#282]
**bug描述**
在demo中的 RefreshViewController 设置 pinSectionHeaderVerticalOffset 后 下拉刷新结束 会立即回弹 不会有动画  不设置就正常

**版本号**
1.JXPagingView版本号：2.0.12
2.OC还是Swift版本：OC
3.手机系统版本号：模拟器 13.7
4.手机型号：模拟器 iPhone 11 Pro Max

**复现步骤**
1. 遇到问题的相关效果、类是：RefreshViewController
2.具体的操作步骤是：在 viewDidLoad 中设置 self.pagerView.pinSectionHeaderVerticalOffset = 100.0;

**截图、GIF**

**Comment by weizhangCoder** [comment]
bug描述
在demo中的 RefreshViewController 设置 pinSectionHeaderVerticalOffset 后 下拉刷新结束 会立即回弹 不会有动画 不设置就正常

版本号
1.JXPagingView版本号：2.0.13
2.OC还是Swift版本：OC
3.手机系统版本号：模拟器 14.3
4.手机型号：模拟器 iPhone 11 Pro Max

我也出现了这个问题，隐藏RefreshViewController里面的导航栏。这个时候视图整体向上偏移，所以设置了self.pagerView.pinSectionHeaderVerticalOffset = 导航栏高度，这个时候就 [self.pagerView reloadData];     里面瞬间把偏移量变为0了。没有了动画，你解决了吗？
@pujiaxin33  大佬这个有办法解决吗？

**Comment by pujiaxin33** [comment]
#316 一并修复了
