### ISSUE TITLE
屏幕旋转后、视图偏移问题

### ISSUE THREAD

**Issue by EntityGJ** [pujiaxin33/JXPagingView#285]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。
我的个人列表页 使用JXPagerView、 点击某个item进入详情页 播放视频、 然后 旋转手机、 让视频横屏播放、###重点： 此时下拉系统状态栏 、  pop退出详情页、返回  个人列表页、  会出现 cell的contentView 的Frame的x 偏移44的问题

**版本号**
1.JXPagingView版本号：2.0.6
2.OC还是Swift版本：OC
3.手机系统版本号：13.5.1
4.手机型号：Xr

**复现步骤**
1. 遇到问题的相关效果、类是：承装JXPagerView的 
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。
<img width="1393" alt="WechatIMG3141" src="https://user-images.githubusercontent.com/16132160/92985507-d23b2100-f4e5-11ea-9f10-1627096f3dc2.png">

**Comment by pujiaxin33** [comment]
可以方便录个视频吗？未能复现出来。

**Comment by wstcwc** [comment]
遇到了同样的问题, 横竖屏切换后 视图向右边偏移

**Comment by pujiaxin33** [comment]
我试了一下，只要是UITableView，对于iPhoneX刘海屏，系统会自己在横屏情况添加额外的leading inset，目前还没有找到相关api可以修正。

**Comment by wstcwc** [comment]
我将listContainerView 从添加到cell.contentView 改为添加到cell上之后这个问题就解决了


> 我试了一下，只要是UITableView，对于iPhoneX刘海屏，系统会自己在横屏情况添加额外的leading inset，目前还没有找到相关api可以修正。

![testImage](https://user-images.githubusercontent.com/11764325/117523286-9a3f9b80-afea-11eb-94d5-c2b807471cdc.png)

**Comment by pujiaxin33** [comment]
@wstcwc 可以临时用你的方案解决，你就在你fork的分支修改。但是我记得直接用cell.bounds，某些情况会有点问题，现在想不起来具体场景了。所以，暂时无法在本库采取你的方案。

**Comment by ashuang521** [comment]
tableView.insetsContentViewsToSafeArea = NO;可以解决

**Comment by pujiaxin33** [comment]
> tableView.insetsContentViewsToSafeArea = NO;可以解决

大家可以使用该API设置列表的tableView
