### ISSUE TITLE
JXCategoryTitleView布局可以独立出来吗？

### ISSUE THREAD

**Issue by programmerElephant** [pujiaxin33/JXPagingView#288]
请问一下，我不想吧JXCategoryTitleView作为headerview，
我想吧JXCategoryTitleView独立放到其他地方，比如navigationbar中的titleview，请问有什么方法可以做到吗

**Comment by pujiaxin33** [comment]
你参考一下JXCategoryView库的demo，里面有布局到navigationbar中的titleview的示例

**Comment by programmerElephant** [comment]
好的，谢谢
