### ISSUE TITLE
headerview是个tableview，有的cell中嵌套了横向滚动的collectionview，左右滚动时怎么不上下滚动？

### ISSUE THREAD

**Issue by slash130** [pujiaxin33/JXPagingView#289]
**Feature描述**
我的VC是参照swift的CategoryView制作的，VC的头部view是个tableview，里面有的cell是内嵌了横向滚动的collectionview，在横向滚动的时候想不去响应上下滚动。我看了几个跟我有类似情况的Issues知道应该是在NestSubjectViewController里面修改mainTableViewGestureRecognizer方法，把不想响应上下滚动的pan手势加入false的判断里，但是这种tableviewcell里的collectionview的pan手势我该怎么去判断呢？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
就是把 
> 这种tableviewcell里的collectionview的pan手势
> 把不想响应上下滚动的pan手势加入false的判断里

**Comment by slash130** [comment]
@pujiaxin33 恕我比较菜，不知道那个if判断里tableviewcell的collectionview的pan手势的条件该怎么写。

**Comment by slash130** [comment]
问题解决，用 otherGestureRecognizer.view?.className() == "UICollectionView" 做了判断。不知道这样弄会不会影响别的地方

**Comment by my-lsk** [comment]
> 问题解决，用 otherGestureRecognizer.view?.className() == "UICollectionView" 做了判断。不知道这样弄会不会影响别的地方

你这是swift吗，我现在的情况和你一样，不知道如何解决

**Comment by chengongwen** [comment]
func preferredPagingView() -> JXPagingView {
        // 悬浮高度
        let pagingView = JXPagingView(delegate: self)
        _### pagingView.mainTableView.gestureDelegate = self  // 设置代理_
        return pagingView
    }

//MARK: - JXPagingMainTableViewGestureDelegate
extension ProductDetailViewController: JXPagingMainTableViewGestureDelegate {
    func mainTableViewGestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        
        // 禁止paramScrollView左右滑动的时候，上下和左右都可以滚动
       ###  let paramScrollViewTag = "paramScrollView".hashValue
        if gestureRecognizer.view?.tag == paramScrollViewTag ||
            otherGestureRecognizer.view?.tag == paramScrollViewTag {
            return false
        }
        
        return gestureRecognizer.isKind(of: UIPanGestureRecognizer.self) && otherGestureRecognizer.isKind(of: UIPanGestureRecognizer.self)
    }
}
