### ISSUE TITLE
头图缩放和上下拉刷新能否同时实现？

### ISSUE THREAD

**Issue by chglog** [pujiaxin33/JXPagingView#29]
类似qq空间的那种效果

**Comment by pujiaxin33** [comment]
你应该是说的qq控件的动态tab的效果吧。
你认真分析一下他的刷新逻辑呢？
就是监听下拉到一定值的距离，松手就触发刷新，转一个系统的UIActivityIndicator（名字好像叫这个）。你自己都可以处理啊，跟我的实现原理没有任何冲突的地方。
就完全属于自己自定义添加一个效果而已

**Comment by chglog** [comment]
明白 感谢
