### ISSUE TITLE
JXPagingListRefreshView Swift代码能否和OC一样使用上automaticallyDisplayListVerticalScrollIndicator属性

### ISSUE THREAD

**Issue by Toorealistic** [pujiaxin33/JXPagingView#290]
OC版是有的，希望swift版也能加上

**Comment by Toorealistic** [comment]
<img width="810" alt="image" src="https://user-images.githubusercontent.com/15881558/94232474-a766b900-ff38-11ea-9ded-9e41510dfa1d.png">

**Comment by pujiaxin33** [comment]
希望你提一个PR

**Comment by Toorealistic** [comment]
OC:
- (void)preferredProcessListViewDidScroll:(UIScrollView *)scrollView {
    BOOL shouldProcess = YES;
    if (self.currentScrollingListView.contentOffset.y > self.lastScrollingListViewContentOffsetY) {
        //往上滚动
    }else {
        //往下滚动
        if (self.mainTableView.contentOffset.y == 0) {
            shouldProcess = NO;
        }else {
            if (self.mainTableView.contentOffset.y < self.mainTableViewMaxContentOffsetY) {
                //mainTableView的header还没有消失，让listScrollView一直为0
                if (self.currentList && [self.currentList respondsToSelector:@selector(listScrollViewWillResetContentOffset)]) {
                    [self.currentList listScrollViewWillResetContentOffset];
                }
                [self setListScrollViewToMinContentOffsetY:self.currentScrollingListView];
                **if (self.automaticallyDisplayListVerticalScrollIndicator) {
                    self.currentScrollingListView.showsVerticalScrollIndicator = NO;
                }**
            }
        }
    }
    if (shouldProcess) {
        if (self.mainTableView.contentOffset.y < self.mainTableViewMaxContentOffsetY) {
            //处于下拉刷新的状态，scrollView.contentOffset.y为负数，就重置为0
            if (self.currentScrollingListView.contentOffset.y > [self minContentOffsetYInListScrollView:self.currentScrollingListView]) {
                //mainTableView的header还没有消失，让listScrollView一直为0
                if (self.currentList && [self.currentList respondsToSelector:@selector(listScrollViewWillResetContentOffset)]) {
                    [self.currentList listScrollViewWillResetContentOffset];
                }
                [self setListScrollViewToMinContentOffsetY:self.currentScrollingListView];
                **if (self.automaticallyDisplayListVerticalScrollIndicator) {
                    self.currentScrollingListView.showsVerticalScrollIndicator = NO;
                }**
            }
        } else {
            //mainTableView的header刚好消失，固定mainTableView的位置，显示listScrollView的滚动条
            self.mainTableView.contentOffset = CGPointMake(0, self.mainTableViewMaxContentOffsetY);
            **if (self.automaticallyDisplayListVerticalScrollIndicator) {
                self.currentScrollingListView.showsVerticalScrollIndicator = YES;
            }**
        }
    }
    self.lastScrollingListViewContentOffsetY = self.currentScrollingListView.contentOffset.y;
}

Swift:
override open func preferredProcessListViewDidScroll(scrollView: UIScrollView) {
        guard let currentScrollingListView = currentScrollingListView else { return }
        var shouldProcess = true
        if currentScrollingListView.contentOffset.y > lastScrollingListViewContentOffsetY {
            //往上滚动
        }else {
            //往下滚动
            if mainTableView.contentOffset.y == 0 {
                shouldProcess = false
            }else {
                if (mainTableView.contentOffset.y < mainTableViewMaxContentOffsetY()) {
                    //mainTableView的header还没有消失，让listScrollView一直为0
                    setListScrollViewToMinContentOffsetY(currentScrollingListView)
                    **currentScrollingListView.showsVerticalScrollIndicator = false;**
                }
            }
        }
        if shouldProcess {
            if (mainTableView.contentOffset.y < mainTableViewMaxContentOffsetY()) {
                //处于下拉刷新的状态，scrollView.contentOffset.y为负数，就重置为0
                if currentScrollingListView.contentOffset.y > minContentOffsetYInListScrollView(currentScrollingListView) {
                    //mainTableView的header还没有消失，让listScrollView一直为0
                    setListScrollViewToMinContentOffsetY(currentScrollingListView)
                    **currentScrollingListView.showsVerticalScrollIndicator = false;**
                }
            } else {
                //mainTableView的header刚好消失，固定mainTableView的位置，显示listScrollView的滚动条
                setMainTableViewToMaxContentOffsetY()
                **currentScrollingListView.showsVerticalScrollIndicator = true;**
            }
        }
        lastScrollingListViewContentOffsetY = currentScrollingListView.contentOffset.y;
    }

@pujiaxin33  preferredProcessListViewDidScroll下swift版本遗落了automaticallyDisplayListVerticalScrollIndicator属性的使用

**Comment by Liyongcong** [comment]
swift这个问题还没修复
