### ISSUE TITLE
JXPagingView能否直接提供分页切换的代理回调

### ISSUE THREAD

**Issue by wbitos** [pujiaxin33/JXPagingView#291]
**Feature描述**
请简单描述你想要的效果：？
直接提供以下回调
public func pagingView(_ pagingView: JXPagingView, didShowListAtIndex index: Int)

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？
当分页比较多的时候（比如几万个）JXSegmentedView 有性能问题
直接用JXPagingView，分页指示又需要自己处理，我建议库本身能提供一个page指示器，并能处理好和JXSegmentedView配合时会有两个指示器的问题。（既希望自身加一个，又希望不和JXSegmentedView的重复）

**Comment by pujiaxin33** [comment]
> 当分页比较多的时候（比如几万个）JXSegmentedView 有性能问题
具体是什么性能问题呢？

**Comment by pujiaxin33** [comment]
JXPagingView视图结构设计，就是让分页指示器和paging交互逻辑解构的。不能让两者耦合在一起。

**Comment by Nododo** [comment]
目前也碰到类似的情况，就是使用自定义的 customCategoryView，在JXPagingView内容滚动的时候，希望通过代理方法，渲染自定义的customCategoryView。

demo中的customCategoryView，由于两个button没有颜色区分，所以忽略了这个问题。

如果owner 没有时间去实现，我近期内可以提一个pr

**Comment by Nododo** [comment]
目前通过观察者模式可以实现
    [RACObserve(_pagerView.listContainerView.scrollView, contentOffset) subscribeNext:^(id  _Nullable x) {
        CGFloat offset = MAX(0, [x CGPointValue].x);
        if (offset == 0 || offset == kScreenWidth) {
            NSInteger index = offset/ kScreenWidth;
            [self.titleView setCurrentIndex:index];
        }
}];
