### ISSUE TITLE
tableHeaderViewHeightInPagerView 头部视图高度可以动态调整

### ISSUE THREAD

**Issue by zwcshy** [pujiaxin33/JXPagingView#292]
`tableHeaderViewHeightInPagerView`  这个代理方法返回的头部视图高度可以动态调整吗？比如根据网络返回的数据动态改变

**Comment by pujiaxin33** [comment]
使用`- (void)resizeTableHeaderViewHeightWithAnimatable:(BOOL)animatable duration:(NSTimeInterval)duration curve:(UIViewAnimationCurve)curve;`api，再修改了高度之后，手动更新。请参考相关示例。

**Comment by zwcshy** [comment]
好的，我试试，谢谢
