### ISSUE TITLE
mj底部上拉加载数据后提示文字部分不回弹

### ISSUE THREAD

**Issue by slash130** [pujiaxin33/JXPagingView#299]
**bug描述**
底部tableview的mj上拉加载数据后mj那行提示文字部分不回弹

**版本号**
1.JXPagingView版本号：2.0.12
2.OC还是Swift版本：swift
3.手机系统版本号：14.0.1
4.手机型号：XR

**复现步骤**
1. 遇到问题的相关效果、类是：模仿demo里的ListViewController
2.具体的操作步骤是：上拉加载更多数据

**截图、GIF**

**Comment by pujiaxin33** [comment]
请使用MJRefreshBackNormalFooter
