### ISSUE TITLE
下面子控制器不是tableview,只是view可以吗

### ISSUE THREAD

**Issue by sushushu** [pujiaxin33/JXPagingView#3]

**Comment by pujiaxin33** [comment]
不可以，如果是view，需要把view内部的UIScrollView或者UITableView或者UICollectionView，实现JXPagingViewListViewDelegate协议方法。

**Comment by pujiaxin33** [comment]
更新了注释：这里要求返回一个UIView而不是一个UIScrollView，因为列表的UIScrollView一般是被包装到一个view里面，里面会处理数据源和其他逻辑。
