### ISSUE TITLE
JXCategoryTitleView 怎么根据网络请求的内容，动态的配置。。

### ISSUE THREAD

**Issue by zhangqi02060227m** [pujiaxin33/JXPagingView#30]
vc 一进来，我就加载 pageView，但是此时的 title 和 listArray 都没有值得。我想通过网络请求之后再刷新头部视图和 pageView。。 请问下怎么实现。。。

**Comment by pujiaxin33** [comment]
JXCategoryTitleView赋值titles，再调用它的reloadData；
pageView也是一样，更新数据之后，再调用它的reloadData；

**Comment by zhangqi02060227m** [comment]
好的。。。
