### ISSUE TITLE
把JXPagingListContainerView的collectionView设置为private，在使用的时候就不好控制了

### ISSUE THREAD

**Issue by chenshipeng** [pujiaxin33/JXPagingView#301]
把JXPagingListContainerView的collectionView设置为private，在使用的时候就不好控制了。
比如，我在没登录的时候滑动想控制不滑到下一个页面，collectionView设置为private就只能使用scrollView了

**Comment by pujiaxin33** [comment]
```
//让外部统一访问scrollView
scrollView = collectionView
```
scrollView就是对外的统一暴露
