### ISSUE TITLE
JXPagingView(delegate: self), delegate不释放 2.0.1版本

### ISSUE THREAD

**Issue by Miracle-Dove** [pujiaxin33/JXPagingView#303]
JXPagingView(delegate: self), delegate不释放 2.0.1版本

**Comment by TongRy** [comment]
我的也不释放，左右滑动不释放，内存居高不下，我是2.0.13

**Comment by Miracle-Dove** [comment]
> 我的也不释放，左右滑动不释放，内存居高不下，我是2.0.13

这是很严重的问题, 内存会越来越高, 耗电增高, 最后崩溃.

**Comment by TongRy** [comment]
> > 我的也不释放，左右滑动不释放，内存居高不下，我是2.0.13
> 
> 这是很严重的问题, 内存会越来越高, 耗电增高, 最后崩溃.

对呀，我现在就是内存很高，我的Category很多个，希望作者能看到解决一下

**Comment by pujiaxin33** [comment]
请问是特定系统才会出现的吗？可以用demo复现吗？我自测了一下没有发现泄漏问题。

**Comment by Miracle-Dove** [comment]
我的解决了, 是其中一个delegate的vc强引用了

**Comment by TongRy** [comment]
> 我的解决了, 是其中一个delegate的vc强引用了

哪里能强引用呀？

**Comment by Miracle-Dove** [comment]
我的是底下分为3个页面, 其中一个vc的子vc没有用weak 引用vc, 导致不能释放.

**Comment by TongRy** [comment]
> 我的是底下分为3个页面, 其中一个vc的子vc没有用weak 引用vc, 导致不能释放.
好吧，我们场景不一样，我是有很多个Category

**Comment by Miracle-Dove** [comment]
嗯, 楼主的代码应该是没问题的, 问题还是在我们自己代码.

**Comment by TongRy** [comment]
> 嗯, 楼主的代码应该是没问题的, 问题还是在我们自己代码.

嗯嗯，我换了种方式，自己处理了
