### ISSUE TITLE
JXPagingListRefreshView滚动条无法消失，设置automaticallyDisplayListVerticalScrollIndicator无效

### ISSUE THREAD

**Issue by ZhangDihan** [pujiaxin33/JXPagingView#308]
preferredProcessListViewDidScroll方法中没有判断automaticallyDisplayListVerticalScrollIndicator便直接设置了currentScrollingListView!.showsVerticalScrollIndicator = true

**Comment by zoloyy** [comment]
我这边也是希望没有滚动指示条，一直没有找到怎么去隐藏，每次指示条都显示出来了

**Comment by pujiaxin33** [comment]
将automaticallyDisplayListVerticalScrollIndicator设置为false，列表的showsVerticalScrollIndicator设置为false即可隐藏列表滚动条。

**Comment by TML007** [comment]
> 将automaticallyDisplayListVerticalScrollIndicator设置为false，列表的showsVerticalScrollIndicator设置为false即可隐藏列表滚动条。

还是没效果😂

**Comment by TML007** [comment]
> 将automaticallyDisplayListVerticalScrollIndicator设置为false，列表的showsVerticalScrollIndicator设置为false即可隐藏列表滚动条。

还是没效果，swift版

**Comment by Liyongcong** [comment]
> 将automaticallyDisplayListVerticalScrollIndicator设置为false，列表的showsVerticalScrollIndicator设置为false即可隐藏列表滚动条。
设置为NO，无效

**Comment by Liyongcong** [comment]
> 将automaticallyDisplayListVerticalScrollIndicator设置为false，列表的showsVerticalScrollIndicator设置为false即可隐藏列表滚动条。

在demo中试的，设置为No无效

**Comment by Junnor** [comment]
class DQPagingListRefreshView: JXPagingListRefreshView {

    /// pods 里面忘了设置，这里设置生效
    override func preferredProcessListViewDidScroll(scrollView: UIScrollView) {
        super.preferredProcessListViewDidScroll(scrollView: scrollView)
        
        currentScrollingListView?.showsVerticalScrollIndicator = automaticallyDisplayListVerticalScrollIndicator
    }
}

**Comment by Junnor** [comment]
class DQPagingListRefreshView: JXPagingListRefreshView {

    /// pods 里面忘了设置，这里设置生效
    override func preferredProcessListViewDidScroll(scrollView: UIScrollView) {
        super.preferredProcessListViewDidScroll(scrollView: scrollView)
        
        currentScrollingListView?.showsVerticalScrollIndicator = automaticallyDisplayListVerticalScrollIndicator
    }
}

**Comment by Junnor** [comment]
private lazy var pageContainer: DQPagingListRefreshView = {
    let view = DQPagingListRefreshView(delegate: self)
    view.automaticallyDisplayListVerticalScrollIndicator = false
    // ...
    // ...
    return view
}()

class DQPagingListRefreshView: JXPagingListRefreshView {

    /// pods 里面忘了设置，这里设置生效
    override func preferredProcessListViewDidScroll(scrollView: UIScrollView) {
        super.preferredProcessListViewDidScroll(scrollView: scrollView)
        
        currentScrollingListView?.showsVerticalScrollIndicator = automaticallyDisplayListVerticalScrollIndicator
    }
}

**Comment by Junnor** [comment]
class MyVC: UIViewController {
    private lazy var pageContainer: DQPagingListRefreshView = {
        let view = DQPagingListRefreshView(delegate: self)
        view.automaticallyDisplayListVerticalScrollIndicator = false
        // ...
        // ...
        return view
    }()
}

class DQPagingListRefreshView: JXPagingListRefreshView {

    /// pods 里面忘了设置，这里设置生效
    override func preferredProcessListViewDidScroll(scrollView: UIScrollView) {
        super.preferredProcessListViewDidScroll(scrollView: scrollView)
        
        currentScrollingListView?.showsVerticalScrollIndicator = automaticallyDisplayListVerticalScrollIndicator
    }
}

**Comment by Junnor** [comment]
automaticallyDisplayListVerticalScrollIndicator = false

class DQPagingListRefreshView: JXPagingListRefreshView {

    /// pods 里面忘了设置，这里设置生效
    override func preferredProcessListViewDidScroll(scrollView: UIScrollView) {
        super.preferredProcessListViewDidScroll(scrollView: scrollView)
        
        currentScrollingListView?.showsVerticalScrollIndicator = automaticallyDisplayListVerticalScrollIndicator
    }
}
