### ISSUE TITLE
heightForPinSectionHeaderInPagerView 设置为0的时候到问题

### ISSUE THREAD

**Issue by menhui222** [pujiaxin33/JXPagingView#309]
业务场景:当numberOfListsInPagerView为1的时候就不需要显示viewForPinSectionHeaderInPagerView
所以我将heightForPinSectionHeaderInPagerView 设置为0
造成bug就是当处理到这个代码的时候就会self.mainTableView.contentOffset = CGPointMake(0, self.mainTableViewMaxContentOffsetY);
问题出现在
 if (self.currentScrollingListView != nil && self.currentScrollingListView.contentOffset.y > [self minContentOffsetYInListScrollView:self.currentScrollingListView]) {
        //mainTableView的header已经滚动不见，开始滚动某一个listView，那么固定mainTableView的contentOffset，让其不动
        [self setMainTableViewToMaxContentOffsetY];
    }

解决方案

   CGFloat height = 0;
    if(self.delegate&&[self.delegate respondsToSelector:@selector(heightForPinSectionHeaderInPagerView:)]){
        height = [self.delegate heightForPinSectionHeaderInPagerView:self];
    }
    if (self.currentScrollingListView != nil && self.currentScrollingListView.contentOffset.y > [self minContentOffsetYInListScrollView:self.currentScrollingListView]&&height>0) {
        //mainTableView的header已经滚动不见，开始滚动某一个listView，那么固定mainTableView的contentOffset，让其不动
        [self setMainTableViewToMaxContentOffsetY];
    }

经过测试而且不影响正常情况

**Comment by pujiaxin33** [comment]
感谢到你的反馈，考虑你这种情况的特殊性，建议你自己fork修改代码，暂时无法将你建议的代码合并到master
