### ISSUE TITLE
超出titleView 上面的按钮怎么相应点击事件？？？

### ISSUE THREAD

**Issue by zhangqi02060227m** [pujiaxin33/JXPagingView#31]
![simulator screen shot - iphone 8 plus - 2018-11-14 at 15 47 32](https://user-images.githubusercontent.com/16876013/48536722-66d49800-e8ea-11e8-98b5-00240776ca60.png)
画红色圈圈的按钮，不相应点击事件，我已经做过
- (UIView *)hitTest:(CGPoint)point withEvent:(UIEvent *)event {
    UIView *view = [super hitTest:point withEvent:event];
    if (view == nil) {
        for (UIView *subView in self.subviews) {
            CGPoint tp = [subView convertPoint:point fromView:self];
            if (CGRectContainsPoint(self.btnFollow.bounds, tp)) {
                view = self.btnFollow;
            } else if (CGRectContainsPoint(self.btnServe.bounds, tp)) {
                view = self.btnServe;
            }  else if (CGRectContainsPoint(self.btnMore.bounds, tp)) {
                view = self.btnMore;
            } else if (CGRectContainsPoint(self.btnClose.bounds, tp)) {
                view = self.btnClose;
            }

        }
    }
    return view;
}
还是点击不到？？？请问问什么？？

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/48536960-08f48000-e8eb-11e8-9edf-c6e60aea6a41.png)
红框里面的视图都是TableHeaderView？
该视图没有导航栏？
你自己看下视图层级，上面有没有其他东西呢？
自己多思考一下，这个问题应该更该库没有关系

**Comment by zhangqi02060227m** [comment]
![2018-11-15 3 56 02](https://user-images.githubusercontent.com/16876013/48538272-fd0abd00-e8ee-11e8-9638-f324af9109b0.png)
这个是视图的层级，因为几个按钮超出了父视图。。。所以没有办法响应点击事件。。。。
