### ISSUE TITLE
mainTableViewDidScroll一直为0

### ISSUE THREAD

**Issue by wsb0617** [pujiaxin33/JXPagingView#310]
func tableHeaderViewHeight(in pagingView: JXPagingView) -> Int {
        return 0
    }
    
    func tableHeaderView(in pagingView: JXPagingView) -> UIView {
        let v = UIView.init()
        return v
    }
    
    func heightForPinSectionHeader(in pagingView: JXPagingView) -> Int {
        return 0
    }
    
    func viewForPinSectionHeader(in pagingView: JXPagingView) -> UIView {
        return UIView.init()
    }
当viewForPinSectionHeader和tableHeaderViewHeight高度都为0时，mainTableViewDidScroll滑动offset一直为0
![image](https://user-images.githubusercontent.com/5467640/102998901-11582400-4563-11eb-92f9-3a039df8db44.png)

**Comment by pujiaxin33** [comment]
无法支持tableHeaderViewHeight为0
