### ISSUE TITLE
如何在第一个list里面置换另外请求到的数据呢

### ISSUE THREAD

**Issue by 2227322717** [pujiaxin33/JXPagingView#311]
**Feature描述**
请简单描述你想要的效果：？
例如第一列上面有两个按钮，一个是获取售出商品列表，一个是获取退货商品列表，点击按钮后第一列可以置换两组不同的数据。

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
你是想问根据不同的数据刷新吗？

**Comment by pujiaxin33** [comment]
根据数据接口返回，找到对应的列表更新即可
