### ISSUE TITLE
CollectionView的cell数量过少时无法进行下拉刷新/上拉加载操作

### ISSUE THREAD

**Issue by alvnly** [pujiaxin33/JXPagingView#315]
<img width="332" alt="image" src="https://user-images.githubusercontent.com/6657499/104402677-cb0a4980-5591-11eb-87a5-3ebe78015b27.png">
底部无法上拉加载,顶部也无法下拉刷新

**Comment by alvnly** [comment]
alwaysBounceVertical设置为true也不起作用

**Comment by pujiaxin33** [comment]
请使用JXPagingListRefreshView
