### ISSUE TITLE
隐藏导航栏，设置pinSectionHeaderVerticalOffset 后，刷新回调没有动画了

### ISSUE THREAD

**Issue by weizhangCoder** [pujiaxin33/JXPagingView#316]
bug描述
在demo中的 RefreshViewController 设置 pinSectionHeaderVerticalOffset 后 下拉刷新结束 会立即回弹 不会有动画 不设置就正常

版本号
1.JXPagingView版本号：2.0.13
2.OC还是Swift版本：OC
3.手机系统版本号：模拟器 14.3
4.手机型号：模拟器 iPhone 11 Pro Max

我也出现了这个问题，隐藏RefreshViewController里面的导航栏。这个时候视图整体向上偏移，所以设置了self.pagerView.pinSectionHeaderVerticalOffset = 导航栏高度，这个时候就 [self.pagerView reloadData];     里面瞬间把偏移量变为0了。没有了动画，你解决了吗？
@pujiaxin33  大佬这个有办法解决吗？

_Originally posted by @weizhangCoder in https://github.com/pujiaxin33/JXPagingView/issues/282#issuecomment-756659112_

**Comment by pujiaxin33** [comment]
感谢反馈，已修复

**Comment by weizhangCoder** [comment]
谢谢，不更新一个版本号吗？

**Comment by weizhangCoder** [comment]
> 感谢反馈，已修复

谢谢，不更新一个版本号吗？

**Comment by pujiaxin33** [comment]
明后天吧
