### ISSUE TITLE
请问listview是tableview时 想要其中的一个tableview支持左滑删除该怎么做？

### ISSUE THREAD

**Issue by ClaerAss** [pujiaxin33/JXPagingView#318]
除了将pagerview的isListHorizontalScrollEnabled设置为NO还有其他方法吗？

**Comment by ClaerAss** [comment]
想要实现 滑动cell时有滑动删除 滑动其余空白区域时滑动页面

**Comment by pujiaxin33** [comment]
目前只能将pagerview的isListHorizontalScrollEnabled设置为NO

**Comment by Plotac** [comment]
@pujiaxin33  关于这个问题，我提交了一个PRhttps://github.com/pujiaxin33/JXPagingView/pull/532
