### ISSUE TITLE
使用哪个库的疑问

### ISSUE THREAD

**Issue by BinBear** [pujiaxin33/JXPagingView#32]
你好，感谢作者的开源，有几点小疑问：
1、如果我想使用带有头部高度可以改变的效果，只使用JXCategoryView可以吗，还是说需要JXCategoryView和JXPagingView一起pod进来
2、swift跟oc版本代码同步吗

**Comment by pujiaxin33** [comment]
1、“如果我想使用带有头部高度可以改变的效果”，这是什么效果，我想不出来；
2、JXPagingView不绝对依赖JXCategoryView，你可以不用，或者用其他的；
3、swift跟oc代码同步；

**Comment by BinBear** [comment]
@pujiaxin33 第一点的效果就是：列表可以下拉刷新，HeaderView高度可改变

**Comment by pujiaxin33** [comment]
“列表可以下拉刷新，HeaderView高度可改变”
这个效果我是真实现不了，一个下拉事件，究竟是响应headerView高度改变呢？还是下拉刷新呢？
你不可能同时都响应卅。
结论：实现不了 -_-

**Comment by BinBear** [comment]
@pujiaxin33 不是同时响应两个事件，单独的，下拉刷新的时候刷新数据就行，headerView高度改变的时候改变高度就行，也就是说同时具有这两个功能就行

**Comment by pujiaxin33** [comment]
关键是什么时候认为要下拉刷新，什么时候认为是要headerView高度改变。

**Comment by yangbo930204** [comment]
> @ pujiaxin33不是同时响应两个事件，单独的，下拉刷新的时候刷新数据就行，headerView高度改变的时候改变高度就行，也就是说同时具有这两个功能就行

这种场景：下拉刷新时，请求回来需要显示banner，但是之前没有banner,需要改下headerView的高度以便添加banner。

`func tableHeaderViewHeight(in pagingView: JXPagingView) -> Int {
       return headerViewHeight
}`
这个只需要在改变headerView高度和上面那个代理用到的headerViewHeight的时候，调用一下`pagingView.reloadData()` 即可.(但是在iOS 9及以下不起作用。我比较着急，在iOS 9 上是直接删除再重新创建的)

**Comment by pujiaxin33** [comment]
@yangbo930204 关于高度改变，你可以参考swift项目写的高度改变示例用法，oc同样支持。我在ios9模拟器测试有效

**Comment by yangbo930204** [comment]
> @ yangbo930204关于高度改变，你可以参考SWIFT项目写的高度改变示例用法，OC同样支持。我在ios9模拟器测试有效

之前的项目没有。。所以只能自己先瞎弄了。 非常感谢哈。库很棒！
