### ISSUE TITLE
JXPagingSmoothView自定义pinView悬停的位置

### ISSUE THREAD

**Issue by noname004** [pujiaxin33/JXPagingView#321]
**Feature描述**
请简单描述你想要的效果：JXPagingSmoothView自定义悬停的位置（smoothView 没有类似JXPagingView的pinSectionHeaderVerticalOffset属性设置）

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：阅读了源码，尝试做了一些修改，可以实现悬停位置自定义，但中途遇到一些底部listVC左右滑动时候pinView会跳动的问题想不出来原因在哪，我已加了作者大大的扣扣能否通过下具体请教一下？或者作者大大直接feature一下这个功能

**Comment by pujiaxin33** [comment]
之前尝试过，支持不了。
