### ISSUE TITLE
关于在左右切换时  ListScrollView  的contentOffset重置为 0 的问题

### ISSUE THREAD

**Issue by sunsang** [pujiaxin33/JXPagingView#324]
类似于demo中个人主页的样式，在左右切换listScrollView时，如果在其中的某一个listScrollView中显示了headerView，就会把其他listScrollView的contentOffset重置为 0。不知道能不能基于这个实现不重置为 0

**Comment by pujiaxin33** [comment]
基于这个库的原理无法实现你想要的效果。只要其中有一个列表显示了headerView之后，都会触发其他列表重置contentOffset.y=0

**Comment by TML007** [comment]
> 基于这个库的原理无法实现你想要的效果。只要其中有一个列表显示了headerView之后，都会触发其他列表重置contentOffset.y=0

不知道这个可有后续优化。正常功能是当某一个listScrollView的tableview滑动看至某一个位置。另一个listScrollView滑动显示了headerView ，此时某一个listScrollView的tableview滑动看至某一个位置应该还在呀！
