### ISSUE TITLE
子列表卡死

### ISSUE THREAD

**Issue by CoderYLM** [pujiaxin33/JXPagingView#325]
需求：想要每次切换的时候都刷新数据
问题：第一次切换可以刷新，第二次切回来选中的时候子列表就卡死了
![52FCD633-62AE-4F8E-86C4-5FCA1594F503](https://user-images.githubusercontent.com/55923063/107142602-30701100-696b-11eb-8abd-593b096a1ae6.png)

**Comment by pujiaxin33** [comment]
子列表刷新请使用`JXPagingListRefreshView`类

**Comment by pujiaxin33** [comment]
我在swift版本demo添加了**用于测试每次点击segment切换，都触发子列表的下拉刷新**测试代码，并没有发现你说的卡死问题，建议你自己分析一下卡死的地方。
