### ISSUE TITLE
initListIfNeeded重置listView

### ISSUE THREAD

**Issue by WangFeiF** [pujiaxin33/JXPagingView#326]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by WangFeiF** [comment]
首次滑动，调用initListIfNeeded中，cell = collectionView.cellForItem(at: IndexPath(item: index, section: 0)) 中，cell有可能为nil，如果为nil，正好会将list.listView().frame设置为zero，建议改为，不影响正常使用，能更健壮些
 //MARK: - Private
    func initListIfNeeded(at index: Int) {
        guard let dataSource = dataSource else { return }
        if dataSource.listContainerView?(self, canInitListAt: index) == false {
            return
        }
        var existedList = validListDict[index]
        if existedList != nil {
            //列表已经创建好了
            return
        }
        existedList = dataSource.listContainerView(self, initListAt: index)
        guard let list = existedList else {
            return
        }
        if let vc = list as? UIViewController {
            containerVC.addChild(vc)
        }
        validListDict[index] = list
        if type == .scrollView {
            list.listView().frame = CGRect(x: CGFloat(index)*scrollView.bounds.size.width, y: 0, width: scrollView.bounds.size.width, height: scrollView.bounds.size.height)
            scrollView.addSubview(list.listView())
        }else {
            guard let cell = collectionView.cellForItem(at: IndexPath(item: index, section: 0)) else {
                return
            }
            cell.contentView.subviews.forEach { $0.removeFromSuperview() }
            // cell 如果取不到，反而会吧listview的frame设置为zero
            // 故改为如果取不到，不设置frame
            list.listView().frame = cell.contentView.bounds
            cell.contentView.addSubview(list.listView())
        }
    }

**Comment by pujiaxin33** [comment]
感谢反馈，已经优化cell为nil的代码
