### ISSUE TITLE
JXPagingView 和 最新版JXSegmentedView 的 listContainer不匹配，无法联动

### ISSUE THREAD

**Issue by aiiaji** [pujiaxin33/JXPagingView#328]
**bug描述**
JXPagingView 和 最新版JXSegmentedView 的 listContainer不匹配，无法联动

segmentedView.listContainer = pagingView.listContainerView
JXPagingViewdemo中用的JXSegmentedView版本太老，替换成最新版又会冲突

**Comment by aiiaji** [comment]
已解决，pagingView.listContainerView extension JXSegmentedView协议即可

**Comment by o1xhack** [comment]
可以贴一下你得extension吗？

**Comment by o1xhack** [comment]
> 可以贴一下你得extension吗？ @aiiaji

已解决

```
extension JXPagingListContainerView: JXSegmentedViewListContainer {}
```

**Comment by mikefan1998** [comment]
怎么解决的， 依赖的版本都是多少

**Comment by o1xhack** [comment]
> 怎么解决的， 依赖的版本都是多少

帖子太老了，以前的依赖应该也不行了，我是一个个 debug出来的版本依赖
