### ISSUE TITLE
导航栏隐藏的时候，无法添加列表下拉刷新

### ISSUE THREAD

**Issue by BinBear** [pujiaxin33/JXPagingView#33]
当导航栏隐藏的时候，无法添加列表下拉刷新，如果是添加顶部的下拉刷新，这个下拉的控件又会在headerView上面，作者有啥解决办法吗

**Comment by pujiaxin33** [comment]
请问你用的是JXPagerListRefreshView吗？

**Comment by BinBear** [comment]
@pujiaxin33 我使用JXPagerListRefreshView添加上下拉刷新了，出现了另外一个问题，往上滑的时候，滑动一点点categoryView就直接到顶部了，有的时候categoryView直接就不动了，列表却往上滑了，跟我隐藏导航栏有关，因为用了作者隐藏导航栏的方式，希望能兼容一下隐藏导航栏和列表刷新

**Comment by pujiaxin33** [comment]
你在NaviBarHiddenViewController类添加一个方法：
```
- (JXPagerView *)preferredPagingView {
    return [[JXPagerListRefreshView alloc] initWithDelegate:self];
}
```

然后再viewDidLoaded里面添加
```
for (TestListBaseView *listView in self.listViewArray) {
        listView.isNeedHeader = YES;
    }
```
就可以有导航栏隐藏和下拉刷新了
