### ISSUE TITLE
子列表猛的滑动到底部，反弹回来，第一次左滑或者右滑会失效，第二次才可正常左右滑动

### ISSUE THREAD

**Issue by fortitude1990** [pujiaxin33/JXPagingView#330]

**Comment by pujiaxin33** [comment]
建议参考文档配置，比如正确配置scrollCallback。

或者你给一个详细的复现逻辑 或者 操作视频

**Comment by jueXying** [comment]
这个问题demo也存在，比如《悬浮SectionHeader位置动态调整》

**Comment by jueXying** [comment]
猜测是需要等到减速动画结束后，才能进行回调，这种情况是设置了pinSectionHeaderVerticalOffset值，是看不到动画效果的，然后需要等到动画结束才可以滑动。
解决办法：这里将animated设置为NO
- (void)setMainTableViewToMaxContentOffsetY {
    [self.mainTableView setContentOffset:CGPointMake(0, self.mainTableViewMaxContentOffsetY) animated:NO];
//    self.mainTableView.contentOffset = CGPointMake(0, self.mainTableViewMaxContentOffsetY);
}

**Comment by jueXying** [comment]
猜测是需要等到减速动画结束后，才能进行回调，这种情况是设置了pinSectionHeaderVerticalOffset值，是看不到动画效果的，然后需要等到动画结束才可以滑动。
解决办法：这里将animated设置为NO
- (void)setMainTableViewToMaxContentOffsetY {
    [self.mainTableView setContentOffset:CGPointMake(0, self.mainTableViewMaxContentOffsetY) animated:NO];
//    self.mainTableView.contentOffset = CGPointMake(0, self.mainTableViewMaxContentOffsetY);
}

**Comment by fortitude1990** [comment]
> 建议参考文档配置，比如正确配置scrollCallback。
> 
> 或者你给一个详细的复现逻辑 或者 操作视频

**Comment by fortitude1990** [comment]
> 建议参考文档配置，比如正确配置scrollCallback。
> 
> 或者你给一个详细的复现逻辑 或者 操作视频

这个问题demo也是存在的，你可以看一下demo的特殊效果 ->  个人主页 ,  滑动到爱好，将爱好的列表猛地滑动到底部，等动画完成后，左右滑动第一次就会失效，第二次才会有效。

**Comment by zhaohailog** [comment]
设置去掉动画之后，会出现滑动子类滚动视图过程中放开手后，整个列表不会一起滑动，会产生滑动脱离现象
