### ISSUE TITLE
列表返回最顶部并且执行刷新以后无法滚动

### ISSUE THREAD

**Issue by CoderYLM** [pujiaxin33/JXPagingView#335]
**bug描述**
列表返回最顶部并且执行刷新以后无法滚动

**版本号**
1.JXPagingView版本号：2.0.1和2.0.13这两个版本都测试过会出现问题
2.OC还是Swift版本：OC
3.手机系统版本号：iOS 14.3
4.手机型号：iphone6 Plus, iphone 7, iphone 11

**截图、GIF**
![B249AE1D-D055-4C59-96BE-DB633ECF226A](https://user-images.githubusercontent.com/55923063/113248741-1bbb5400-92f0-11eb-9b05-3930525f8610.png)

加上最后一行beginRefreshing以后列表就无法滑动了，注释掉就不会有问题

**Comment by CoderYLM** [comment]
暂时的解决办法就是在最后再执行一次pagerView reloadData

**Comment by pujiaxin33** [comment]
使用的是JXPagerListRefreshView吗？
