### ISSUE TITLE
数据量过少的处理

### ISSUE THREAD

**Issue by sunhuaiwu** [pujiaxin33/JXPagingView#336]
如果数据量过少，可不可以不强制segmentedview滑动到顶，而是只可以滑动到显示完数据。

<img width="297" alt="WeChat243dc6e10dff9c3c59deacc3608b3197" src="https://user-images.githubusercontent.com/11421343/113272823-9eeba280-930e-11eb-9ee9-53abbb437b38.png">

**Comment by sunhuaiwu** [comment]
像这样如果只有两条数据，滑动到底下面会有空白
![Uploading Simulator Screen Shot - iPhone 8 - 2021-04-01 at 21.33.27.png…]()

**Comment by sunhuaiwu** [comment]
像这样如果header屏幕百分之90高，只有两条数据，滑动到底下面会有空白，请问怎么能控制滑动到显示完两条数据就不可继续滑动
![Simulator Screen Shot - iPhone 8 - 2021-04-01 at 21 33 27](https://user-images.githubusercontent.com/11421343/113302180-62ca3900-9332-11eb-926b-094fef4bef6e.png)

**Comment by sunhuaiwu** [comment]
看了下源码，就是mainTableView的row的问题，希望能给个控制mainTableview行高的属性

**Comment by pujiaxin33** [comment]
抱歉，无法实现，必须要有一个最小高度。
