### ISSUE TITLE
pagingView嵌套pagingView，滚动最底部的listContainer，最顶部的categoryView直接悬停，headerView快速消失

### ISSUE THREAD

**Issue by amycliny** [pujiaxin33/JXPagingView#338]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
移动底部的listContainer，顶部的header会滚到底部，categoryView悬停置顶。是否是因为暂时不支持pagingView嵌套pagingView呢？谢谢解答~

**版本号**
1.JXPagingView版本号：2.0.8
2.OC还是Swift版本：OC
3.手机系统版本号：14.4
4.手机型号：模拟器和真机都有

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
[具体可看下面的视频](url

https://user-images.githubusercontent.com/15085638/113815457-c080da00-97a5-11eb-80da-ddee28437437.mov

)

**Comment by hongxubao** [comment]
你这个问题解决了么

**Comment by pujiaxin33** [comment]
不支持pagingView嵌套pagingView

**Comment by suGaoFei** [comment]
我下面自定义view，view中添加了vc，vc里面有tableview ，也会出现这个问题。上划就直接把tableHeaderView闪没

**Comment by wmadao11** [comment]
我这边也有类似的问题，底部是vc->UITableView，其中有TableViewCell里嵌套了CollectionView，在第一次往下滚动时会直接跳到标签view悬浮在顶部的位置，后续再滚动就不会了
