### ISSUE TITLE
遇到一个刷新的问题

### ISSUE THREAD

**Issue by yungfan** [pujiaxin33/JXPagingView#34]
作者您好：
        我在使用这个库的时候，在TestListView中设置刷新的时候，我想一进来就刷新一次，然后在点击title的时候也能够刷新，问题来了，在三个title的时候，点击中间的那个，会把第三个或者第一个也一起刷新了，虽然好像预加载了，但是我不需要这个功能该怎么解决？还望回复一下

**Comment by pujiaxin33** [comment]
虽然有点不太懂你的核心问题，但是我把列表下拉刷新的示例demo优化了一下，你重新clone仓库看一下呢

**Comment by pujiaxin33** [comment]
感谢你的反馈，自测复现了，是UICollectionView的prefetchDataSource功能触发的。1.0.0版本已经修复了。
