### ISSUE TITLE
实现JXCategoryTitleView中的title增加或者删除的时候，JXPageview中的reloadData的方式能是否能保持原有页面状态不变，而不是全部remove再add？

### ISSUE THREAD

**Issue by changpk** [pujiaxin33/JXPagingView#340]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：今日头条
2.目标页面路径：首页-点击 顶部titleview右侧的频道管理如下
![B927123BCFDAD96379A1741C720ADA3E](https://user-images.githubusercontent.com/5789904/114156515-3ecfae80-9955-11eb-8251-535797850c19.png)
3.目标效果截图：
点击频道管理新增或者删除后，原先页面的状态是可以保留的，不是全部重新生成。

**其他补充**
关于目标效果的其他说明：
简单说：JXCategoryTitleView的title动态管理（增加或者删除的时候），JXPagerView中的原先视图能否保证最小化的增加或者
删除，现在调用reloadData的话，是全部remove<JXPagerViewListViewDelegate> 的控制器。
这样原先页面的状态会丢失。

**Comment by pujiaxin33** [comment]
需要你自己缓存列表，然后通过initListAtIndex方法返回已创建的列表。
