### ISSUE TITLE
tableView.scrollToRow

### ISSUE THREAD

**Issue by Gaozn** [pujiaxin33/JXPagingView#341]
**bug描述**
子视图是tableVC 在viewDidLoad调用tableView.scrollToRow 滑动至某一行无效

**Comment by Gaozn** [comment]
![QQ20210414-152200-HD](https://user-images.githubusercontent.com/10608257/114670104-3ef4f300-9d35-11eb-94d8-e41ab32d4d84.gif)
当我尝试延迟执行时，出现了如图的情况，会向下偏移，然后回弹
 DispatchQueue.main.asyncAfter(deadline: .now() + 1) {
            self.tableView.beginUpdates()
            self.tableView.scrollToRow(at: IndexPath(row: 6, section: 0), at: UITableView.ScrollPosition.top, animated: true)
            self.tableView.endUpdates()
        }

**Comment by pujiaxin33** [comment]
你看下oc和swift的示例，有相关的示例

**Comment by smallgirl** [comment]
如何解决的？

**Comment by PursuitSunshine** [comment]
如何解决的？示例在哪里啊？ @pujiaxin33
