### ISSUE TITLE
获取  public var currentList: JXPagingViewListViewDelegate?  错误

### ISSUE THREAD

**Issue by FunnyerFeng** [pujiaxin33/JXPagingView#342]
通过JXPagingView 获取  public var currentList: JXPagingViewListViewDelegate?  错误，一直是第一个list 
目前解决方法是通过validListDict 获取

**Comment by pujiaxin33** [comment]
感谢反馈，currentList这个属性访问权限问题，已经修改为internal，不能被外部访问使用。
