### ISSUE TITLE
表格头部刷新无回弹动画

### ISSUE THREAD

**Issue by GKWenBo** [pujiaxin33/JXPagingView#344]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
作者，你好，我项目集成了这个库，通过pinSectionHeaderVerticalOffset改变悬停位置，结合MJRefresh做整体下拉刷新的时候，没有回弹动画，发现pod里JXPagerView类reloadData方法代码和GitHub源库代码不一致。

**版本号**
1.JXPagingView版本号：2.0.13
2.OC还是Swift版本：OC
3.手机系统版本号：13.3.1
4.手机型号：iPhone X

**复现步骤**
1. 下拉刷新结束下拉刷新

**截图、GIF**
提供bug出现时的截图或者GIF。
![截屏2021-04-27 上午11 44 56](https://user-images.githubusercontent.com/25070098/116182201-6e9cf580-a74e-11eb-9ca3-8012b9875b8b.png)
![截屏2021-04-27 上午11 45 56](https://user-images.githubusercontent.com/25070098/116182212-7361a980-a74e-11eb-80a9-75593dd26761.png)

**Comment by weizhangCoder** [comment]
应该是大佬没有新增加版本号，我也在等大佬升级库 @pujiaxin33 。

**Comment by pujiaxin33** [comment]
恩，稍等，今天应该会发新包。
