### ISSUE TITLE
能否提供个刷新悬浮view高度的方法

### ISSUE THREAD

**Issue by yunjieyj** [pujiaxin33/JXPagingView#345]
**Feature描述**
请简单描述你想要的效果：有时候切换不同tab时，需要使用不一样高度的悬浮view。切换不同高度的悬浮view后，能否保持在当前contentOffset？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
1、更改`tableHeaderViewHeightInPagerView`代理方法返回的view。
2、调用`resizeTableHeaderViewHeightWithAnimatable`方法触发headerview的更新。
