### ISSUE TITLE
界面无法向下滑动

### ISSUE THREAD

**Issue by allendeng3** [pujiaxin33/JXPagingView#349]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。
使用的JXPagingView
界面向上滑动悬停后，想再向下移动时，头视图无法显示，一直在悬停位置卡顿。

断点调试发现 minContentOffsetYInListScrollView中计算出的adjustedContentInset.top 不满足在scrolldidscrollview中的if 判断
问题只出现在12 pro max 14.5 版本上
图片中是希望向下滑动 headerview能显示

**版本号**
1.JXPagingView版本号：？2.1.0
2.OC还是Swift版本：？swift
3.手机系统版本号：？14.5
4.手机型号：？12 pro max

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。
![image](https://user-images.githubusercontent.com/7615935/118617252-085b3e00-b7f5-11eb-9d06-2bd9c5a215ea.jpeg)

**Comment by pujiaxin33** [comment]
建议参考demo的配置代码，尤其是列表滚动那一块的代码。
