### ISSUE TITLE
OC版 如何更新顶部userHeaderView的高度?

### ISSUE THREAD

**Issue by iBinbro** [pujiaxin33/JXPagingView#35]
OC版 如何更新顶部userHeaderView的高度? 每次下拉刷新 我都想动态改变头部的高度，要怎么做

**Comment by iBinbro** [comment]
大概是这样吧...
self.userHeaderView.frame = CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, 500);
        JXTableHeaderViewHeight = 500;
        [self.pagerView reloadData];

**Comment by pujiaxin33** [comment]
是这样子的
