### ISSUE TITLE
在headerview是地图的时候，地图和maintableview手势冲突，这个要如何解决呢？谢谢了。

### ISSUE THREAD

**Issue by iimuy** [pujiaxin33/JXPagingView#353]
**Feature描述**
请简单描述你想要的效果：
在headerview是地图的时候，地图和maintableview手势冲突，这个要如何解决呢？谢谢了。
![image](https://user-images.githubusercontent.com/10590616/120735245-d6e4b100-c51c-11eb-8eb4-28a61c589f0f.png)

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：
2.目标页面路径：
3.目标效果截图：

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
你尝试实现`- (BOOL)mainTableViewGestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer;`代理方法，当判断otherGestureRecognizer是地图的手势时，就return NO；

**Comment by imzzcoder** [comment]
蛋疼，百度地图是没有手势漏出……

**Comment by pujiaxin33** [comment]
你打断点看一下手势的类名，或许有线索

**Comment by imzzcoder** [comment]
好的
