### ISSUE TITLE
怎么实现 headerView 的高度可以展开和收起，意思就是headerview的高度能够动态的改变

### ISSUE THREAD

**Issue by zhangqi02060227m** [pujiaxin33/JXPagingView#354]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by zixinxiaohei** [comment]
贝壳首页，header可以自由滑动

**Comment by pujiaxin33** [comment]
可以参考OC example中的【HeaderView高度改变示例】

**Comment by znblyj** [comment]
这个pagingView.resizeTableHeaderViewHeight()
