### ISSUE TITLE
怎么实现segmentview 放在header 上面

### ISSUE THREAD

**Issue by lanhaooo** [pujiaxin33/JXPagingView#355]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？
<img width="481" alt="截屏2021-06-07 16 08 16" src="https://user-images.githubusercontent.com/85482876/120982696-8cc52f00-c7ab-11eb-9325-5f91959874a1.png">

**其他补充**
关于目标效果的其他说明：？
segmentview 放在header上面的

**Comment by maketubotim** [comment]
![1638435054585](https://user-images.githubusercontent.com/21094560/144388907-daf32c3c-cb8a-4894-b7d6-d1cce3689bd8.jpg)

**Comment by maketubotim** [comment]
您好，如何实现类似上图的效果呢，segmentview菜单盖住header

**Comment by pujiaxin33** [comment]
可以把你先要悬浮的视图包裹到一个view中，然后将其通过viewForHeaderInSection返回。
