### ISSUE TITLE
swift为什么会报这个错，能帮忙看一下吗？谢谢

### ISSUE THREAD

**Issue by ZCApple** [pujiaxin33/JXPagingView#356]
<img width="966" alt="327F2DD6-F90B-4DAA-8268-7B409FEA38A7" src="https://user-images.githubusercontent.com/35450114/121359458-14ef3400-c966-11eb-961b-aebd6cadf03f.png">

**Comment by ZCApple** [comment]
和demo一样的写法

**Comment by DreamRui** [comment]
添加
extension JXPagingListContainerView: JXSegmentedViewListContainer {}
