### ISSUE TITLE
mainTableView滚动代理方法没有调用

### ISSUE THREAD

**Issue by lxtkinky** [pujiaxin33/JXPagingView#361]
@objc optional func mainTableViewDidScroll(_ scrollView: UIScrollView)
    @objc optional func pagingView(_ pagingView: JXPagingView, mainTableViewDidScroll scrollView: UIScrollView)
    @objc optional func pagingView(_ pagingView: JXPagingView, mainTableViewWillBeginDragging scrollView: UIScrollView)
    @objc optional func pagingView(_ pagingView: JXPagingView, mainTableViewDidEndDragging scrollView: UIScrollView, willDecelerate decelerate: Bool)
    @objc optional func pagingView(_ pagingView: JXPagingView, mainTableViewDidEndDecelerating scrollView: UIScrollView)
    @objc optional func pagingView(_ pagingView: JXPagingView, mainTableViewDidEndScrollingAnimation scrollView: UIScrollView)
`最新swift版本这几个方法没有回调```

**Comment by pujiaxin33** [comment]
最近版本没有该问题。
