### ISSUE TITLE
JXPagerSmoothView reloadData问题

### ISSUE THREAD

**Issue by huangxianyu** [pujiaxin33/JXPagingView#364]
**bug描述**
JXPagerSmoothView reloadData问题

问题1. 每次reloadData, 列表都会滑到最顶部. 是否可以停留在当前滚动到的位置.
问题2. reloadData, 为了避免列表重复创建, 使用了@property (nonatomic, strong) NSMutableDictionary <NSString *, id<JXPagerSmoothViewDataSource>> *listCache; 但是滚动到悬浮条停到顶部后, 继续往上滚动, 然后reloadData,  列表滚到最顶端, 列表就不能滚动了

**复现步骤**
问题2
(1) 悬浮条滚动到顶部, 列表继续往上滚动.
(2) 调用reloadData方法, 列表滚到最顶端.
(3) 再次列表就不能滚动了.

**截图、GIF**
https://user-images.githubusercontent.com/20720740/124265900-ed584980-db68-11eb-82d8-77fd5a047516.mov

**Comment by huangxianyu** [comment]
大佬 JXPagerSmoothView可不可以让悬浮条停在指定位置?

**Comment by RobotAmiee** [comment]
> 大佬 JXPagerSmoothView可不可以让悬浮条停在指定位置?

提了个 [pull request](https://github.com/pujiaxin33/JXPagingView/pull/366)，你看看是不是你要的效果。

**Comment by 1knight520** [comment]
> 每次reloadData, 列表都会滑到最顶部. 是否可以停留在当前滚动到的位置.

这个你解决了吗 什么方法

**Comment by 1knight520** [comment]
还有除了reloadData ，JXPagerSmoothView怎么滑动到最顶部

**Comment by pujiaxin33** [comment]
> **bug描述** JXPagerSmoothView reloadData问题
> 
> 问题1. 每次reloadData, 列表都会滑到最顶部. 是否可以停留在当前滚动到的位置. 问题2. reloadData, 为了避免列表重复创建, 使用了@Property (nonatomic, strong) NSMutableDictionary <NSString *, id> *listCache; 但是滚动到悬浮条停到顶部后, 继续往上滚动, 然后reloadData, 列表滚到最顶端, 列表就不能滚动了
> 
> **复现步骤** 问题2 (1) 悬浮条滚动到顶部, 列表继续往上滚动. (2) 调用reloadData方法, 列表滚到最顶端. (3) 再次列表就不能滚动了.
> 
> **截图、GIF** https://user-images.githubusercontent.com/20720740/124265900-ed584980-db68-11eb-82d8-77fd5a047516.mov

问题1：是因为实现机制的原因，reloadData必须要全部重置所有的状态，不然就会有状态不一致的情况；
问题2：我按照同样的操作并没有复现同样的问题。

**Comment by pujiaxin33** [comment]
> 还有除了reloadData ，JXPagerSmoothView怎么滑动到最顶部

你可以尝试直接设置list.tableView.contentoffset.y = 0
