### ISSUE TITLE
使用 Xcode 中 Swift Package 工具添加依赖库报错：invalidManifestFormat 

### ISSUE THREAD

**Issue by muxinqi** [pujiaxin33/JXPagingView#365]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

使用 Xcode 中的 Swift Package 工具添加依赖库时，出现错误。

Showing All Messages
invalidManifestFormat("/var/folders/p3/3jdhkx516hgg5dv0zl14wqb40000gn/T/TemporaryFile.AiBj5u.swift:29:52: error: value of type \'(String) -> SwiftVersion\' has no subscripts\n    swiftLanguageVersions: [.version(\"5\"), .version[\"4.2\"]]\n                                           ~~~~~~~~^", diagnosticFile: Optional(<AbsolutePath:"/Users/<USERNAME>/Library/Developer/Xcode/DerivedData/<PROJECT_NAME>/SourcePackages/ManifestLoading/jxpagingview.dia">)) in https://github.com/pujiaxin33/JXPagingView/

**版本号**
1.JXPagingView版本号：2.1.0
2.OC还是Swift版本：Swift
3.手机系统版本号：nil
4.手机型号：nil

**复现步骤**
1. 遇到问题的相关效果、类是：nil
2.具体的操作步骤是：

在项目中使用 Xcode -> File -> Swift Packages -> Add Package Dependency 出现错误

**截图、GIF**
提供bug出现时的截图或者GIF。

<img width="766" alt="image" src="https://user-images.githubusercontent.com/42941327/124866935-cf1e9d80-dfef-11eb-9f8c-05092686498c.png">

**尝试了以下解决方案**

感觉可能是格式问题🤔，就用枚举替换了现在的写法。

```diff
- swiftLanguageVersions: [.version("5"), .version["4.2"]]
+ swiftLanguageVersions: [.v5, .v4_2]
```

并清空了 Xcode 中 Derived Data，以及 `~/Library/Caches/org.swift.swiftpm/` 对应的 `JXPagingView` 缓存

再次尝试使用 Xcode 中 Swift Package 工具添加依赖，仍提示此错误。

**Comment by JayDaniel** [comment]
依然添加错误啊，我目前是fork后，删除了swift version版本限制，才成功。

**Comment by muxinqi** [comment]
> 依然添加错误啊，我目前是fork后，删除了swift version版本限制，才成功。

关于你删除 `swift version` 才成功这个问题，你的项目中设置的 `Swift Language Version` 是否匹配呢？

在对应 `Target` 下的 `Build Settings` 中，如下图所示：
<img width="818" alt="image" src="https://user-images.githubusercontent.com/42941327/130176791-76d04da8-b577-4b74-aa8f-4283bd1286dc.png">

---

而对于我遇到的问题，主要原因是 repo 中 `swift.package` 文件格式问题，具体解决方案参考 #369
