### ISSUE TITLE
JXPagerSmoothView 动态更新header 高度

### ISSUE THREAD

**Issue by rgmyyw** [pujiaxin33/JXPagingView#368]
**Feature描述**
JXPagerSmoothView 动态更新header 高度

可以和JXPagingView调用 resizeTableHeaderViewHeight  更新header 高度吗

**Comment by RobotAmiee** [comment]
不知道作者最近咋回事，我这边提了个 [pull request](https://github.com/pujiaxin33/JXPagingView/pull/366)，可以设置头部偏移和动态更新头部高度，你可以看看，希望对你有帮助。
