### ISSUE TITLE
当加载的子视图是vc，vc里面加载WKWebView的url或者htmlString时候，segmentedView会弹到顶部悬浮

### ISSUE THREAD

**Issue by pc-He** [pujiaxin33/JXPagingView#371]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

https://user-images.githubusercontent.com/13309562/127117609-a6f14eb3-5487-423d-b09b-73004c4b8bce.mov

swift 版本 JXPagingView嵌套 JXSegmentedView  子视图都是vc，其中一个vc里面是webView 加载的htmlString或者url，在向上滑动的时候，不是平滑的上滑直到悬浮，而是直接弹到顶部直接悬浮，视频是我用demo测试的加载的url 或者htmlString，依旧也会出现，现在想要平滑的滑动，这个要怎么处理呢？   还有个问题，我不想要segmentedView悬浮，视图把segmentedView添加到headerVIew上来解决，但是依然没有实现sgementedView不悬浮，最新的版本有办法解决吗？

**Comment by pujiaxin33** [comment]
请参考文档整除处理scrollCallback(scrollView)的回调。示例代码：
```
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    !self.scrollCallback ?: self.scrollCallback(scrollView);
}
```

**Comment by ShenYj** [comment]
我设置了 scrollCallback(scrollView)的回调 但同样遇到了这个问题

**Comment by ShenYj** [comment]
> 我设置了 scrollCallback(scrollView)的回调 但同样遇到了这个问题

简单的debug了一下，注释这一行后正常：
https://github.com/pujiaxin33/JXPagingView/blob/9c5e9a72fcd0f565cf379331d339a5a6e5947932/Sources/JXPagingView/JXPagingListRefreshView.swift#L36

**Comment by ShenYj** [comment]
找到问题了，Rx写多了，养成了不挂delegate的习惯， 因为没挂delegate 所以导致子列表的didScroll等一系列回调没被触发引起的问题
