### ISSUE TITLE
[JXPagerListContainerView contentScrollView]: unrecognized selector sent to instance 0x108557bf0

### ISSUE THREAD

**Issue by starrymood** [pujiaxin33/JXPagingView#375]
self.categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pagerView.listContainerView;
报错显示unrecognized selector sent to instance 0x108557bf0

**Comment by pujiaxin33** [comment]
这样写`self.categoryView.listContainer = (id<JXCategoryViewListContainer>)self.pagerView.listContainerView;`
