### ISSUE TITLE
能否开放出一个获取currentIndex的属性或者代理来？

### ISSUE THREAD

**Issue by YongTaiSin** [pujiaxin33/JXPagingView#376]
**Feature描述**
我现在想用自定义的一个categoryView，单独使用JXPagerView来实现页面，但是目前来看并没有找到.h里暴露出pagerListContentView的当前index，导致我现在在页面滑动后并不知道当前是哪一页。由于外部接口的请求跟currentIndex关联很大，请问作者能加一个获取index的代理吗

**Comment by pujiaxin33** [comment]
现在已经暴露了JXPagingListContainerView.currentIndex属性
