### ISSUE TITLE
iOS15 headerView与segmentedView会多出来间距

### ISSUE THREAD

**Issue by Corotata** [pujiaxin33/JXPagingView#380]
**bug描述**
iOS15 headerView与segmentedView会多出来间距，在iOS13和iOS14正常显示

**版本号**
1.JXPagingView版本号：2.1.0
2.OC还是Swift版本：Swift
3.手机系统版本号：？iPhone XS Max模拟器

**截图、GIF**
![Simulator Screen Shot - iPhone Xs Max - 2021-08-26 at 14 21 52](https://user-images.githubusercontent.com/4392753/130911617-3f83871d-843f-44de-b10f-62761a7f739c.png)

**Comment by chenshipeng** [comment]
> **bug描述**
> iOS15 headerView与segmentedView会多出来间距，在iOS13和iOS14正常显示
> 
> **版本号**
> 1.JXPagingView版本号：2.1.0
> 2.OC还是Swift版本：Swift
> 3.手机系统版本号：？iPhone XS Max模拟器
> 
> **截图、GIF**
> ![Simulator Screen Shot - iPhone Xs Max - 2021-08-26 at 14 21 52](https://user-images.githubusercontent.com/4392753/130911617-3f83871d-843f-44de-b10f-62761a7f739c.png)

 在iOS15里面需要设置`sectionHeaderTopPadding`为0

**Comment by chenshipeng** [comment]
@Corotata 在iOS15里面需要设置`sectionHeaderTopPadding`为0

**Comment by crazypoo** [comment]
> @Corotata 在iOS15里面需要设置`sectionHeaderTopPadding`为0

没有找到这个属性哦

**Comment by crazypoo** [comment]
> @Corotata 在iOS15里面需要设置`sectionHeaderTopPadding`为0

如果我是以gird形式的collection呢,因为你这个属性如果是list形式的collectionview才可以用UICollectionLayoutListConfiguration配置

**Comment by crazypoo** [comment]
> @Corotata 在iOS15里面需要设置`sectionHeaderTopPadding`为0

如果我是gird样式的collectionview呢?你说的这个属性仅限在tableview,和以UICollectionLayoutListConfiguration的collectionview才能使用

**Comment by superk589** [comment]
@crazypoo 修改 JXPagingView.swift 文件中内部实现用的`mainTableView`的`sectionHeaderTopPadding`
和自己实现用的是什么视图无关

**Comment by crazypoo** [comment]
> @crazypoo 修改 JXPagingView.swift 文件中内部实现用的`mainTableView`的`sectionHeaderTopPadding`
> 和自己实现用的是什么视图无关
好的,只是@chenshipeng 同学没有说清楚而已
