### ISSUE TITLE
深色模式bug

### ISSUE THREAD

**Issue by gongsunqingyang** [pujiaxin33/JXPagingView#382]
**bug描述**
手机开启深色模式，在app中关闭深色模式“[UIApplication sharedApplication].keyWindow.overrideUserInterfaceStyle = UIUserInterfaceStyleLight”，创建”JXCategoryTitleView“并设置“titleColorGradientEnabled = YES”，左右滑动时，标题会出现闪烁

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：OC
3.手机系统版本号：14.7
4.手机型号：iPhone 6s Plus

**截图、GIF**
![Simulator Screen Recording - iPhone 12 - 2021-09-03 at 09 36 35](https://user-images.githubusercontent.com/13862075/131937522-3a858681-005f-4a5d-9c3f-b26c151c2c9a.gif)

**Comment by pujiaxin33** [comment]
同样的操作，并没有出现同样的问题。

**Comment by gongsunqingyang** [comment]
亲，邮件已收到
