### ISSUE TITLE
segmentedView 固定在顶部失效

### ISSUE THREAD

**Issue by liang-zhang** [pujiaxin33/JXPagingView#387]
使用pagingView.mainTableView.isScrollEnabled = false，使segmentview固定在顶部，切换后会跟随滑动

**Comment by YoungXKing** [comment]
请问如何在JXCategoryView和JXPagerView结合使用时，让categoryView固定在一个位置，比如导航栏下方。

**Comment by YoungXKing** [comment]
> 请问如何在JXCategoryView和JXPagerView结合使用时，让categoryView固定在一个位置，比如导航栏下方。

是不是如果要固定JXCategoryView的位置，不需要滑动悬浮等效果，就不必使用JXPagerView了，直接用JXCategoryListContainerView来实现呢？

**Comment by pujiaxin33** [comment]
> > 请问如何在JXCategoryView和JXPagerView结合使用时，让categoryView固定在一个位置，比如导航栏下方。
> 
> 是不是如果要固定JXCategoryView的位置，不需要滑动悬浮等效果，就不必使用JXPagerView了，直接用JXCategoryListContainerView来实现呢？

是的，JXPagerView必须要求悬浮。
