### ISSUE TITLE
iOS 15.0显示有问题

### ISSUE THREAD

**Issue by ZCApple** [pujiaxin33/JXPagingView#390]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：2.1.0
2.OC还是Swift版本：Swift
3.手机系统版本号：iOS 15.0
4.手机型号：iPhone 8以上

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagingView, tableHeaderView和sectionHeaderView之间有一段空白的间距，和设置的tableHeaderViewHeight和sectionHeaderViewHeight大小无关
2.具体的操作步骤是：

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by D-meng** [comment]
OC版本也有同样的问题。

**Comment by IceTears1** [comment]
我也碰到了同样的问题

**Comment by IceTears1** [comment]
JXPagingView.swift 文件内部



初始化mainTableView时候添加以下代码
if #available(iOS 15.0, *) {
            mainTableView.sectionHeaderTopPadding = 0
 }

**Comment by bk97531** [comment]
全局添加，跟预估行高那些一样
if #available(iOS 15.0, *) {
     UITableView.appearance().sectionHeaderTopPadding = 0
}
