### ISSUE TITLE
【P0】阿语环境下JXSegmentedView的title个数大于一个时，第一个list会白屏，要手动来回切一下2个list才正常！！

### ISSUE THREAD

**Issue by qazwyw** [pujiaxin33/JXPagingView#392]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：2.1.0
2.OC还是Swift版本：swift
3.手机系统版本号：所有
4.手机型号：所有

**复现步骤**
1. 遇到问题的相关效果、类是：随便都能复现
2.具体的操作步骤是：阿语下title个数大于1个时初始化第一个就是白屏

**截图、GIF**
![image-2021-09-28-17-02-21-360](https://user-images.githubusercontent.com/9583838/135189845-097b4fba-c78e-4fec-b60f-2c2a7dc96857.gif)

**Comment by qazwyw** [comment]
目前的临时解决方式是在更新titles的时候手动来回刷一下list，很挫！
![image](https://user-images.githubusercontent.com/9583838/135190047-cd13a4e0-66b7-4d9f-9af4-82b14bd10712.png)

**Comment by pujiaxin33** [comment]
展示不支持阿拉伯语言，你可以提交一个Pull Request 支持该特性吗？

**Comment by qazwyw** [comment]
> 展示不支持阿拉伯语言，你可以提交一个Pull Request 支持该特性吗？

这个还需要你花点时间支持一下吧，争取把项目做大做强，因为现在阿拉伯语是很多商业项目的目标市场了

**Comment by pujiaxin33** [comment]
已被PR： https://github.com/pujiaxin33/JXPagingView/pull/515 修复
