### ISSUE TITLE
我建议你修改一下兼容ios15代码的sectionHeaderTopPadding属性，

### ISSUE THREAD

**Issue by zixinxiaohei** [pujiaxin33/JXPagingView#395]
xcode13以下运行，打包全部报错，建议加上
#if __IPHONE_OS_VERSION_MAX_ALLOWED > __IPHONE_14_5
        if (@available(iOS 15.0, *)) {
            self.mainTableView.sectionHeaderTopPadding = 0;
        }
#endif
这句，就兼容旧版本了

**Comment by kkzhaoxiang** [comment]
同上，建议修改编译条件

**Comment by wyk190576528** [comment]
同上，建议修改编译条件

**Comment by pujiaxin33** [comment]
最新2.1.2版本已经更新
