### ISSUE TITLE
需要单独刷新JXPagingView的TableHeaderView

### ISSUE THREAD

**Issue by ywz364kf** [pujiaxin33/JXPagingView#400]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
目前我看JXPagingView，没有把单独刷新TableHeaderView的方法开发，有些业务场景是需要更换TableHeaderView，只能调用JXPagingView的reloadData方法，这样导致下面的列表页刷新，最好能开放refreshTableHeaderView()方法

**版本号**
1.JXPagingView版本号：2.0.13
2.OC还是Swift版本：Swift
3.手机系统版本号：任意
4.手机型号：任意

**Comment by pujiaxin33** [comment]
请参考示例【HeaderView高度改变示例】

**Comment by znblyj** [comment]
直接调用这个pagingView.resizeTableHeaderViewHeight()
