### ISSUE TITLE
JXPagingView 下两个子页面， 其中一个是评论，希望可以固定评论框到页面底部

### ISSUE THREAD

**Issue by WHDevLab** [pujiaxin33/JXPagingView#401]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：bibili
2.目标页面路径：视频详情页
3.目标效果截图：
![IMG_3012](https://user-images.githubusercontent.com/50726147/138596103-b1a512fe-3dc5-4a51-bde7-35356d75a5a8.PNG)

**其他补充**
关于目标效果的其他说明：？
视频详情页，切到评论tab， 然后暂停视频，上下滑动评论，底部评论框是固定的，并且可以在简介和评论间左右切换

**Comment by pujiaxin33** [comment]
你可以查看一下JXPagerView的视图层级，每个列表视图的高度从一开始就是pagerView的高度。所以，你把输入框视图add到列表view，然后监听pager.maintableView.contentOffset.y去不断调整评论列表底部输入框距离底部的距离。整个过程需要你对视图层级有比较清楚的认识，然后就是调整过程会比较花费时间，请耐心的去实现。
