### ISSUE TITLE
pod 导入一直失败

### ISSUE THREAD

**Issue by zhangxin-wuxin** [pujiaxin33/JXPagingView#402]
pod 导入一直报错,之前项目一直用的挺好的

(![image](https://user-images.githubusercontent.com/14136892/138624372-53d359ee-8ace-4e40-a829-c6c523b53498.png))
<img width="568" alt="WechatIMG62" src="https://user-images.githubusercontent.com/14136892/138624470-543c2273-11d9-48c6-80c2-b2e255f73e9d.png">
`

**Comment by HLTangbinbin** [comment]
开VPN去访问，，，github早被墙了

**Comment by pujiaxin33** [comment]
建议终端配合代理进行pod install
