### ISSUE TITLE
iOS15兼容性问题

### ISSUE THREAD

**Issue by lemonvsdemon** [pujiaxin33/JXPagingView#404]
JXPagingView中需要加入以下代码
if #available(iOS 15.0, *) {
          mainTableView.sectionHeaderTopPadding = 0
}
不然在iOS15中会默认有一个顶部间距，希望能够快点修复

**Comment by youwuxiangsheng** [comment]
一样

**Comment by pujiaxin33** [comment]
最近版本2.1.2已经修复
