### ISSUE TITLE
添加sectionHeaderTopPadding，旧版本Xcode无法编译处理

### ISSUE THREAD

**Issue by wyk190576528** [pujiaxin33/JXPagingView#405]
添加sectionHeaderTopPadding属性后，xcode13以下的版本，编译不了，建议添加条件判断语句
#if defined(__IPHONE_15_0) && (__IPHONE_OS_VERSION_MAX_ALLOWED >= __IPHONE_15_0)
        if (@available(iOS 15.0, *))
        {
            _tableView.sectionHeaderTopPadding = 0;
        }
#endif

**Comment by HLTangbinbin** [comment]
一样遇到了，swift下如何改？

**Comment by pujiaxin33** [comment]
用最新的2.1.2试一下呢？
