### ISSUE TITLE
无障碍模式适配

### ISSUE THREAD

**Issue by Taeyss** [pujiaxin33/JXPagingView#406]
**bug描述**
在无障碍模式下，使用Swift或者OC版本的分类视图都有同样的问题，比如，列表是VC的Demo，子VC的列表无法三指上下滚动，Cell无法聚焦，严重影响无障碍用户的使用

**版本号**
1.JXPagingView版本号：2.0.12
2.OC还是Swift版本：swift
3.手机系统版本号：15.0
4.手机型号: iPhone 11

**复现步骤**
开启旁白模式，点击列表是VC示例，聚焦分类”爱好“，三指无法上下滑动，列表里的Cell无法聚焦

**Comment by pujiaxin33** [comment]
没有无障碍的开发经验，你能通过Pull Request进行修复吗？

**Comment by lyb5834** [comment]
我根据作者的框架改了一个适配无障碍的版本 [YBPagerView](https://github.com/lyb5834/YBPagerView) 
因为涉及最底层scrollView 的变更，所以没有提 Pull Request

**Comment by pujiaxin33** [comment]
> 我根据作者的框架改了一个适配无障碍的版本 [YBPagerView](https://github.com/lyb5834/YBPagerView) 因为涉及最底层scrollView 的变更，所以没有提 Pull Request

感谢 @lyb5834 的开源。
