### ISSUE TITLE
JXPagingViewListViewDelegate 报错

### ISSUE THREAD

**Issue by HLTangbinbin** [pujiaxin33/JXPagingView#407]
使用pod方式引入：
_报错：Cannot find type 'JXPagingViewListViewDelegate' in scope
![image](https://user-images.githubusercontent.com/17370016/140919968-10bb54c8-afa8-46ac-a097-ecdc61a54b19.png)
![image](https://user-images.githubusercontent.com/17370016/140920167-baa4d760-d6eb-4761-aaee-c0b1d7fc1bd2.png)

Swift
JXPagingView 2.1.1
Xcode 12.4 
模拟器 iPhone 12 Pro （iOS 14）

不使用pod，直接copy Example里的JXPagingView文件后，按照现有代码导入，编译成功。

**Comment by pujiaxin33** [comment]
请在使用的地方导入`import JXPagingView`
