### ISSUE TITLE
你好,如何监听listContainerView的左右滚动?

### ISSUE THREAD

**Issue by xyl-private** [pujiaxin33/JXPagingView#408]
**Feature描述**
请简单描述你想要的效果：
做自定义的JXCategoryView,想要上下联动,但是没有找到,下面容器左右滚动的监听方法

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
JXPagingListContainerView类的`delegate: JXPagingListContainerViewDelegate?`，其中`func listContainerViewDidScroll(_ listContainerView: JXPagingListContainerView) {}`代理方法可以监听左右滚动
