### ISSUE TITLE
当悬浮高度设置超过导航栏高度后，下边会出现遮挡，拉不到底部。

### ISSUE THREAD

**Issue by teaplant** [pujiaxin33/JXPagingView#411]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**

self.pagerView.pinSectionHeaderVerticalOffset = 高度，

这个高度超过导航栏高度后，下拉会出现遮挡。

**版本号**
1.JXPagingView版本号：最新版
2.OC还是Swift版本： OC
3.手机系统版本号： iOS15
4.手机型号：iphone 13   iphone8等

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by LoSenTrad** [comment]
@teaplant  我也遇到这情况了 有处理方案?

**Comment by 274737258** [comment]
同样遇到了怎么解决啊

**Comment by DongfengWang123** [comment]
我也遇到了同样的问题呀!

**Comment by pujiaxin33** [comment]
在最新的iPhone OS上，比如iOS 17 也会有这个问题吗？

**Comment by teaplant** [comment]
当时已解决，是配置的问题，具体什么配置，时间过久已经忘了
