### ISSUE TITLE
15.1 版本大量crash

### ISSUE THREAD

**Issue by xiaof631** [pujiaxin33/JXPagingView#412]
OS Version:          iPhone OS 15.1 (19B74)
Release Type:        User
Baseband Version:    1.15.02
Report Version:      104

Exception Type:  EXC_CRASH (SIGKILL)
Exception Codes: 0x0000000000000000, 0x0000000000000000
Exception Note:  EXC_CORPSE_NOTIFY
Triggered by Thread:  0

Thread 0 name:
Thread 0 Crashed:
0   libdispatch.dylib             	0x0000000181b55dc8 DYLD-STUB$$objc_lookUpClass + 16
1   UIKitCore                     	0x000000018443c3f8 -[UIView nextResponder] + 36 (UIView.m:4862)
2   UIKitCore                     	0x0000000184612e24 -[UIResponder _responderWindow] + 28 (UIResponder.m:1190)
3   UIKitCore                     	0x0000000184612e3c -[UIResponder _responderWindow] + 52 (UIResponder.m:1190)
4   UIKitCore                     	0x00000001844e9d60 -[UIView(Internal) _firstResponder] + 28 (UIView.m:16223)
5   UIKitCore                     	0x00000001845f19c8 -[UIResponder isFirstResponder] + 32 (UIResponder.m:512)
6   UIKitCore                     	0x00000001847763f0 -[UIView(Hierarchy) _willMoveToWindow:] + 568 (UIView.m:12104)
7   UIKitCore                     	0x0000000184475290 _makeSubTreePerformSelector + 456 (UIView.m:12179)
8   UIKitCore                     	0x00000001844752ac _makeSubTreePerformSelector + 484 (UIView.m:12182)
9   UIKitCore                     	0x00000001844387d0 __UIViewWillBeRemovedFromSuperview + 776 (UIView.m:11590)
_10  UIKitCore                     	0x0000000184467bc8 -[UIView(Hierarchy) removeFromSuperview] + 96 (UIView.m:11669)
11  JXPagingView                  	0x000000010689238c -[JXPagerListContainerView collectionView:cellForItemAtIndexPath:] + 25484 (JXPagerListContainerView.m:262)_
12  UIKitCore                     	0x00000001845e45a0 -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 1020 (UICollectionView.m:2938)
13  UIKitCore                     	0x00000001844ddaf0 -[UICollectionView _updateVisibleCellsNow:] + 4224 (UICollectionView.m:4520)
14  UIKitCore                     	0x0000000184431630 -[UICollectionView layoutSubviews] + 320 (UICollectionView.m:5236)
15  UIKitCore                     	0x0000000184443ed8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2620 (UIView.m:18347)
16  QuartzCore                    	0x0000000185b9fe24 CA::Layer::layout_if_needed(CA::Transaction*) + 536 (CALayer.mm:10038)
17  UIKitCore                     	0x00000001844a8548 -[UIView(Hierarchy) layoutBelowIfNeeded] + 552 (UIView.m:12782)
18  UIKitCore                     	0x000000018442a268 +[UIView(Animation) performWithoutAnimation:] + 104 (UIView.m:14521)
19  UIKitCore                     	0x000000018453ea24 -[UITableView _createPreparedCellForGlobalRow:withIndexPath:willDisplay:] + 2132 (UITableView.m:16262)
20  UIKitCore                     	0x000000018473db18 -[UITableView _updateVisibleCellsForRanges:createIfNecessary:] + 748 (UITableView.m:3088)
21  UIKitCore                     	0x00000001845645ec -[UITableView _updateVisibleCellsNow:] + 1396 (UITableView.m:3225)
22  UIKitCore                     	0x00000001844338a8 -[UITableView layoutSubviews] + 456 (UITableView.m:10380)
23  UIKitCore                     	0x0000000184443ed8 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 2620 (UIView.m:18347)
24  QuartzCore                    	0x0000000185b9fe24 CA::Layer::layout_if_needed(CA::Transaction*) + 536 (CALayer.mm:10038)
25  QuartzCore                    	0x0000000185b92644 CA::Layer::layout_and_display_if_needed(CA::Transaction*) + 144 (CALayer.mm:2480)
26  QuartzCore                    	0x0000000185ba6c6c CA::Context::commit_transaction(CA::Transaction*, double, double*) + 524 (CAContextInternal.mm:2586)
27  QuartzCore                    	0x0000000185baf560 CA::Transaction::commit() + 680 (CATransactionInternal.mm:449)
28  QuartzCore                    	0x0000000185b91db8 CA::Transaction::flush_as_runloop_observer(bool) + 100 (CATransactionInternal.mm:941)
29  UIKitCore                     	0x00000001847f92e0 _UIApplicationFlushCATransaction + 76 (UIApplication.m:0)
30  UIKitCore                     	0x0000000184a937d8 _UIUpdateSequenceRun + 84 (_UIUpdateSequence.mm:112)
31  UIKitCore                     	0x000000018510d008 schedulerStepScheduledMainSection + 144 (_UIUpdateCycleScheduler.m:1174)
32  UIKitCore                     	0x000000018510c5f8 runloopSourceCallback + 60 (_UIUpdateCycleScheduler.m:1262)
33  CoreFoundation                	0x0000000181ecb020 __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 28 (CFRunLoop.c:1972)
34  CoreFoundation                	0x0000000181edbce0 __CFRunLoopDoSource0 + 208 (CFRunLoop.c:2016)
35  CoreFoundation                	0x0000000181e15fe8 __CFRunLoopDoSources0 + 268 (CFRunLoop.c:2053)
36  CoreFoundation                	0x0000000181e1b7f4 __CFRunLoopRun + 820 (CFRunLoop.c:2951)
37  CoreFoundation                	0x0000000181e2f3b8 CFRunLoopRunSpecific + 600 (CFRunLoop.c:3268)
38  GraphicsServices              	0x000000019d7bf38c GSEventRunModal + 164 (GSEvent.c:2200)
39  UIKitCore                     	0x00000001847cf6a8 -[UIApplication _run] + 1100 (UIApplication.m:3493)
40  UIKitCore                     	0x000000018454e7f4 UIApplicationMain + 2092 (UIApplication.m:5046)
41  AnyWidgets                    	0x0000000104ed0e1c main + 1723932 (main.m:18)
42  dyld                          	0x0000000106409a24 start + 520 (dyldMain.cpp:876)

Thread 1:
0   libsystem_pthread.dylib       	0x00000001f2a31e8c start_wqthread + 0

**Comment by wangjinshan** [comment]
这个问题找到愿意了吗

**Comment by pujiaxin33** [comment]
如何复现呢？
