### ISSUE TITLE
请问下JXPagingListContainerView如何滑动至指定的index

### ISSUE THREAD

**Issue by Gaozn** [pujiaxin33/JXPagingView#414]
我只使用了JXPagingListContainerView这个类。
我找到didClickSelectedItem这个方法，断点都会走，但是页面没任何反应
public func didClickSelectedItem(at index: Int) {
        guard checkIndexValid(index) else {
            return
        }
        willAppearIndex = -1
        willDisappearIndex = -1
        if currentIndex != index {
            listWillDisappear(at: currentIndex)
            listWillAppear(at: index)
            listDidDisappear(at: currentIndex)
            listDidAppear(at: index)
        }
    }

**Comment by Gaozn** [comment]
我尝试添加了这个方法来实现，不知道会不会有什么影响？
public func didClickSelectedItem(at index: Int, without:Bool=true) {
        if without{
            if self.type == .collectionView{
                self.collectionView.scrollToItem(at: IndexPath(item: index, section: 0), at: .centeredVertically, animated: true)
            }else{
                let sx = scrollView.bounds.size.width*CGFloat(index)
                scrollView.setContentOffset(CGPoint(x:sx, y: 0), animated: true)
            }
        }
        self.didClickSelectedItem(at: index)
    }

**Comment by z234009184** [comment]
the same issue

**Comment by J0nphy** [comment]
同样的问题，这个需求很大啊！

**Comment by roMummy** [comment]
这样子做
```
- (void)switchSubPage:(NSInteger)index {
    UIScrollView *contentScrollView = self.pagerView.listContainerView.contentScrollView;
    CGPoint offset = CGPointMake(index*contentScrollView.bounds.size.width, 0);
    [contentScrollView setContentOffset:offset animated:true];
    
    [self.pagerView.listContainerView didClickSelectedItemAtIndex:index];
}
```

**Comment by pujiaxin33** [comment]
可以通过segmentedView的`func selectItemAt(index: Int) `方法，实现选中某个index。OC版本就是categoryView的`- (void)selectItemAtIndex:(NSInteger)index;`方法
