### ISSUE TITLE
个人主页手势返回时 页面可以拖动

### ISSUE THREAD

**Issue by liwei5544** [pujiaxin33/JXPagingView#418]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**

https://user-images.githubusercontent.com/25995237/146865578-f1ea95f6-bd0e-4e23-94a1-5788008adfc5.mp4

**Comment by liwei5544** [comment]
搞定

**Comment by uclort** [comment]
> 搞定

请问是怎么搞定的，也发现这个问题了。

**Comment by znblyj** [comment]
> > 搞定
> 
> 请问是怎么搞定的，也发现这个问题了。

    override func viewDidLoad() {
        super.viewDidLoad()
   
        pagingView.mainTableView.gestureDelegate = self
    }

  func mainTableViewGestureRecognizer(_ gestureRecognizer: UIGestureRecognizer, shouldRecognizeSimultaneouslyWith otherGestureRecognizer: UIGestureRecognizer) -> Bool {
        
        guard let panGesture = gestureRecognizer as? UIPanGestureRecognizer else {
            return false
        }

        let velocity = panGesture.velocity(in: view)

        // 横向右滑时，不允许同时响应
        // 优先系统侧滑返回
        if abs(velocity.x) > abs(velocity.y),
           velocity.x > 0 {
            return false
        }

        // 其余情况允许 simultaneous
        return true
    }
