### ISSUE TITLE
滚动到当前列表的某个cell

### ISSUE THREAD

**Issue by WHDevLab** [pujiaxin33/JXPagingView#419]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by WHDevLab** [comment]
并将headerview滚动出屏幕，像正常手滑一样

**Comment by smallgirl** [comment]
解决了吗？

**Comment by chinghoi** [comment]
同求方案

**Comment by chinghoi** [comment]
同求方案

**Comment by jifengchao** [comment]
同求方案

**Comment by pujiaxin33** [comment]
请参考OC example中的【滚动到当前列表的某个cell】示例。
