### ISSUE TITLE
JXPagingSmoothView中的KVO监听contentOffset、contentSize会出现递归情况，导致crash

### ISSUE THREAD

**Issue by HellotalkXJP** [pujiaxin33/JXPagingView#420]
**bug描述**
左右滑动列表，会出现KVO递归，导致crash

**版本号**
1.JXPagingView版本号：最新版本
2.OC还是Swift版本：swift
3.手机系统版本号：15.2
4.手机型号：模拟器 iPhone12

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagingSmoothView
2.具体的操作步骤是：左右滑动下面的列表

**截图、GIF**
![image](https://user-images.githubusercontent.com/37888366/147239755-c1d795a1-0c42-4682-8083-3ee058434b34.png)
![simulator_screenshot_71129AF7-910C-4836-9E3D-D905018B9F3D](https://user-images.githubusercontent.com/37888366/147240041-56d4fa7d-3d7a-4292-85d0-588b37ea705d.png)

**Comment by pujiaxin33** [comment]
因为内部已经添加了KVO监听contentOffset和contentSize，不建议外部再做同样的操作。
