### ISSUE TITLE
JXPagerSmoothView的list controller里面添加其他控件

### ISSUE THREAD

**Issue by UknowHui** [pujiaxin33/JXPagingView#422]
**Feature描述**
请简单描述你想要的效果：？
JXPagerSmoothView的list controller里面,只有添加UIScrollView相关的控件,能不能添加其他的
随着列表滚动,到最上面能够在pinHeader下面悬停
**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？
JXPagerView是很容易实现,如果能结合JXPagerSmoothView的滑动效果就是最完美的

**Comment by pujiaxin33** [comment]
是的，你可以将segmentedView嵌入一个UIView，把该UIView通过viewForPinSectionHeader方法返回。然后你就可以在容器内部去自定义segmentedView的frame了，以及添加其他视图。
