### ISSUE TITLE
segmentView的frame的x和width无法自定义

### ISSUE THREAD

**Issue by liuxinghudiejie** [pujiaxin33/JXPagingView#424]
![image](https://user-images.githubusercontent.com/14884778/149918450-fea1c253-9fd8-4bba-b53d-92928dd5aefa.png)
第一步设置了segmentView的frame，输出是（50，0，328，50）
然后
![image](https://user-images.githubusercontent.com/14884778/149918750-0333ba14-c309-4ad5-9e55-9f94335724e6.png)
走完delegate这里，进入JXSegmentedView的layoutSubviews
![image](https://user-images.githubusercontent.com/14884778/149918927-6461cb56-abcd-4542-a061-c8deb7e65460.png)
这个时候frame已经变了，输出是（0，300，428，50），y的300没问题，我设置的header高度是300，但是x和w就已经变了，变成全屏宽了

**Comment by pujiaxin33** [comment]
是的，具体来说应该是悬浮容器视图无法指定x和width。你可以将segmentedView嵌入一个UIView，把该UIView通过viewForPinSectionHeader方法返回。然后你就可以在容器内部去自定义segmentedView的frame了。
