### ISSUE TITLE
底部列表视图滑动后，顶部菜单JXCategoryTitleImageView的selectedImage显示为未选中

### ISSUE THREAD

**Issue by YangXiaoYangY** [pujiaxin33/JXPagingView#425]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
JXPagerView 设置的frame并非屏宽，二十如截图中黄色部分，当底部视图滑动到某个列表视图后，顶部菜单随之联动，但顶部菜单显示的选中状态中文字和指示器都正确，唯独image为未选中，且顶部菜单代理方法- (void)categoryView:(JXCategoryBaseView *)categoryView didSelectedItemAtIndex:(NSInteger)index中的index值也不与真正选中的值匹配，怀疑是否底部滑动视图时计算的当前选中页数值不对，是否与JXPagerView 设置的frame并非屏宽有关

**版本号**
1.JXPagingView版本号：
pod 'JXCategoryView', '~> 1.5.9'
pod 'JXPagingView/Pager', '~> 2.1.2'
2.OC还是Swift版本：？
OC
3.手机系统版本号：？
15.1,其他版本也有问题
4.手机型号：？

**截图、GIF**

![image](https://user-images.githubusercontent.com/86941549/151529323-afcf4615-de1c-45a0-8653-0de084cca700.png)

**Comment by pujiaxin33** [comment]
这是属于JXCategoryView库的问题，已修复。
