### ISSUE TITLE
三级联动的问题

### ISSUE THREAD

**Issue by songxing10000** [pujiaxin33/JXPagingView#426]
**Feature描述**
三级联动

**参考效果**
![image](https://user-images.githubusercontent.com/10040131/153417663-97d3f47e-47b9-453c-a947-413ee20bdd17.png)

**其他补充**
看了demo中的两级联动，感觉要实现三级的有点麻烦。不知道现有框架能实现这种三级联动不

**Comment by f2yu** [comment]
我也想知道这个问题

**Comment by songxing10000** [comment]
完善下需求：
支持左右滑动
1、选好一级课程分类后才会展示二级课程分类（如果有），选好二级课程分类才会展示三级课程分类（如果有）

2、课程分类导航以UI的设计为准

**Comment by pujiaxin33** [comment]
> 完善下需求： 1、支持左右滑动 2、选好一级课程分类后才会展示二级课程分类（如果有），选好二级课程分类才会展示三级课程分类（如果有） 3、页面在向上滑动的时候，最底层的课程分类吸顶。例如：该课程分类有3级，则3级分类吸顶。
> 
> 目前简陋的做法： 一个`tableView` 三个`JXCategoryTitleView` 需要滑动的(可能是菜单一/二)放在`tableHeaderView` 需要悬浮的(可能是菜单一/二/三)放`sectionHeader` `- (nullable UIView *)tableView:(UITableView *)tableView viewForHeaderInSection:(NSInteger)section;`

可以参考这个思路多尝试一下。
