### ISSUE TITLE
isListHorizontalScrollEnabled 不生效

### ISSUE THREAD

**Issue by loveuqian** [pujiaxin33/JXPagingView#43]
![image](https://user-images.githubusercontent.com/9745332/50623045-0a3a4480-0f4d-11e9-86f3-02040861f060.png)
打点看了，设置属性后，并没有进入 set 方法

**Comment by loveuqian** [comment]
- (void)setIsListHorizontalScrollEnabled:(BOOL)isListHorizontalScrollEnabled

原来是你写错了一个 I 。。。

**Comment by pujiaxin33** [comment]
谢谢反馈，已修复🤝
可能是全局替换属性名的时候没有注意

**Comment by pujiaxin33** [comment]
已更新

**Comment by loveuqian** [comment]
还有个问题，为什么 tableHeaderViewInPagerView 使用 xib 会使尺寸不正确

**Comment by pujiaxin33** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    你需要把xib生成的headerView放到另一个容器UIView里面，然后把容器UIView当做headerView给pagerView用
    
        
            
        
    
    
        
            
        
    
    
          
        
            
    
        font{
            line-height: 1.6;
        }
    


        
    
     
    

    在2019年01月3日 17:05，王胜峰<notifications@github.com> 写道： 


还有个问题，为什么 tableHeaderViewInPagerView 使用 xib 会使尺寸不正确
