### ISSUE TITLE
添加UISearchController的问题

### ISSUE THREAD

**Issue by cleven1** [pujiaxin33/JXPagingView#431]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
JXPagingView/Paging (2.1.2)
JXSegmentedView (1.3.0)

2.OC还是Swift版本：Swift
3.手机系统版本号：13.3
4.手机型号：全型号

**复现步骤**
1. 遇到问题的相关效果、类是：JXSegmentedView
2.具体的操作步骤是：
在NestViewController中添加一个UISearchController 然后当searchBar成为第一响应着的时候显示异常, 导航栏不见了, 详情见GIF

**截图、GIF**
提供bug出现时的截图或者GIF。
<img width="1400" alt="image" src="https://user-images.githubusercontent.com/18156348/158133589-9d711536-b7e0-4746-b022-3894fefd43d5.png">
![ScreenRecorderProject1](https://user-images.githubusercontent.com/18156348/158134532-6e108e02-e429-4147-a941-2a68f42c1e70.gif)

**Comment by pujiaxin33** [comment]
不支持在嵌套的时候又实用UISearchController，建议自己实用UISearchBar实现需求。
