### ISSUE TITLE
我在使用JXPagingSmoothView的时候，childe是UICollectionView，出现崩溃，毕现

### ISSUE THREAD

**Issue by SunshineBrother** [pujiaxin33/JXPagingView#434]
我UICollectionView注册了不同的cell，每一个UICollectionView显示的cell可能不同，在切换的时候出现崩溃。使用JXPagingView正常

[UICollectionViewRecursion] <UICollectionView: 0x10d00a000; frame = (0 0; 375 732); clipsToBounds = YES; gestureRecognizers = <NSArray: 0x2827dd860>; layer = <CALayer: 0x2829d81c0>; contentOffset: {0, -161}; contentSize: {375, 571.22000000000003}; adjustedContentInset: {732, 0, 0, 0}; layout: <UICollectionViewFlowLayout: 0x10890f2a0>; dataSource: <HomeViewController: 0x10890f870>> is stuck in its update/layout loop. See previous logs in the "UICollectionViewRecursionCategory" to find callers that scheduled a recursive update

 Assertion failure in -[UICollectionView _setNeedsVisibleCellsUpdate:withLayoutAttributes:], UICollectionView.m:1511

**Comment by pujiaxin33** [comment]
看日志可能是触发了递归刷新页面，但是我通过demo测试多种collection cell的情况，并没有出现你说的这种情况，建议你再检查一下你的配置代码。
