### ISSUE TITLE
JXPagingSmoothView时，列表当中有悬浮的sectionheader，这些header空了很大距离

### ISSUE THREAD

**Issue by Lovezysong** [pujiaxin33/JXPagingView#439]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by bigcoww** [comment]
同有此问题，tableView 的sectionHeaderView 上面会多出一段属于tableView的间隔

**Comment by bigcoww** [comment]
在 CategoryNestPaging demo中，直接去BaseViewController 的ListViewController 里添加SectionHeadView, sectionHeadView上面出现一段距离
![IMG_7605](https://user-images.githubusercontent.com/59868590/180382497-81fae080-6345-4661-955a-f30d6a677348.PNG)

如图，蓝色为天机的组头，上面有一段白色间隔

**Comment by bigcoww** [comment]
@Lovezysong 这个是啥问题

**Comment by JiaYunGenius** [comment]
在JXPagerView.m里49行增加这段代码
`if (@available(iOS 15.0, *)) {
    self.mainTableView.sectionHeaderTopPadding = 0;
}`

**Comment by pujiaxin33** [comment]
已修复
