### ISSUE TITLE
我们底部collectionView是一个瀑布流，不用你写的JXPagerSmoothCollectionFlowLayout用别人写好的瀑布流layout可以么

### ISSUE THREAD

**Issue by Liyongcong** [pujiaxin33/JXPagingView#444]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by shenxiang11** [comment]
所以可以吗？关issue 前不能评论下？
