### ISSUE TITLE
某些情况下 listContinerView 的大小和 cell 的大小不一致，导致一部分内容无法完全显示到屏幕上。

### ISSUE THREAD

**Issue by SAGESSE-CN** [pujiaxin33/JXPagingView#446]
**bug描述**
某些情况下 listContinerView 的大小和 cell 的大小不一致，导致一部分内容无法完全显示到屏幕上。

具体原因是, 系统会动态调整Cell的大小(系统调用layoutSubviews, 不会调用reloadData)
但 JXPagerView 严重依赖 [cellForRow](https://github.com/pujiaxin33/JXPagingView/blob/9c5e9a72fcd0f565cf379331d339a5a6e5947932/Sources/JXPagerView/JXPagerView.m#L194) 来更新大小, 这就导致listContainerView比Cell大, 一部分内容超出cell的区域

解决方案:
给listContainerView添加自动autoresizing mask 让它跟随cell的大小变更即可
```oc
self.listContainerView.autoresizingMask = UIViewAutoresizingFlexibleWidth | UIViewAutoresizingFlexibleHeight;
```

**版本号**
1.JXPagingView版本号：2.1.2
2.OC还是Swift版本：OC/Swift 5.4
3.手机系统版本号：iOS 15
4.手机型号：iPhone Xr
![origin_img_v2_2435f244-b2fc-4dc2-afd4-959653a5bc7g](https://user-images.githubusercontent.com/6903353/172087120-8b8162e9-0125-467c-82f3-14d4481cf307.jpg)

**Comment by pujiaxin33** [comment]
请使用最新版本，已经适配诸如横竖屏旋转的情况。
