### ISSUE TITLE
双击分类标题会出现列表切换卡顿问题，百分百复现

### ISSUE THREAD

**Issue by YaoWeiCheng** [pujiaxin33/JXPagingView#448]
**bug描述**
使用JXCategoryTitleView以及JXPagerView组合使用后，双击JXCategoryTitleView的标题会出现列表切换卡顿问题，这种情况当有十几个标题数据后就会百分百触发，触发前提要将contentScrollViewClickTransitionAnimationEnabled = YES;

**版本号**
1.JXPagingView版本号：2.1.2.
2.OC还是Swift版本：OC
3.手机系统版本号：15.0.2
4.手机型号：iPhone13

**复现步骤**
使用JXCategoryTitleView以及JXPagerView组合使用后，双击JXCategoryTitleView的标题会出现列表切换卡顿问题，这种情况当有十几个标题数据后就会百分百触发，触发前提要将contentScrollViewClickTransitionAnimationEnabled = YES; 来回不断切换不同的标题就会触发了

**截图、GIF**
双击切换点击标题就会触发图片情况
![IMG_0327](https://user-images.githubusercontent.com/26733378/173544488-e52d21d4-2a98-47d3-84c7-0a35eaf1672d.PNG)

提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
我在iOS 17系统测试并没有出现你遇到的问题，你用的是哪个版本的系统呢？
