### ISSUE TITLE
左右滚动pin headerview高度问题

### ISSUE THREAD

**Issue by mxpasser** [pujiaxin33/JXPagingView#45]
@pujiaxin33 你好，使用了你的这个库解决了页面布局的一些问题，谢谢。
同时有个问题想请教，就是在左右滚动切换时，如果pin headerview需要动态的调整高度，如何处理？ 
如图，比如节目和生活下pin headerview是80，当切换到动态下时为45，这时候需要怎么调整一下？谢谢！

![image](https://user-images.githubusercontent.com/3272620/50766620-e4969d80-12b4-11e9-9073-cb1b8f6e0771.png)

**Comment by pujiaxin33** [comment]
切换不同的item要改变pin headerView高度这个需求。
为什么会有这么奇葩的需求？
先不讨论如何实现，只是这个高度最终肯定是跳变的，就是说重节目切换到生活会reload一下，页面就会跳变，不然怎么改变高度呢？
