### ISSUE TITLE
加载更多，使用MJRefreshBackNormalFooter，展示bug

### ISSUE THREAD

**Issue by leblanc-zx** [pujiaxin33/JXPagingView#450]
加载更多功能，使用MJRefreshBackNormalFooter，endRefreshing后，界面依然会展示MJ的footer，无法隐藏;
demo中也是有这样的问题。

**Comment by pujiaxin33** [comment]
> .contentInsetAdjustmentBehavior = UIScrollViewContentInsetAdjustmentNever; 试试

已按照该方法优化demo。
