### ISSUE TITLE
比如JXPagingViewDelegate的tableHeaderView的高度可以设置，那么能相应的设置pagingView的子列表cell的高度，甚至为0 或者不显示。简单来说就是根据特定需求要么只显示显示tableHeaderView，要么只显示pagingView的子列表和PinSectionHeader，要么都显示。

### ISSUE THREAD

**Issue by TML007** [pujiaxin33/JXPagingView#452]
**Feature描述**
比如JXPagingViewDelegate的tableHeaderView的高度可以设置，那么能相应的设置pagingView的子列表cell的高度，甚至为0 或者不显示。简单来说就是根据特定需求要么只显示显示tableHeaderView，要么只显示pagingView的子列表和PinSectionHeader，要么都显示。

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
“pagingView的子列表cell的高度“ 由内部自动计算，因为该cell是list的容器，它的高度必须是悬浮分段控制器的底部 到 屏幕底部之间的高度。
