### ISSUE TITLE
SmoothListViewController 的Cell无法自适应高度

### ISSUE THREAD

**Issue by XiaoPangTang** [pujiaxin33/JXPagingView#457]
**bug描述**
SmoothListViewController 的Cell无法自适应高度

**版本号**
1.JXPagingView版本号：1.6.1
2.OC还是Swift版本：OC
3.手机系统版本号：15.0
4.手机型号：7 Plus

**复现步骤**
1. 遇到问题的相关效果、类是：SmoothListViewController
2.具体的操作步骤是：
Demo，进入滚动延续（PagerHeader 列表），修改Demo代码，任意在SmoothListViewController 里面的tableViewCell写自适应view，配合UITableViewAutomaticDimension && estimatedRowHeight，cell的自适应高度无效。
**截图、GIF**
任意写内容自测即可（几行代码，传图不方便，不传了）

**Comment by aSynch1889** [comment]
你好，你这个问题解决了嘛，我这边出现同样的情况。
同时发现cell布局在这个tableview中就会报警告
"<NSLayoutConstraint:0x282638e60 'UIView-Encapsulated-Layout-Height' UITableViewCellContentView:0x11162c660.height == 44   (active)>"
导致高度始终为44。

**Comment by xiaoliang1410** [comment]
请问解决了吗？怎么解决的？

**Comment by pujiaxin33** [comment]
为了修复list内容过少，不足一屏的时候，显示会出现问题。所以，内部对list tableView做了属性覆写。请自己计算cell 高度。
```
            if list?.listScrollView().isKind(of: UITableView.self) == true {
                (list?.listScrollView() as? UITableView)?.estimatedRowHeight = 0
                (list?.listScrollView() as? UITableView)?.estimatedSectionHeaderHeight = 0
                (list?.listScrollView() as? UITableView)?.estimatedSectionFooterHeight = 0
            }
```
