### ISSUE TITLE
请问什么时候可以支持 PagingView 嵌套 PagingView

### ISSUE THREAD

**Issue by uclort** [pujiaxin33/JXPagingView#458]
看其他相关 issue 作者说不支持嵌套使用，有朋友这么用会偶现崩溃。
想问一下作者有没有计划让 PagingView 可以嵌套使用？

**Comment by csjlengxiang** [comment]
PagingView 可以嵌套 PagingSmoothView

**Comment by pujiaxin33** [comment]
目前没有计划支持JXPagingView嵌套JXPagingView，遇到了一些很难解决的问题点。
