### ISSUE TITLE
由于多个scrollview的嵌套，点击statusBar不能正确的滚动到顶部

### ISSUE THREAD

**Issue by Junnor** [pujiaxin33/JXPagingView#46]
scrollView 属性：
`   
     open var scrollsToTop: Bool // default is YES.
`
注释是：
 When the user taps the status bar, the scroll view beneath the touch which is closest to the status bar will be scrolled to top, but only if its `scrollsToTop` property is YES, its delegate does not return NO from `-scrollViewShouldScrollToTop:`, and it is not already at the top. On iPhone, we execute this gesture only if there's one on-screen scroll view with `scrollsToTop` == YES. If more than one is found, none will be scrolled.

// -------------------------------------------------------

首先非常感谢作者写了该开源项目，在实际的项目中节约了很多时间。

有一个问题：

如果子item也滚动到顶部的话，此时点击 status bar 是没有反应的，因为 mainTableView 和该 itemScrollView 的 scrollsToTop 都是true, 系统不知道处理哪一个了。希望题主可以把这个小issue加进去😄。

我在实际项目的处理方式是：

1 在 AppDelegate.swift 添加通知:

    override func touchesBegan(_ touches: Set<UITouch>, with event: UIEvent?) {
        super.touchesBegan(touches, with: event)
        if let touch = touches.first {
            let statusBarHeight = xxxxxx
            if touch.location(in: nil).y > statusBarHeight {
                return
            }
            NotificationCenter.default.post(name: notificationName, object: nil)
        }
    }

2 在相关的ViewController设置：

    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        NotificationCenter.default.addObserver(self, selector: #selector(scrollToTopNoti), name: .notificationName, object: nil)
    }
    
    @objc private func scrollToTopNoti() {
        item0.scrollView.contentOffset = .zero
        item1.scrollView.contentOffset = .zero
        item2.scrollView.contentOffset = .zero
        
        pagingView.mainTableView?.scrollRectToVisible(topFrame, animated: true)
    } 

这样处理以后点击status bar 就能正常滚动到顶部了，希望题主可以考虑一下怎样在pods实现类似的功能。

**Comment by pujiaxin33** [comment]
谢谢反馈，已经支持列表点击状态栏滚动到顶部了

**Comment by cgwangding** [comment]
@pujiaxin33 麻烦问一下这个 “列表点击状态栏滚动到顶部” 的代码在哪里？
