### ISSUE TITLE
   func pagingView(_ pagingView: JXPagingView, initListAtIndex index: Int) -> JXPagingViewListViewDelegate这样的声明不是一个好的设计方式

### ISSUE THREAD

**Issue by MrXuxxx** [pujiaxin33/JXPagingView#463]
func pagingView(_ pagingView: JXPagingView, initListAtIndex index: Int) -> JXPagingViewListViewDelegate将返回值限定为不可选类型，这样，一旦出现可变场景，使用起来十分别扭。

**Comment by pujiaxin33** [comment]
【一旦出现可变场景】具体指的是什么呢？

**Comment by pujiaxin33** [comment]
这个是根据index返回对应的list。
