### ISSUE TITLE
pagingView.listContainerView的width自定义问题

### ISSUE THREAD

**Issue by 979881765** [pujiaxin33/JXPagingView#465]
我想实现类似轮播图片一样，第二张图片的三分之一可以展示出来(比如当前显示的第一个列表，他的的右边也将下一个列表三分之一的的页面显示出来)，我尝试修改pagingView.listContainerView的宽度，但是无效，请问有什么方案可以实现这样的效果吗？

**Comment by pujiaxin33** [comment]
需要设置`initListPercent`属性，比如为0.3，那么就会在下一个列表出现超过30%的时候，加载下一个列表。
