### ISSUE TITLE
- (void)preferredProcessMainTableViewDidScroll:(UIScrollView *)scrollView  在个人项目有点问题

### ISSUE THREAD

**Issue by songhongkang** [pujiaxin33/JXPagingView#469]
![image](https://user-images.githubusercontent.com/13045795/207210563-aad5210c-1309-488e-b57b-4e74e0673b35.png)

https://user-images.githubusercontent.com/13045795/207211090-c923c0cd-9ee0-41a1-b98a-9903f5d51a8e.mp4

**Comment by songhongkang** [comment]
每次向上滑动    内部的tableview 的Y偏移量是是个很小的值 刚好大于 0,就执行  [self setMainTableViewToMaxContentOffsetY];
但是demo又不会,很诡异啊
  //当往上滚动mainTableView的headerView时，滚动到底时，修复listView往上小幅度滚动
        [self setMainTableViewToMaxContentOffsetY];

大哥能帮忙分析一下原因吗

**Comment by songhongkang** [comment]
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    !self.scrollCallback ?: self.scrollCallback(scrollView);
}

在listviewVC 忘记加上这句代码了，我擦

**Comment by joshiaProgram** [comment]
大佬，加了这句，还是有同样的问题，向上滑动一点点，就直接吸顶。
