### ISSUE TITLE
JXPagingView如何取消自动吸顶呢?

### ISSUE THREAD

**Issue by developerjet** [pujiaxin33/JXPagingView#472]
**Feature描述**
请问就是往上滚动的时候, 如何设置一定的距离才吸顶呢? 
现在的情况是: 只要一往上滚动一点点, 就自动吸顶了, 会有一种跳动的感觉;

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by pujiaxin33** [comment]
本身是没有自动吸顶的设计，请对比demo检查一下代码。

**Comment by Immmmmmortal1** [comment]
var listViewDidScrollCallback: ((UIScrollView) -> ())?
    deinit {
        listViewDidScrollCallback = nil
    }
    
    public func listView() -> UIView {
        return self.view
    }
    public func listScrollView() -> UIScrollView {
        return UIScrollView()
    }
    public func listViewDidScrollCallback(callback: @escaping (UIScrollView) -> ()) {
        self.listViewDidScrollCallback = callback
    }自动吸顶的原因,这个几个方法检查一下,scrollview对象没有回调,或者回调对象出错 特别是listViewDidScrollCallback这个回调实现
