### ISSUE TITLE
iOS 15.0的APP 起步pod 会报错

### ISSUE THREAD

**Issue by fanglinwei** [pujiaxin33/JXPagingView#479]
**bug描述**
iOS 15.0的APP 起步pod 会报错
linker command failed with exit code 1 (use -v to see invocation)

**版本号**
1.JXPagingView版本号：2.1.2
2.OC还是Swift版本：Swift
3.手机系统版本号：16.4.1
4.手机型号：iphone 13 pro

**复现步骤**
新建demo, 
``` ruby
platform :ios, '15.0'

target 'Demo' do

  use_frameworks!

  pod 'JXPagingView/Paging'

end
```

2. ```pod install ```

<img width="793" alt="image" src="https://github.com/pujiaxin33/JXPagingView/assets/16839723/865c1140-f645-4d2f-a6ae-62ba004700ad">

**Comment by pujiaxin33** [comment]
建议使用最新版本再试试。
