### ISSUE TITLE
JXPagingSmoothView 不支持 UITableView.automaticDimension

### ISSUE THREAD

**Issue by uclort** [pujiaxin33/JXPagingView#480]
经发现是 JXPagingSmoothView 289 行 (list?.listScrollView() as? UITableView)?.estimatedRowHeight = 0 的原因，请问是出于什么考虑必须设置 estimatedRowHeight = 0？

**Comment by xiaoliang1410** [comment]
请问解决了吗？怎么解决的？

**Comment by pujiaxin33** [comment]
是为了解决【JXPagingSmoothView处理内容过少的情况】
