### ISSUE TITLE
这嵌套太难用了，我第一个control需要嵌套，第二个不需要，无法实现

### ISSUE THREAD

**Issue by 542604974** [pujiaxin33/JXPagingView#481]
**Feature描述**
请简单描述你想要的效果：？

**参考效果**
如果你想要实现一个其他APP已有的效果：
1.参考APP名字：？
2.目标页面路径：？
3.目标效果截图：？

**其他补充**
关于目标效果的其他说明：？

**Comment by dlxflys** [comment]
可以使用 addChildViewController
