### ISSUE TITLE
方便把模块名换成和类名不一样的吗

### ISSUE THREAD

**Issue by fanlilinSaber** [pujiaxin33/JXPagingView#485]
我们的工程为了支持二进制兼容包，其中依赖了这个组件，但是开启了兼容 BUILD_LIBRARY_FOR_DISTRIBUTION 之后在 framework swiftinterface中会报错如下 
'JXPagerViewListViewDelegate' is not a member type of class 'JXPagingView.JXPagingView'
 
原因就是模块名和类名相同了，这个问题我这边已经验证过了
https://stackoverflow.com/questions/65798857/xcframeworks-swiftinterface-breaks-compile-when-imported-with-swift-package-ma

二进制包对我们很重要，希望作者能修改一下，谢谢。只要模块名和类名不一样就行。这个问题在 [HandyJSON](https://github.com/alibaba/HandyJSON)这提到过

**Comment by fanlilinSaber** [comment]
我好像已经找到对应的解决办法了 https://github.com/apple/swift/issues/64669

**Comment by tclxivan-ye** [comment]
@fanlilinSaber -no-verify-emitted-module-interface 这个似乎没生效？请问你这边解决方案是什么？
