### ISSUE TITLE
JXPagerSmoothView 调用reloaddata，pagerHeaderContainerView的父视图会被多次创建

### ISSUE THREAD

**Issue by yunjinghui123** [pujiaxin33/JXPagingView#487]
1、每次调用reloaddata，pagerHeaderContainerView的父视图都会重新创建一次
2、调用reloaddata，页面会回到顶部
![b921d8bb0a9466e7bdbdc53862a9521d](https://github.com/pujiaxin33/JXPagingView/assets/9649401/93ae1e5e-7787-4e29-9210-e93b4cb1ecb4)

**Comment by pujiaxin33** [comment]
> 1、是因为在cellForItemAtIndexPath中重新创建了listHeader，但是在reloaddata中并没有完全将上一个视图移除，在reloaddata中移除就可以 for (UIView *view in self.listHeaderDict.allValues) { [view removeFromSuperview]; } [self.listHeaderDict removeAllObjects]; 2、reloaddata中将self.currentPagerHeaderContainerViewY = 0;置为0所致，移除即可（不知道作者出于什么考虑）

已采用你的建议，进行了修复。
