### ISSUE TITLE
如果不使用[self.pagerView reloadData] 进行页面的刷新

### ISSUE THREAD

**Issue by XieHenry** [pujiaxin33/JXPagingView#491]
已解决。博主的功能很棒

**Comment by XieHenry** [comment]
已解决

**Comment by ZeroYoung1104** [comment]
怎么解决的？

**Comment by XieHenry** [comment]
> 怎么解决的？
            [self.pagerView resizeTableHeaderViewHeightWithAnimatable:YES duration:0 curve:UIViewAnimationCurveEaseInOut];
