### ISSUE TITLE
关于 pinSectionHeaderVerticalOffset 属性 和  [_pagingView reloadData];的联系 

### ISSUE THREAD

**Issue by ZeroYoung1104** [pujiaxin33/JXPagingView#492]
**Feature描述**
请简单描述你想要的效果：？
默认导航栏是透明效果 刚开始设置pinSectionHeaderVerticalOffset =导航的像素点   页面滑动页面 显示导航栏 JXCategoryTitleView悬停在导航底部  点击JXCategoryTitleView的菜单选项 进行网络请求 之后刷新 [_pagingView reloadData];  页面会执行滚动初始化位置 我想保留在滚动之后的位置 应该怎么处理 ？（我目前pinSectionHeaderVerticalOffset =0 发现执行[_pagingView reloadData] 可以保留当前位置 但是JXCategoryTitleView会被导航盖住 ）

**Comment by pujiaxin33** [comment]
目前没有办法达到你想要的效果，因为修复其他问题的在reloadData内部引入了该代码块：
```
if pinSectionHeaderVerticalOffset != 0 && mainTableView.contentOffset.y > CGFloat(pinSectionHeaderVerticalOffset) {
            mainTableView.contentOffset = .zero
        }
```
就导致list的滚动会被重置。
