### ISSUE TITLE
JXPagingViewListViewDelegate 不能在OC中使用

### ISSUE THREAD

**Issue by JqyModi** [pujiaxin33/JXPagingView#495]
**bug描述**
public protocol JXPagingViewListViewDelegate: NSObjectProtocol没有添加@objc修饰，在OC中导入库后无法找到对应的协议

**版本号**
1.JXPagingView 2.1.2
2.Swift

**截图、GIF**
![image](https://github.com/pujiaxin33/JXPagingView/assets/19703476/bc0e9ebe-7dc8-4289-b645-eef5c21067fc)

**Comment by pujiaxin33** [comment]
请使用OC版本的JXPagerView
