### ISSUE TITLE
如果使用MJRefresh,下拉刷新不会在CategoryView下面出来

### ISSUE THREAD

**Issue by Heisenbean** [pujiaxin33/JXPagingView#5]
还是从Nav下面出来的.
iPhone 8 Plus iOS 11.4

**Comment by pujiaxin33** [comment]
你好，我的demo里面有loadData的使用示例。参考这个修改一下呢？

**Comment by pujiaxin33** [comment]
请问你使用的是JXPagingListRefreshView类吗？参考demo里面的列表刷新呢

**Comment by Heisenbean** [comment]
是用的JXPagingListRefreshView初始化..
也是在参考Demo里的,ListView是UIView,里面有tableVew,tableView加的下拉刷新.
现在的问题是下拉刷新控件不会出现了

**Comment by pujiaxin33** [comment]
demo的列表刷新在iPhone 8 Plus iOS 11.4，是正常的吗？
如果方便的话，可以加我qq：317437084
