### ISSUE TITLE
动态PinSectionHeader高度问题

### ISSUE THREAD

**Issue by mxpasser** [pujiaxin33/JXPagingView#50]
@pujiaxin33 请教个问题，就是点击切换不同标签选项时，pageView reloadData后高度变短了，出现了黑边。如图，点击节目时PinSectionHeader=80然后再切换回来点击了动态PinSectionHeader=45，分别设置PinSectionHeader后，pageView reloadData后出现了黑边。。

![image](https://user-images.githubusercontent.com/3272620/51293843-7cca1a80-1a4b-11e9-92e6-5d50e0ed6151.png)

**Comment by pujiaxin33** [comment]
能提供一个能复现问题的demo吗

**Comment by mxpasser** [comment]
> 能提供一个能复现问题的demo吗

搞了一个demo，怎么发给你？

**Comment by pujiaxin33** [comment]
麻烦加下我的qq：317437084

**Comment by pujiaxin33** [comment]
最新版本已修复
