### ISSUE TITLE
位置记录问题

### ISSUE THREAD

**Issue by SPStore** [pujiaxin33/JXPagingView#500]
你这个框架不会记录滚动位置。
比如A页面滚动到第五行，再横向切换到B页面，B页面不论怎么滑动，再切换回A，A页面都应该停留在第五行，你这个每次都会恢复到第一行。有些主流app是会记录的，比如美团、微博

**Comment by pujiaxin33** [comment]
A页面滚动到第5行，切到B页面，滚动之后，如果往下滑动，显示了header视图。这个时候就会把所有列表（也就是A、B页面的contentoffset.y 更新为0，也就是置顶了），这就是你反馈中的没有记录滚动位置。
相反如果你切换到B页面，如果不显示header，再切换到A页面，这个时候A页面的位置是被记录了的，没有被重置。
