### ISSUE TITLE
在使用JXPagingView的时候，下面分类的子vc中添加了UITableView，并且设置了自动高度

### ISSUE THREAD

**Issue by xiaoliang1410** [pujiaxin33/JXPagingView#501]
在使用JXPagingView的时候，下面分类的子vc中添加了UITableView，并且设置了自动高度，这会导致子vc下面留了很多空白，这个怎么解决
![Uploading WX20240112-170131.png…]()

**Comment by YXMao** [comment]
同问

**Comment by pujiaxin33** [comment]
请使用最新版本，应该已经修复了。
