### ISSUE TITLE
单个界面有两个tableView联动问题

### ISSUE THREAD

**Issue by SunSevi** [pujiaxin33/JXPagingView#503]
**bug描述**
当调用!self.scrollCallback ?: self.scrollCallback(scrollView);这个block时，点击左边tableview,右边tableview滚动会失效，这个方法注掉后才可以滚动

**版本号**
1.JXPagingView版本号：2.1.2
2.OC还是Swift版本：OC
3.手机系统版本号：17.3.1
4.手机型号：15 promax

**复现步骤**
1. 遇到问题的相关效果、类是：JXPagerView
2.具体的操作步骤是：不滑动到最顶部，点击左边tableView，右边tableView[self.rightTableView scrollToRowAtIndexPath:[NSIndexPath indexPathForRow:0 inSection:_selectIndex] atScrollPosition:UITableViewScrollPositionTop animated:YES];这个方法调用无效

**截图、GIF**
提供bug出现时的截图或者GIF。

https://github.com/pujiaxin33/JXPagingView/assets/19682231/d0e4c119-07fc-4d20-8be1-b1cd6226db64

**Comment by seanLee** [comment]
你好，请问这个问题解决了吗？目前需要时间同样的需求

**Comment by qiaqiaxian** [comment]
同样问题，请问下是怎么解决的
