### ISSUE TITLE
JXPagingView的showsVerticalScrollIndicator设置不生效

### ISSUE THREAD

**Issue by chenlinyuan** [pujiaxin33/JXPagingView#509]
<img width="1509" alt="Snipaste_2024-04-22_17-12-26" src="https://github.com/pujiaxin33/JXPagingView/assets/3690117/12f1f0ed-6f39-4461-b867-ce65c740ea1a">

可能是因为没有使用automaticallyDisplayListVerticalScrollIndicator进行判断

**Comment by pujiaxin33** [comment]
showsVerticalScrollIndicator属性内部通过自动处理了，外部的传值会被重置掉。

**Comment by Liyongcong** [comment]
不想显示这个滚动条应该怎么处理
