### ISSUE TITLE
请教下TableHeaderView从xib加载初始化的问题

### ISSUE THREAD

**Issue by ShaoXinSen** [pujiaxin33/JXPagingView#51]
demo里是用代码初始化HeaderView的, 我试着从xib加载初始化, 如下
```objective-c
_userHeaderView = [[[NSBundle mainBundle] loadNibNamed:NSStringFromClass(TestView.class) owner:nil options:nil] objectAtIndex:0];
_userHeaderView.bounds = CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, JXTableHeaderViewHeight);
```

但是得到的结果完全超出预期, headerView太大了, 都已经超过了一个屏幕大小, 想问下还有什么是我没有注意到的地方吗?

**Comment by pujiaxin33** [comment]
用另一个UIView包裹一下

**Comment by ShaoXinSen** [comment]
> 用另一个UIView包裹一下

刚正好搜到了tips...3Q

**Comment by ShaoXinSen** [comment]
@pujiaxin33 xib还是遇到了问题, 没法解决, 手写代码正常
在头图缩放的情况下, headerView的图片会显示在categoryView之下listView之上
![img_2262](https://user-images.githubusercontent.com/13616801/51516981-38c48480-1e54-11e9-8d98-beddcd8e443e.PNG)

**Comment by ShaoXinSen** [comment]
```objective-c
- (void)awakeFromNib{
    [super awakeFromNib];
    [self setupImage];
}

- (void)setupImage{
    [self.headerGameAlbumImage setImage:[UIImage imageNamed:@"game_cover"]];
    [self.headerBackgoundImage setImage:[UIImage imageNamed:@"lufei"]];
    self.headerBackgoundImage.contentMode = UIViewContentModeScaleAspectFill;
}

- (void)setFrame:(CGRect)frame{
    [super setFrame:frame];
    _imageViewFrame = frame;
}

- (void)scrollViewDidScroll:(CGFloat)contentOffsetY {
    CGRect frame = self.imageViewFrame;
    frame.size.height -= contentOffsetY;
    frame.origin.y = contentOffsetY;
    self.headerBackgoundImage.frame = frame;
}
```

**Comment by pujiaxin33** [comment]
初始化headerView和使用headerView的代码

**Comment by ShaoXinSen** [comment]
```objective-c
_userHeaderContainerView = [[UIView alloc] initWithFrame:CGRectMake(0, 0, [UIScreen mainScreen].bounds.size.width, JXTableHeaderViewHeight)];
_userHeaderView = [[[NSBundle mainBundle] loadNibNamed:NSStringFromClass(TestView.class) owner:nil options:nil] objectAtIndex:0];
[_userHeaderContainerView addSubview:_userHeaderView];
_userHeaderView.frame = _userHeaderContainerView.bounds;
```

**Comment by pujiaxin33** [comment]
你把userHeaderContainerView.clickToBounds设置为YES

**Comment by ShaoXinSen** [comment]
我把demo改了下发你看看
JXPagerViewExample-OC > 导航栏隐藏
[JXPagingView-master.zip](https://github.com/pujiaxin33/JXPagingView/files/2781720/JXPagingView-master.zip)

**Comment by ShaoXinSen** [comment]
@pujiaxin33 但是这样的话, 导航栏隐藏的部分图片也无法显示出来了

**Comment by pujiaxin33** [comment]
你不是说用代码没有问题吗？你就不要用xib了吧。

**Comment by ShaoXinSen** [comment]
@pujiaxin33 XIB没问题不是更好吗....所以想请教一下啊

**Comment by pujiaxin33** [comment]
那我就说了一下导航栏隐藏的细节，然后你自己处理xib的逻辑：
1、tableView依然从导航栏下方布局，关键代码：`//pagingView依然是从导航栏下面开始布局的
    self.pagerView.frame = CGRectMake(0, self.pinHeaderViewInsetTop, self.view.bounds.size.width, self.view.bounds.size.height - self.pinHeaderViewInsetTop);`
2、让mainTableView可以显示范围外，这样子导航栏顶部就可以被headerView显示，关键代码：`//让mainTableView可以显示范围外
    self.pagerView.mainTableView.clipsToBounds = false;`
3、你要调整headerView的内容，去填充导航栏，关键代码：`//让头图的布局往上移动naviHeight高度，填充导航栏下面的内容
    self.userHeaderView.headerBackgoundImage.frame = CGRectMake(0, -naviHeight, self.view.bounds.size.width, naviHeight + JXTableHeaderViewHeight);`
4、明白了这些xib就可以按照这个来设置。多试试吧，就可以实现的。
