### ISSUE TITLE
用 allowsCacheList ，validListDict 取不到第一頁

### ISSUE THREAD

**Issue by TsengWenJian** [pujiaxin33/JXPagingView#513]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
用 allowsCacheList ，validListDict 取不到第一頁

**版本号**
1.JXPagingView版本号：2.1.3
2.OC还是Swift版本：swift
3.手机系统版本号：iOS  17.4.1
4.手机型号：iphone 15 pro 
 
**复现步骤**
1. 遇到问题的相关效果、类是：JXPagingView， allowsCacheList 設定 true ，實作 listIdentifierAtIndex
2.具体的操作步骤是：情境上內頁需等 api 回來才顯示，JXPagingView reloadData ， validListDict 拿不到第一頁資料

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
已经通过 https://github.com/pujiaxin33/JXPagingView/pull/512  修复

**Comment by TsengWenJian** [comment]
能新增 tag 2.1.4 嗎？
