### ISSUE TITLE
请问能否支持多个自定义悬停？

### ISSUE THREAD

**Issue by zht415** [pujiaxin33/JXPagingView#516]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：OC
3.手机系统版本号：17.5
4.手机型号：iphone13

**复现步骤**
1. 遇到问题的相关效果、类是：请问能否支持多个悬停，
3.具体的操作步骤是：
 例如闲鱼： 上滑时顶部海鲜市场/推荐/北京视图在顶部悬停，下拉时视图跟着滑动， 再上滑中部猜你喜欢也会悬停
 同样贝壳： 下拉刷新时看点/首页跟着下拉滑动，上滑时看点/首页固定在头部，再上滑推荐/二手视图也会悬停
**截图、GIF**
提供bug出现时的截图或者GIF。

https://github.com/pujiaxin33/JXPagingView/assets/7188250/78536a98-0a61-408e-bfd7-5f4b141cceb6

https://github.com/pujiaxin33/JXPagingView/assets/7188250/f44a4a58-b9b3-4543-8af4-1c6929431dba

**Comment by pujiaxin33** [comment]
你可以参考Swift版本中的【categoryView嵌套PagingView示例】，至于最顶部的下拉刷新功能需要自己想办法解决了。
