### ISSUE TITLE
点击两次问题

### ISSUE THREAD

**Issue by zidonJ** [pujiaxin33/JXPagingView#55]
[self.mainTableView setContentOffset:CGPointMake(0, headerH) animated:false];
改成这种方式应该可以避免点击两次的情况出现

**Comment by pujiaxin33** [comment]
改哪里呢？给截图给一个代码的上下文吗？

**Comment by zidonJ** [comment]
JXPagerView preferredProcessMainTableViewDidScroll方法内

**Comment by pujiaxin33** [comment]
我试了下用这这种方式，[self.mainTableView setContentOffset:CGPointMake(0, headerH) animated:false];
会有更多副作用问题。

**Comment by zidonJ** [comment]
我现在用的这种方式，暂时还么有遇到，导致点击两次的问题原因应该就在这里 导致scrollview处于tracking状态 无法及时接受点击事件。

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/51899612-58c4ec80-23ee-11e9-9373-0bdc3b22c665.png)
你是把两处红框都修改了吗

**Comment by zidonJ** [comment]
对 都修改了

**Comment by pujiaxin33** [comment]
我试了一下还是有副作用
