### ISSUE TITLE
请问这个table怎么刷新数据呢

### ISSUE THREAD

**Issue by yqy159** [pujiaxin33/JXPagingView#59]
(id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index 设置数据是在这个代理方法里设置的 我想刷新数据的话需要重新走这个代理是吗

**Comment by pujiaxin33** [comment]
第一个要确定的疑问：“我想刷新数据”，请问指的是某一个列表的数据吗？还是整个pagingView？
如果是单个列表的数据刷新，你直接操作列表即可；
如果是paingView，调用reloadData方法，然后`(id)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index`方法会重新走的

**Comment by yqy159** [comment]
懂了，谢谢
