### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by yszhangjiayu** [pujiaxin33/JXPagingView#6]
oc怎么用？继承还是push推出？

**Comment by pujiaxin33** [comment]
JXPagingView就是一个自定义视图而已，创建被添加到VC.view即可。OC版本的示例，我放到这个仓库里面了：https://github.com/pujiaxin33/JXCategoryView

**Comment by yszhangjiayu** [comment]
没看到导航栏隐藏的那个效果，要结合swift那个自己弄一下吧？

**Comment by pujiaxin33** [comment]
导航栏隐藏OC版本里面也有，只是示例demo，没有用而已，使用方法自己转换一下就行

**Comment by yszhangjiayu** [comment]
老哥能说下是哪一个类吗，或者单独发一个demo？我是小白，真是麻烦你了

**Comment by pujiaxin33** [comment]
NaviHiddenViewController

**Comment by pujiaxin33** [comment]
最新工程添加了OC版本的example工程了，下载最新代码即可

**Comment by yszhangjiayu** [comment]
不是阿，老哥，我下载了oc的还是没有呀，NaviHiddenViewController是swift的我看到了

**Comment by pujiaxin33** [comment]
你重新clone仓库，在JXPagerViewExample-OC文件夹里面

**Comment by yszhangjiayu** [comment]
谢谢大哥
