### ISSUE TITLE
点击cell不能push下一页

### ISSUE THREAD

**Issue by yuJian14180** [pujiaxin33/JXPagingView#61]
我这里的列表是用自定义UIViewController封装的，代理已经遵循，界面也没有问题 ，但是，当点击cell的时候 ，点击方法也响应 。但就是不能push下一个界面。我是在ViewController里push的

**Comment by pujiaxin33** [comment]
示例项目里面有关于`DetailViewController`类的跳转示例

**Comment by YuanJiaShuai** [comment]
@yuJian14180 有没有addChildController？

**Comment by pujiaxin33** [comment]
列表如果是VC，不能通过VC.navigationController进行跳转。因为列表VC是作为childViewController存在，它没有navigationController，请参考示例工程，将navigationController传递给列表进行跳转。示例项目里面有关于`DetailViewController`类的跳转示例
