### ISSUE TITLE
希望能优化一个手势问题

### ISSUE THREAD

**Issue by lf19940514** [pujiaxin33/JXPagingView#62]
当mainTableView的HeadView里有轮播图或者可左右滑动的scrollview时，滑动子视图时，mainTableView的滚动也会响应，希望滚动主视图时，子视图不响应拖动，滚动子视图时，主视图不响应拖动

**Comment by pujiaxin33** [comment]
最新仓库添加了顶部轮播图手势处理示例，你看一下就知道如何处理了
