### ISSUE TITLE
self.pagingView.currentListDidAppear() 报错

### ISSUE THREAD

**Issue by LockeXia** [pujiaxin33/JXPagingView#64]
self.pagingView.currentListDidAppear()
Thread 1: EXC_BAD_ACCESS (code=1, address=0x10)
很奇怪，pod update的 版本。 将demo里的文件copy到我的项目也是一样的

**Comment by pujiaxin33** [comment]
你clean一下项目再试试呢

**Comment by LockeXia** [comment]
可以了，我关闭问题了。多谢
