### ISSUE TITLE
希望能增加像脉脉首页的效果

### ISSUE THREAD

**Issue by cocfident** [pujiaxin33/JXPagingView#65]
希望能增加像脉脉首页的效果  header吸附的时候 带有缩放效果

**Comment by pujiaxin33** [comment]
这个效果之前有人提过，还在开发中，静候

**Comment by pujiaxin33** [comment]
垂直缩放效果已经实现，具体请到这个库[JXCategoryView](https://github.com/pujiaxin33/JXCategoryView)
在readme页面搜索【垂直缩放】关键字即可看到相关内容
