### ISSUE TITLE
怎样设置悬浮的位置

### ISSUE THREAD

**Issue by cocfident** [pujiaxin33/JXPagingView#66]
怎么样设置悬浮的位置,例如我想让他悬浮在屏幕中间 而不是 navbar的底部~~~

**Comment by pujiaxin33** [comment]
因为悬浮的view就是UITableView的sectionHeaderView，所以它悬浮的位置就是UITableView的顶部，这是系统特性决定了。
但是有看到网上说可以调整contentInset，间接达到控制悬浮位置，但是这个还需要再验证一下，因为会影响到手势的处理。
所以，这个特性会晚一点更新

**Comment by pujiaxin33** [comment]
你能给一个位置调整的具体案例吗？因为我写着写着不知道最终的效果是什么样的了。
能给一个已经上线的app参考吗？或者示例图？或者gif

**Comment by pujiaxin33** [comment]
用图文描述下最终的效果，尽量不要用文字，不然理解起来会有歧义

**Comment by pujiaxin33** [comment]
最新版本添加了pinSectionHeaderVerticalOffset属性可以设置悬浮位置。1.1.1版本
