### ISSUE TITLE
会增加这种效果么？  现在导航栏里这种效果出现的很频繁

### ISSUE THREAD

**Issue by GeekZP** [pujiaxin33/JXPagingView#67]
<img width="675" alt="image" src="https://user-images.githubusercontent.com/12639787/53559928-3c030c80-3b86-11e9-8d2f-70ba9f97d6c8.png">

会增加这种效果么？  现在导航栏里这种效果出现的很频繁

**Comment by pujiaxin33** [comment]
你所表达的效果是底部对齐吗？

**Comment by GeekZP** [comment]
底部对齐，居左

发自我的 iPhone

**Comment by GeekZP** [comment]
> 你所表达的效果是底部对齐吗？

大小缩放+cell宽度缩放       底部对齐，居左 这种效果

**Comment by pujiaxin33** [comment]
[Issue93](https://github.com/pujiaxin33/JXCategoryView/issues/93)
目前仅支持顶部或底部对齐，不支持居左

**Comment by pujiaxin33** [comment]
还有这是JXPagingView库，关于分类控制器有疑问的，请到这里提问[JXCategoryView](https://github.com/pujiaxin33/JXCategoryView)
