### ISSUE TITLE
导航透明时下拉问题

### ISSUE THREAD

**Issue by WS-Vincent** [pujiaxin33/JXPagingView#68]
看了一下导航透明实现，使用了那种取巧方法，子视图偏移出父视图不剪切。但是现在想在导航透明的情况下整个刷新，这时候刷新控件刚好会被多出的视图遮盖住看不见。有什么好的办法吗？Swift

**Comment by WS-Vincent** [comment]
用contentInset解决了 比frame便偏移好使一点 解决了

**Comment by pujiaxin33** [comment]
最近也在研究用contentInset调整偏移量的方案，后续版本会加上
