### ISSUE TITLE
listViewDidScrollCallback 没有执行，其他的都可以，就是这个不执行会出现scrollerView瞬间滑动到一段距离的bug。。。

### ISSUE THREAD

**Issue by zhangqi02060227m** [pujiaxin33/JXPagingView#7]
- (void)listViewDidScrollCallback:(void (^)(UIScrollView *))callback {
    self.listViewDidScrollCallback = callback;
}
- (void)scrollViewDidScroll:(UIScrollView *)scrollView {
    if (self.listViewDidScrollCallback) {
        self.listViewDidScrollCallback(self.myTableView);
    }
}

这个listViewDidScrollCallback 没有执行为什么？？

**Comment by pujiaxin33** [comment]
建议你按照demo工程配置。如果还不行，请联系QQ:317437084   多半是代码使用问题

**Comment by zhangqi02060227m** [comment]
好的
