### ISSUE TITLE
tableview点击代理失效

### ISSUE THREAD

**Issue by wamgcn** [pujiaxin33/JXPagingView#71]
当内嵌的TableVIew上滑  新加载出来的cell点击失效  断点调试发现没有新的cell被点击后没有走tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath方法但旧cell无问题

**Comment by pujiaxin33** [comment]
你可以参考文档里面，关于cell点击无效的处理方式

**Comment by wamgcn** [comment]
> 你可以参考文档里面，关于cell点击无效的处理方式

我看了关于cell点击无效的处理方法  但另外发现伴随cell无法点击的同时JXCategoryTitleView这个view也是无法点击的

**Comment by wamgcn** [comment]
> 你可以参考文档里面，关于cell点击无效的处理方式

参考文档？JXPagingView工程下没发现相关文档 JXCategoryView的Document中也未发现相关内容啊？

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/54675805-3d4aa800-4b3a-11e9-9c7d-a6fe3c5cd11d.png)

**Comment by wamgcn** [comment]
关于下方列表视图的代理方法- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath有时候需要点击两次才回调

**Comment by wamgcn** [comment]
关于下方列表视图的代理方法- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath有时候需要点击两次才回调

**Comment by wamgcn** [comment]
需要两次点击那个我看了  cell问题试了一下是可以解决的  但我发会伴随有另外一个问题  当新cell无法点击的同时JXCategoryTitleView也是无法响应点击的   这是只能左右滑切换下面tableview的内容了

**Comment by pujiaxin33** [comment]
你能只用demo就能复现这么问题吗？复现的步骤是什么？

**Comment by wamgcn** [comment]
> 现的步骤是什么？

demo复现不是很稳定  但我的项目浮现率还是比较高的   复现步骤就是APP点开  直接上拉  知道headView隐藏    这时下面新的cell就不能点击了  JXCategoryTitleView也不能点击了  必须左右滑到其他内容的tableview才能正常   复现率我这边有个2/5大概     我这边是有5个标签对应的5个list

**Comment by Z-Victory** [comment]
所以你最后是怎么解决了

**Comment by MrCaiWH** [comment]
@pujiaxin33 2.0.1版本UIbutton的方式无效，帮忙看一下

**Comment by ZClee128** [comment]
都没有处理好呀，为什么关闭了
