### ISSUE TITLE
列表下拉刷新功能里，cell点击

### ISSUE THREAD

**Issue by hYRamos** [pujiaxin33/JXPagingView#72]
tableView点击时，为什么所有的cell的分割线都不显示了，而且cell的contentview也变成了白色（我自己本来设了一个颜色），cell.selectionStyle = UITableViewCellSelectionStyleNone;这行代码也加了
我的didSelectRowAtIndexPath是能走的，文档说的点击无效的情况我也没有出现

**Comment by pujiaxin33** [comment]
请问你是使用demo就出现了该问题吗？

**Comment by pujiaxin33** [comment]
列表的显示问题，理论上跟JXPagingView库是独立开的，建议你再仔细自测一下。
