### ISSUE TITLE
JXPagingListRefreshView 配合 pinSectionHeaderVerticalOffset 难以触发刷新

### ISSUE THREAD

**Issue by wiiale** [pujiaxin33/JXPagingView#74]
***场景***：将 Swift Demo 中 PagingViewController.swift 的 pagingView 用 JXPagingListRefreshView 实现，设置 `pagingView.pinSectionHeaderVerticalOffset = 50`

***触发动作***：先下拉小段（contentOffset.y > 0），然后下拉去触发刷新。

***原因是*** [JXPagingListRefreshView.swift 22行附近](https://github.com/pujiaxin33/JXPagingView/blob/master/JXPagingView-Swift/JXPagingListRefreshView.swift#L22)  `scrollView.contentOffset.y < 0` 时 `mainTableView.bounces 会被置为 true`

***简单处理了下可以用***
```
if scrollView.contentOffset.y == 0 {
    mainTableView.bounces = false
}else {
    mainTableView.bounces = true
}
```
改为
```
if scrollView.contentOffset.y < 0 {
    self.mainTableView.contentOffset = .zero
    mainTableView.bounces = false
} else if scrollView.contentOffset.y == 0 {
    mainTableView.bounces = false
} else {
    mainTableView.bounces = true
}
```

**Comment by pujiaxin33** [comment]
能再详情一点描述复现步骤吗？或者有复现视频，自测没发现问题

**Comment by wiiale** [comment]
过了段时间稍微有点忘了哈，现在在本项目里改改测测没问题。之前是在 JXSegmentedView 项目里面改的，应该是没有改好或漏了代码。不好意思
