### ISSUE TITLE
UIViewController实现JXPagerViewListViewDelegate协议 小问题

### ISSUE THREAD

**Issue by wuzhecode** [pujiaxin33/JXPagingView#75]
如果是UIViewController实现JXPagerViewListViewDelegate协议，控制器的navigationController拿不到，就无法push到另一个控制器。需要在- (id<JXPagerViewListViewDelegate>)pagerView:(JXPagerView *)pagerView initListAtIndex:(NSInteger)index;里面将其作为子控制器，才能push

**Comment by pujiaxin33** [comment]
可以参考demo里面，将外部的navigationController赋值给列表VC的一个自定义属性
