### ISSUE TITLE
使用defaultSelectedIndex修改初始化的时候默认选择的index=3时，还是先加载了index=0,然后才加载index=3

### ISSUE THREAD

**Issue by GeekZP** [pujiaxin33/JXPagingView#78]
使用defaultSelectedIndex修改初始化的时候默认选择的index=3时，还是先加载了index=0,然后才加载index=3

**Comment by pujiaxin33** [comment]
1.1.2版本 JXPagerListContainerView新增defaultSelectedIndex 保持与self.categoryView.defaultSelectedIndex一样即可
