### ISSUE TITLE
设置pinSectionHeaderVerticalOffset后, 猛的向下滑动, 出现顶部空白问题.

### ISSUE THREAD

**Issue by huangxianyu** [pujiaxin33/JXPagingView#79]
**bug描述**
1. 设置一下属性后
_pagerView.pinSectionHeaderVerticalOffset = 30;
2. 向上滑动到顶部, 悬浮在距离SectionHeader 30的位置.
3. 然后猛的往下滑动列表, 出现顶部有30的空白区域, mainTableView不能回到原点.

**版本号**
1.JXPagingView版本号: 1.1.1
2.OC还是Swift版本: OC

**截图、GIF**
![WechatIMG10](https://user-images.githubusercontent.com/20720740/55861290-a016e880-5ba8-11e9-9dea-efa40cf88136.jpeg)

**Comment by pujiaxin33** [comment]
谢谢反馈，已修复，预计1.1.3版本更新
