### ISSUE TITLE
使用自定义导航，配合DZEmptyDataSet，不能设置空白页不能滑动

### ISSUE THREAD

**Issue by 460565420** [pujiaxin33/JXPagingView#80]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：？
2.OC还是Swift版本：？
3.手机系统版本号：？
4.手机型号：？

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：？

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by pujiaxin33** [comment]
是你的列表视图使用DZEmptyDataSet有问题吗？
截图呢

**Comment by 460565420** [comment]
> 是你的列表视图使用DZEmptyDataSet有问题吗？
> 截图呢

![IMG_3899](https://user-images.githubusercontent.com/15902435/56015608-31629800-5d2c-11e9-9878-23a32be968de.PNG)
![IMG_3900](https://user-images.githubusercontent.com/15902435/56015616-36274c00-5d2c-11e9-87e7-618e47cba522.PNG)
![IMG_3901](https://user-images.githubusercontent.com/15902435/56015618-39223c80-5d2c-11e9-93f2-5f332d0cd91a.PNG)
swift

**Comment by pujiaxin33** [comment]
如果可以的话，把你的能复现问题的工程发给我，qq：317437084

**Comment by 460565420** [comment]
自己设置的有点问题
