### ISSUE TITLE
问个问题

### ISSUE THREAD

**Issue by BowenCoder** [pujiaxin33/JXPagingView#81]
你好，问一个问题。我想简写一个类似的两个scrollview滚动的功能，当mainscrollview滑动到底部，再滑动的时候，childscrollview就不滚动了，代理也不走了。你是怎么做到的啊，我看了你的代码没看到关键点。

**Comment by pujiaxin33** [comment]
1、关键代码是`JXPagerMainTableView`类的代理方法：
`- (BOOL)gestureRecognizer:(UIGestureRecognizer *)gestureRecognizer shouldRecognizeSimultaneouslyWithGestureRecognizer:(UIGestureRecognizer *)otherGestureRecognizer`
返回true表示，允许多个`UIScrollView`同时响应手势；

2、然后就是`JXPagerView`类的`- (void)preferredProcessListViewDidScroll`和`- (void)preferredProcessMainTableViewDidScroll`两个方法，根据不同情况对contentOffset等进行处理。

**Comment by BowenCoder** [comment]
我之前看了，没有找到我的关键点。我在你的这两个方法中直接return了。你的mainTableView滑动到底部，再往上面滑动，mainTableView和listContainerView都会滑动。我的只响应mainTableView 的scrollViewDidScroll, listContainerView不响应scrollViewDidScroll。初步怀疑手势问题，看了你的也只在JXPagerMainTableView处理了一下

**Comment by pujiaxin33** [comment]
mainTableView和列表scrollView的滑动处理，比较麻烦，需要自己多尝试，处理好边界情况即可。
