### ISSUE TITLE
bug: 一级界面使用JXPagingView后旋转屏幕之后冻屏

### ISSUE THREAD

**Issue by 534254884** [pujiaxin33/JXPagingView#82]
一级界面使用JXPagingView后，  进入二级界面，连续旋转屏幕后，app冻屏假死,
产生问题的代码如下：
- (void)deviceOrientationDidChangeNotification:(NSNotification *)notification {
    if (self.currentDeviceOrientation != [UIDevice currentDevice].orientation) {
        self.currentDeviceOrientation = [UIDevice currentDevice].orientation;
        //前后台切换也会触发该通知，所以不相同的时候才处理
        [self.mainTableView reloadData];
        [self.listContainerView deviceOrientationDidChanged];
        [self.listContainerView reloadData];
    }
}

**Comment by pujiaxin33** [comment]
可以看一下控制台bt指令的输出吗？

**Comment by pujiaxin33** [comment]
或者其他错误信息的截图

**Comment by pujiaxin33** [comment]
感谢你的反馈，问题会在1.1.4版本修复。
复现路径，滚动一个列表，立马旋转屏幕即可复现。
