### ISSUE TITLE
滑动就立即加载了将要显示的页面

### ISSUE THREAD

**Issue by GeekZP** [pujiaxin33/JXPagingView#83]
demo里是滑动JXCategoryListCollectionContainerView，只要一触发滑动就加载将要出现页面了，能设置等滑动结束才触发页面显示

**Comment by pujiaxin33** [comment]
`JXCategoryListCollectionContainerView`这个类不行，它是在`willDisplayCell`回调里面触发列表加载的。
你可以使用`JXCategoryListContainerView`，设置它的`didAppearPercent`为0.9，就可以接近达到滑动结束后加载。
