### ISSUE TITLE
关于设置悬浮pinSectionHeaderVerticalOffset的位置

### ISSUE THREAD

**Issue by xytyes** [pujiaxin33/JXPagingView#85]
你好，按照demo里面的 在viewDidLoad直接设置悬浮的位置是没问题的

但是如果一开始没有设置pinSectionHeaderVerticalOffset， 而是通过事件来触发的
就会导致 子视图里面的tableview高度不对，应该是刚好差 pinSectionHeaderVerticalOffset设置的高度， 导致tableview拉不到底

我看了你的代码，没有找到关键点来处理这个问题，这个问题怎么解决比较好

**Comment by pujiaxin33** [comment]
```Objective-C
self.pagerView.pinSectionHeaderVerticalOffset = 100;
[self.pagerView reloadData];
```
你把`[self.pagerView reloadData];`加上试试

**Comment by xytyes** [comment]
解决了。thk
