### ISSUE TITLE
关于使用 NSUInteger 类型返回高度的初衷的疑惑。

### ISSUE THREAD

**Issue by iDevOrz** [pujiaxin33/JXPagingView#86]
```
/**
 返回悬浮HeaderView的高度，因为内部需要比对判断，只能是整型数

 @param pagerView pagerView description
 @return 悬浮HeaderView的高度
 */
- (NSUInteger)heightForPinSectionHeaderInPagerView:(JXPagerView *)pagerView;

/**
 返回tableHeaderView的高度，因为内部需要比对判断，只能是整型数

 @param pagerView pagerView description
 @return return tableHeaderView的高度
 */
- (NSUInteger)tableHeaderViewHeightInPagerView:(JXPagerView *)pagerView;
```

请问这里的 ``NSInteger`` 如果换成使用 ``CGFloat`` 类型有什么后果？或者说，出于什么样的考虑使用了``NSInteger``,是因为浮点型有精度丢失问题？

**Comment by pujiaxin33** [comment]
因为内部会通过`tableHeaderViewHeightInPagerView`值进行比较，如果浮点无理数会有问题。所以就通过类型约束了。

**Comment by iDevOrz** [comment]
浮点型比较大小似乎只在比较两个浮点型是否相等时会有精度丢失问题，所以通常两浮点数差值的绝对值小于某个很小的数（通常是 0.000001 ）时就认为两数“相等” 。``JXPagingView``似乎只有比较大小的情况，请问 “浮点无理数会有问题” 具体值的是什么？

**Comment by pujiaxin33** [comment]
> 通常两浮点数差值的绝对值小于某个很小的数（通常是 0.000001 ）时就认为两数“相等”

这个是人为主观判断的相等，并不是真正意义的相等。反正之前出现的问题就是，无理数会导致处理头部悬浮错误，我记得是现象是会异常置顶。

**Comment by iDevOrz** [comment]
谢谢解惑。
