### ISSUE TITLE
How to support FDFullscreenPopGesture?

### ISSUE THREAD

**Issue by RobotAmiee** [pujiaxin33/JXPagingView#87]
I'd like to add full screen pop gesture with FDFullscreenPopGesture, but only the header part can support pop gesture.

**Comment by pujiaxin33** [comment]
老哥，我看了你的资料，广州深圳的兄弟，我就不用google翻译，中文回复了哈。
因为下面列表容器`JXPagerListContainerView`内部持有一个`UICollectionView`，可以左右滚动切换。所以左右滑动手势，会先被`JXPagerListContainerView`响应，FDFullscreenPopGesture就不会响应了。

**Comment by RobotAmiee** [comment]
```
[self.pagerView.mainTableView.panGestureRecognizer requireGestureRecognizerToFail:self.navigationController.fd_fullscreenPopGestureRecognizer];[self.pagerView.listContainerView.collectionView.panGestureRecognizer requireGestureRecognizerToFail:self.navigationController.fd_fullscreenPopGestureRecognizer];
```

这么做的话可以侧滑返回，但是 `JXPagerListContainerView` 下面的 `UICollectionView` 不能左右滑动了，如果能实现 `UICollectionView` 在第一页时 `requireGestureRecognizerToFail`，其他页时取消这个 fail gesture recognizer 就能完美支持了。

**Comment by pujiaxin33** [comment]
1.1.7版本新增api可以处理FDFullscreenPopGesture
[FDFullscreenPopGesture全屏手势兼容处理文档](https://github.com/pujiaxin33/JXPagingView/blob/master/Document/%E5%85%A8%E5%B1%8F%E6%89%8B%E5%8A%BF%E5%A4%84%E7%90%86.md)

你更新一下试试呢

**Comment by RobotAmiee** [comment]
可以的，完美支持了。

**Comment by CoderYLM** [comment]
2.0.1版本处理FDFullscreenPopGesture时self.pagerView.listContainerView.collectionView.gestureDelegate = self;   colletionView点不到
