### ISSUE TITLE
使用的1.1.3版本JXPagerListRefreshView导致title一下正常一下闪烁置顶的情况

### ISSUE THREAD

**Issue by Q-Time** [pujiaxin33/JXPagingView#88]
更新到1.1.3版本以后，我用的JXPagerListRefreshView，并且把mainTableView的contentInset = UIEdgeInsetsMake(100, 0, 0,0)，然后往上滚动内容过程中，title突然置顶了，而不是停留在距离顶部100的位置，但是往下滚动内容过程中，title会停留在距离顶部100的位置。

**Comment by pujiaxin33** [comment]
1、贴一下关键代码呢？
2、能有一个出现问题时的GIF动图最好了。

**Comment by Q-Time** [comment]
/**
 mainTableView的滚动回调，用于实现头图跟随缩放
 
 @param scrollView mainTableView
 */
- (void)mainTableViewDidScroll:(UIScrollView *)scrollView{
    
    if (scrollView.contentOffset.y < self.navigationBarViewHeight + 20) {
        
        scrollView.contentInset = UIEdgeInsetsMake(0, 0, 0, 0);
    }else if (scrollView.contentOffset.y > self.navigationBarViewHeight + 20) {
        
        scrollView.contentInset = UIEdgeInsetsMake(self.navigationBarViewHeight, 0, 0, 0);
    }
}

![689DB9C41AA7058A47CE28B95DB328C0](https://user-images.githubusercontent.com/19901460/57348576-29f6a900-7189-11e9-8806-2e8af5e710ed.gif)

**Comment by pujiaxin33** [comment]
尽量不要通过外部修改scrollView的一些属性，你可以尝试用`pinSectionHeaderVerticalOffset`属性，看看能满足你的要求不

**Comment by Q-Time** [comment]
你好，通过pinSectionHeaderVerticalOffset属性设置，是能达到一样的效果，但是发现头部headerView最顶部会出现空白闪烁一下的问题。

/**
 mainTableView的滚动回调，用于实现头图跟随缩放
 
 @param scrollView mainTableView
 */
- (void)mainTableViewDidScroll:(UIScrollView *)scrollView{
    
    if (scrollView.contentOffset.y < self.navigationBarViewHeight + 20) {
        
        self.contentListView.pinSectionHeaderVerticalOffset = 0;
    }else if (scrollView.contentOffset.y > self.navigationBarViewHeight + 20) {
        
        self.contentListView.pinSectionHeaderVerticalOffset = self.navigationBarViewHeight;
    }
}

**Comment by pujiaxin33** [comment]
> 头部headerView最顶部会出现空白闪烁一下的问题。
如何出现的？再来个GIF动图呢

**Comment by Q-Time** [comment]
顶部的白色区域闪烁有点延迟的闪一下

![2CCE98FEC5C6542E03C6B53B6C49EBF5](https://user-images.githubusercontent.com/19901460/57355065-c4fa7d80-719f-11e9-9961-840c25858b6e.gif)

**Comment by pujiaxin33** [comment]
我没怎么看出来，自测也没啥问题，这个就爱莫能助了

**Comment by Q-Time** [comment]
不是经常出现的，我回退回1.1.2版本或者之前更早的版本，修改pinSectionHeaderVerticalOffset 属性或者contentInset都可以解决了，谢谢
