### ISSUE TITLE
用这个还要把老版的 #import "JXCategoryView.h"这个也pod进来吗？

### ISSUE THREAD

**Issue by Azraeltulips** [pujiaxin33/JXPagingView#89]
使用pod 'JXPagingView/Pager', '~> 1.1.7'时，要同时pod 'JXCategoryView', '~> 1.3.0'这个吗？不然直接#import "JXCategoryView.h"会报错

**Comment by pujiaxin33** [comment]
它们是分开的两个库，需要分别引入的
