### ISSUE TITLE
如果列表是collectionView时，滑动异常

### ISSUE THREAD

**Issue by meskaly** [pujiaxin33/JXPagingView#9]
大佬，如果列表是collectionView时，上滑到collectionView部门内容超出边界后（ categoryView 悬浮停靠后继续上滑了一段距离）， 往下滑时collectionView 的contentOffset的y值突然变为0，是什么原因呀？而且上下滑动时很容易左右滑动

**Comment by pujiaxin33** [comment]
请参考swift版本demo工程的CollectionViewViewController类示例。
