### ISSUE TITLE
关于demo，有个地方不是很明白

### ISSUE THREAD

**Issue by liujunliuhong** [pujiaxin33/JXPagingView#91]
**Feature描述**
看了你的demo，有个地方不是很明白

**其他补充**
![image](https://user-images.githubusercontent.com/16097707/58410964-db606e80-80a5-11e9-9c65-bc9bad7346b5.png)
userHeaderView和categoryView的frame设置是否多余？因为代理方法里面有设置headerHeight和sectionHeight.
我尝试了下，在初始化时不给headerView和categoryView设置frame是不成功的。
感觉这样很奇怪

**Comment by pujiaxin33** [comment]
```
- (void)refreshTableHeaderView {
    UIView *tableHeaderView = [self.delegate tableHeaderViewInPagerView:self];
    UIView *containerView = [[UIView alloc] initWithFrame:tableHeaderView.bounds];
    [containerView addSubview:tableHeaderView];
    self.mainTableView.tableHeaderView = containerView;
}
```
这是headerView的刷新逻辑，里面依赖了代理方法tableHeaderViewInPagerView返回视图的frame。
确实应该依赖heightForPinSectionHeaderInPagerView代理方法的高度。代码有点冗余了

**Comment by liujunliuhong** [comment]
望修改，之前的pod版本我是没设置headerHeight的，没有任何问题，但是更新pod之后，就不行了，检查了一番，才发现是这个问题

**Comment by pujiaxin33** [comment]
可能还是要保持现在的做法，需要你自己设置一下frame
