### ISSUE TITLE
使用titleDataSource方式计算cell宽度，文本显示异常。

### ISSUE THREAD

**Issue by Eddiegooo** [pujiaxin33/JXPagingView#92]
**bug描述**
使用titleDataSource 自计算tab宽度， 当宽度大于110时，最大取110，否则取计算的出来的宽度。此时，cell宽度正常，但是cell里面的titleLabel宽度异常，导致显示异常。

**版本号**
1.JXPagingView版本号：最新版
2.OC还是Swift版本：OC 
3.手机系统版本号：ALL
4.手机型号：ALL

**复现步骤**
1. 遇到问题的相关效果、类是： JXCategoryTitleCell
2.具体的操作步骤是：使用titleDataSource 计算cell宽度。

**截图、GIF**
        self.typeView.titleDataSource = self;
        self.typeView.cellWidth = JXCategoryViewAutomaticDimension;

//自定义计算从cell宽度 
- (CGFloat)categoryTitleView:(JXCategoryTitleView *)titleView widthForTitle:(NSString *)title {
    CGFloat cellWidth = ceilf([title boundingRectWithSize:CGSizeMake(MAXFLOAT, MAXFLOAT) options:NSStringDrawingUsesLineFragmentOrigin|NSStringDrawingUsesFontLeading attributes:@{NSFontAttributeName : [UIFont systemFontOfSize:13]} context:nil].size.width);
    return cellWidth > 110 ? 110 : cellWidth;
}

![屏幕快照 2019-06-04 上午11 38 43](https://user-images.githubusercontent.com/10209529/58849555-54bb1b00-86bd-11e9-8fa8-ea52edd1456f.png)

可能问题：
 JXCategoryTitleCell 里 self.titleLabel.translatesAutoresizingMaskIntoConstraints = NO; 导致。。。

TIPS：楼主辛苦了，楼主可有更优的解决方案？

**Comment by pujiaxin33** [comment]
cell里面的titleLabel会超过cell的范围显示，所以你计算的宽度不能小于titleLabel的宽度

**Comment by Eddiegooo** [comment]
Label.numbersOfLine 设置为2.  当它宽度大于指定宽度的时候文本就换行，这样子也不行的么？
cell宽度不能设置一个最大宽度，必须根据文本计算得出？

**Comment by Eddiegooo** [comment]
> cell里面的titleLabel会超过cell的范围显示，所以你计算的宽度不能小于titleLabel的宽度

@pujiaxin33      Label.numbersOfLine 设置为2. 当它宽度大于指定宽度的时候文本就换行，这样子也不行的么？
cell宽度不能设置一个最大宽度，必须根据文本计算得出？

**Comment by pujiaxin33** [comment]
titleLabel没有边界的概念，它不知道超过了父视图，所以numbersOfLine=2也不会自动换行，如果需要换行你需要自己再文本里面添加\n换行符

**Comment by Eddiegooo** [comment]
> titleLabel没有边界的概念，它不知道超过了父视图，所以numbersOfLine=2也不会自动换行，如果需要换行你需要自己再文本里面添加\n换行符

好吧。  非常感谢。 我在研究看下。

**Comment by Eddiegooo** [comment]
> titleLabel没有边界的概念，它不知道超过了父视图，所以numbersOfLine=2也不会自动换行，如果需要换行你需要自己再文本里面添加\n换行符

那么按你的设计，是不是numbersOfLine=2没有用？  用titleDataSource代理来计算cell宽度也没有用？这个代理计算用意在哪里呢？ 望解惑

**Comment by pujiaxin33** [comment]
```Objective-C
self.titleLabelCenterX = [NSLayoutConstraint constraintWithItem:self.titleLabel attribute:NSLayoutAttributeCenterX relatedBy:NSLayoutRelationEqual toItem:self.contentView attribute:NSLayoutAttributeCenterX multiplier:1 constant:0];
    self.titleLabelCenterY = [NSLayoutConstraint constraintWithItem:self.titleLabel attribute:NSLayoutAttributeCenterY relatedBy:NSLayoutRelationEqual toItem:self.contentView attribute:NSLayoutAttributeCenterY multiplier:1 constant:0];
    [NSLayoutConstraint activateConstraints:@[self.titleLabelCenterX, self.titleLabelCenterY]];
```
上面是titleLabel的约束代码，titleLabel就是居中于cell。
为什么不能限制leading和trailing在cell内部呢？主要是因为开启了titleLabelZoomEnabled之后，titleLabel放大之后就会超过cell，就会显示...  这是主要原因。

当然你设置numbersOfLine=2是有用的，是要你的文字里面自己插入换行符\n即可
