### ISSUE TITLE
动态设置pinSectionHeaderVerticalOffset后，reloadData后子视图全部刷新了

### ISSUE THREAD

**Issue by xieytt** [pujiaxin33/JXPagingView#93]
**bug描述**

 动态设置pinSectionHeaderVerticalOffset的高度，如果我不reloadData的话，会导致子视图的高度计算不正确， 但是我reloadData后，子视图全部重新加载了一遍，有没有什么方式能解决动态设置pinSectionHeaderVerticalOffset的高度后，不需要重新加载整个子视图

**版本号**
1.JXPagingView版本号：最新
2.OC还是Swift版本：OC
3.手机系统版本号：ALL
4.手机型号：ALL

**复现步骤**
1. 遇到问题的相关效果、类是：？
2.具体的操作步骤是：
 在demo的HeaderPositionViewController 里面增加个按钮来设置pinSectionHeaderVerticalOffset的高度。

**Comment by pujiaxin33** [comment]
你更新`pinSectionHeaderVerticalOffset`之后，试一下调用`[self.pagerView.mainTableView reloadData];`呢？

**Comment by xieytt** [comment]
试过了，不行， 整个tableview的高度计算的不准确，头部跟底部都不正确了，只有整个reloadData 才行，但是会导致我上面说的那个情况

**Comment by pujiaxin33** [comment]
你下载最新仓库，新增了【reloadData无需重新创建列表】示例，你参考一下里面的使用示例，就能实现reload之后无需重新创建列表
