### ISSUE TITLE
设置pinSectionHeaderVerticalOffset 为非整数时，xs max上列表显示不全

### ISSUE THREAD

**Issue by TZZhan** [pujiaxin33/JXPagingView#94]
**bug描述**
设置_pagerView.pinSectionHeaderVerticalOffset = 23.33;为非整数时，xs max上列表显示不全，无法下拉全部内容

**版本号**
1.JXPagingView版本号：最新
2.OC还是Swift版本：OC
3.手机系统版本号：12.2
4.手机型号：xs max

**复现步骤**
demo中，PagingViewController初始化pagerView时设置_pagerView.pinSectionHeaderVerticalOffset = 23.33;
运行，点击头图缩放，下拉列表，显示不全。

**截图、GIF**
<img width="246" alt="WeChatbb8e25384c50990853a00b53724813d3" src="https://user-images.githubusercontent.com/8191963/59017055-3c8dfc00-8875-11e9-8f24-fc01d7212e6b.png">

**Comment by pujiaxin33** [comment]
建议先使用整数吧，后续优化非整数

**Comment by pujiaxin33** [comment]
![image](https://user-images.githubusercontent.com/12654640/59400960-b0775980-8dcb-11e9-82ed-b34e14f0681c.png)
计算机存储浮点数的时候，是失真的，不会绝对保存其所有真实信息，但是代码内部有需要判断`self.mainTableView.contentOffset.y`和`self.mainTableViewMaxContentOffsetY`相等，有浮点数存在的情况，就会判断出错。所以我将`pinSectionHeaderVerticalOffset`声明为`NSInteger`类型来规避该问题。

```
@property (nonatomic, assign) NSInteger pinSectionHeaderVerticalOffset;
```
