### ISSUE TITLE
JXPagingView 标题页布局能修改么

### ISSUE THREAD

**Issue by LockeXia** [pujiaxin33/JXPagingView#95]
JXPagingView 标题页布局 左对齐
<img width="480" alt="QQ20190614-095417@2x" src="https://user-images.githubusercontent.com/13343921/59478020-6e611d00-8e8a-11e9-9e5e-c5515be826ba.png">

**Comment by pujiaxin33** [comment]
averageCellSpacingEnabled设置为NO即可
