### ISSUE TITLE
触发置顶操作后，在轻轻滚动下列表， 会自动回弹到下面列表

### ISSUE THREAD

**Issue by Eddiegooo** [pujiaxin33/JXPagingView#96]
**bug描述**
列表滚到最下面，触发置顶操作，然后轻轻滚动列表， 列表会自动滚到下面的位置。

**版本号**
1.JXPagingView版本号：我用的这个：https://github.com/pujiaxin33/JXPageListView
2.OC还是Swift版本：OC
3.手机系统版本号：12.2
4.手机型号：All

**复现步骤**
1. 将列表滚到下面
2.触发置顶操作
3.轻轻滚动列表，列表位置异常

**截图、GIF**
![896](https://user-images.githubusercontent.com/10209529/59480861-d583cf00-8e94-11e9-8b65-ba36eb34a007.gif)

大神辛苦了

**Comment by pujiaxin33** [comment]
朋友，你到这里：https://github.com/pujiaxin33/JXPageListView 提issue，而且JXPageListView最新版本点击状态栏只会滚动下面的列表，不会滚动整个列表。你去试一下呢
