### ISSUE TITLE
滚动后，点击事件都无效了

### ISSUE THREAD

**Issue by LockeXia** [pujiaxin33/JXPagingView#97]
**bug提交前阅读**
1.请先仔细阅读文档，尤其是【其他注意事项】文档，里面有常见问题的解决方案；
2.请先搜索已有的Issues，尝试找到相同问题的讨论；
3.请先阅读相关类的API、源码，尝试从源码找到答案；
4.如果以上步骤都未能解决你的疑问，欢迎提交ISSUE；

**bug描述**
请简单描述你的bug现象。

**版本号**
1.JXPagingView版本号：1.1.12
2.OC还是Swift版本：swift
3.手机系统版本号：12.3.1
4.手机型号：都是

**复现步骤**
1. 遇到问题的相关效果、类是：JXCategoryView
2.具体的操作步骤是：往下滑后，点击事件失效

**截图、GIF**
提供bug出现时的截图或者GIF。

**Comment by Z-Victory** [comment]
请问你是滚动后tableview的点击事件失效了吗，我遇到了这个问题
