### ISSUE TITLE
自定义悬停的headerview和列表联动

### ISSUE THREAD

**Issue by yuanxinliang** [pujiaxin33/JXPagingView#98]
1.如果用作者大神的悬停JXCategoryTitleView，
//关联contentScrollView，这样列表就可以和categoryView联动了。
categoryView.contentScrollView = pagingView.listContainerView.collectionView

2.如果我用自定义的悬停headerview的话，联动就要自己写，

当点击自定义悬停view的时候，我可以通过这段代码去控制pagingView的滚动
self.pageView.listContainerView.collectionView.scrollToItem(at: IndexPath(item: index, section: 0), at: .centeredHorizontally, animated: true)

当pagingView横向滚动的时候，并没有找到横向滚动之后可以监听的方法：

于是看了一下源码发现：
open class JXPagingListContainerView: UIView {
    unowned var delegate: JXPagingListContainerViewDelegate
找到这个类之后，发现这个代理并未开放出来，

在JXPagingListContainerView中也能找到这个滚动结束的代理，
public func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        self.mainTableView?.isScrollEnabled = true
    }

大神，请问能否把横向滚动之后的代理api开放出来，这样扩展行更好，谢谢大神

**Comment by pujiaxin33** [comment]
你可以参考`JXCategoryTitleView`内部原理，通过KVO `UIScrollView`的`contentOffset`属性来实现联动

**Comment by yuanxinliang** [comment]
嗯你的思路也可以，不过我现在的应用场景比较简单，就是滚动视图结束的时候获取就好了，我用通知中心发送就可以了，谢谢大神

**Comment by China-Gary** [comment]
大神,有一个问题,就是如果我头部不是一张图片,而是很多个控件的view....我一滚动的时候,底下的列表瞬间直接就悬停到屏幕顶部了,,没有那种一点一点向上滚动的视觉....

**Comment by pujiaxin33** [comment]
> .我一滚动的时候,底下的列表瞬间直接就悬停到屏幕顶部了

你这个应该是你使用问题。
之前有人出现类似的情况，是scrollCallback没有回调。
建议你仔细参考demo代码使用

**Comment by pujiaxin33** [comment]
> 大神,有一个问题,就是如果我头部不是一张图片,而是很多个控件的view....我一滚动的时候,底下的列表瞬间直接就悬停到屏幕顶部了,,没有那种一点一点向上滚动的视觉....

你这个应该是你使用问题。
之前有人出现类似的情况，是scrollCallback没有回调。
建议你仔细参考demo代码使用
