### ISSUE TITLE
大神，请教个问题

### ISSUE THREAD

**Issue by lion1993** [pujiaxin33/JXPagingView#99]
**bug描述**
我按照文档将框架用在的我的app中，我的悬浮层一共三个按钮，在代理中对应三个自定义的view
第一个view是普通的滚动视图，后两个是列表视图。
在向上滑动的时候，普通的滚动视图可以按照手势向上滚动，可是列表我稍微向上滑动，悬浮层立即带着列表紧贴到最上面（页面中的头部视图也瞬间消失，体验很不好）

**Comment by lion1993** [comment]
![UNADJUSTEDNONRAW_mini_4ed](https://user-images.githubusercontent.com/15356253/60167640-0e795780-9836-11e9-85a9-b128e1550d91.jpg)

**Comment by lion1993** [comment]
![RPReplay_Final1561540436 2](https://user-images.githubusercontent.com/15356253/60169614-a0369400-9839-11e9-960c-8e05b64c9848.gif)

**Comment by pujiaxin33** [comment]
之前有人跟你一样的问题，是他粗心漏了代码，不知道你是不是也是这样：
![image](https://user-images.githubusercontent.com/12654640/60169777-f3104b80-9839-11e9-88a3-d0ff8f3d9e4a.png)

**Comment by lion1993** [comment]
我这个方法里面是空实现。
我没有使用内部滚动视图的代理方法

**Comment by pujiaxin33** [comment]
你再认真看下文档和示例呢，一步一步校对一下

**Comment by lion1993** [comment]
校对了一天了，你看我补充的动图，一个有问题，一个没问题。。

**Comment by pujiaxin33** [comment]
> 第一个view是普通的滚动视图，后两个是列表视图。

你的意思后两个列表里面只是UIView，没有UIScrollView？

**Comment by lion1993** [comment]
有啊，第一个是普通的UISCrollView 后两个是UITableView

**Comment by pujiaxin33** [comment]
对了嘛，三个列表都是滚动视图，每个的scrollCallBack都要处理

**Comment by lion1993** [comment]
我都做了空实现。。三个都做了。因为我三个视图的滚动我都不做监听。

**Comment by pujiaxin33** [comment]
我不管你怎么空实现，反正你要持有scrollCallback，并且在scrollView滚动的时候，调用scrollCallback回调给pagingView

**Comment by lion1993** [comment]
啊～～这样啊。我以为不用监听就不用持有了。我在去试试～

**Comment by lion1993** [comment]
谢大神，终于好了。
